################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../osprey/libF77/_powci.c \
../osprey/libF77/_powcl.c \
../osprey/libF77/_powdi.c \
../osprey/libF77/_powdl.c \
../osprey/libF77/_powii.c \
../osprey/libF77/_powll.c \
../osprey/libF77/_powri.c \
../osprey/libF77/_powrl.c \
../osprey/libF77/_powzi.c \
../osprey/libF77/_powzl.c \
../osprey/libF77/and_b.c \
../osprey/libF77/and_h.c \
../osprey/libF77/and_l.c \
../osprey/libF77/and_ll.c \
../osprey/libF77/b_abs.c \
../osprey/libF77/b_dim.c \
../osprey/libF77/b_mod.c \
../osprey/libF77/b_sign.c \
../osprey/libF77/bclr_b.c \
../osprey/libF77/bclr_h.c \
../osprey/libF77/bclr_l.c \
../osprey/libF77/bclr_ll.c \
../osprey/libF77/bext_b.c \
../osprey/libF77/bext_h.c \
../osprey/libF77/bext_l.c \
../osprey/libF77/bext_ll.c \
../osprey/libF77/bittab.c \
../osprey/libF77/bset_b.c \
../osprey/libF77/bset_h.c \
../osprey/libF77/bset_l.c \
../osprey/libF77/bset_ll.c \
../osprey/libF77/btest_b.c \
../osprey/libF77/btest_h.c \
../osprey/libF77/btest_l.c \
../osprey/libF77/btest_ll.c \
../osprey/libF77/c_abs.c \
../osprey/libF77/c_cos.c \
../osprey/libF77/c_div.c \
../osprey/libF77/c_exp.c \
../osprey/libF77/c_log.c \
../osprey/libF77/c_sin.c \
../osprey/libF77/c_sqrt.c \
../osprey/libF77/cis_stubs.c \
../osprey/libF77/d_abs.c \
../osprey/libF77/d_acos.c \
../osprey/libF77/d_acosd.c \
../osprey/libF77/d_asin.c \
../osprey/libF77/d_asind.c \
../osprey/libF77/d_atan.c \
../osprey/libF77/d_atand.c \
../osprey/libF77/d_atn2.c \
../osprey/libF77/d_atn2d.c \
../osprey/libF77/d_cis.c \
../osprey/libF77/d_cnjg.c \
../osprey/libF77/d_cos.c \
../osprey/libF77/d_cosd.c \
../osprey/libF77/d_cosh.c \
../osprey/libF77/d_dim.c \
../osprey/libF77/d_exp.c \
../osprey/libF77/d_imag.c \
../osprey/libF77/d_imagalt.c \
../osprey/libF77/d_int.c \
../osprey/libF77/d_lg10.c \
../osprey/libF77/d_log.c \
../osprey/libF77/d_mod.c \
../osprey/libF77/d_nint.c \
../osprey/libF77/d_prod.c \
../osprey/libF77/d_sign.c \
../osprey/libF77/d_sin.c \
../osprey/libF77/d_sind.c \
../osprey/libF77/d_sinh.c \
../osprey/libF77/d_sqrt.c \
../osprey/libF77/d_tan.c \
../osprey/libF77/d_tand.c \
../osprey/libF77/d_tanh.c \
../osprey/libF77/derf_.c \
../osprey/libF77/derfc_.c \
../osprey/libF77/ef1asc_.c \
../osprey/libF77/ef1cmc_.c \
../osprey/libF77/erf_.c \
../osprey/libF77/erfc_.c \
../osprey/libF77/frts.c \
../osprey/libF77/gamma.c \
../osprey/libF77/h_abs.c \
../osprey/libF77/h_dim.c \
../osprey/libF77/h_dnnt.c \
../osprey/libF77/h_indx.c \
../osprey/libF77/h_len.c \
../osprey/libF77/h_lentrim.c \
../osprey/libF77/h_mod.c \
../osprey/libF77/h_nint.c \
../osprey/libF77/h_sign.c \
../osprey/libF77/hl_ge.c \
../osprey/libF77/hl_gt.c \
../osprey/libF77/hl_le.c \
../osprey/libF77/hl_lt.c \
../osprey/libF77/i_abs.c \
../osprey/libF77/i_dim.c \
../osprey/libF77/i_dnnt.c \
../osprey/libF77/i_indx.c \
../osprey/libF77/i_len.c \
../osprey/libF77/i_lentrim.c \
../osprey/libF77/i_mod.c \
../osprey/libF77/i_nint.c \
../osprey/libF77/i_sign.c \
../osprey/libF77/idint.c \
../osprey/libF77/irint.c \
../osprey/libF77/l_abs.c \
../osprey/libF77/l_dim.c \
../osprey/libF77/l_dnnt.c \
../osprey/libF77/l_ge.c \
../osprey/libF77/l_gt.c \
../osprey/libF77/l_indx.c \
../osprey/libF77/l_le.c \
../osprey/libF77/l_len.c \
../osprey/libF77/l_lentrim.c \
../osprey/libF77/l_lt.c \
../osprey/libF77/l_mod.c \
../osprey/libF77/l_nint.c \
../osprey/libF77/l_sign.c \
../osprey/libF77/lgamma.c \
../osprey/libF77/lnblnk_.c \
../osprey/libF77/main.c \
../osprey/libF77/map_datapool_.c \
../osprey/libF77/mclock_.c \
../osprey/libF77/mvbits.c \
../osprey/libF77/nargum.c \
../osprey/libF77/not_b.c \
../osprey/libF77/not_h.c \
../osprey/libF77/not_l.c \
../osprey/libF77/not_ll.c \
../osprey/libF77/or_b.c \
../osprey/libF77/or_h.c \
../osprey/libF77/or_l.c \
../osprey/libF77/or_ll.c \
../osprey/libF77/outstr_.c \
../osprey/libF77/pow_cc.c \
../osprey/libF77/pow_ci.c \
../osprey/libF77/pow_dd.c \
../osprey/libF77/pow_di.c \
../osprey/libF77/pow_hh.c \
../osprey/libF77/pow_ii.c \
../osprey/libF77/pow_ri.c \
../osprey/libF77/pow_zi.c \
../osprey/libF77/pow_zz.c \
../osprey/libF77/r_abs.c \
../osprey/libF77/r_acos.c \
../osprey/libF77/r_acosd.c \
../osprey/libF77/r_asin.c \
../osprey/libF77/r_asind.c \
../osprey/libF77/r_atan.c \
../osprey/libF77/r_atand.c \
../osprey/libF77/r_atn2.c \
../osprey/libF77/r_atn2d.c \
../osprey/libF77/r_cis.c \
../osprey/libF77/r_cnjg.c \
../osprey/libF77/r_cos.c \
../osprey/libF77/r_cosd.c \
../osprey/libF77/r_cosh.c \
../osprey/libF77/r_dim.c \
../osprey/libF77/r_exp.c \
../osprey/libF77/r_imag.c \
../osprey/libF77/r_int.c \
../osprey/libF77/r_lg10.c \
../osprey/libF77/r_log.c \
../osprey/libF77/r_mod.c \
../osprey/libF77/r_nint.c \
../osprey/libF77/r_sign.c \
../osprey/libF77/r_sin.c \
../osprey/libF77/r_sind.c \
../osprey/libF77/r_sinh.c \
../osprey/libF77/r_sqrt.c \
../osprey/libF77/r_tan.c \
../osprey/libF77/r_tand.c \
../osprey/libF77/r_tanh.c \
../osprey/libF77/ran_.c \
../osprey/libF77/s_abort.c \
../osprey/libF77/s_cat.c \
../osprey/libF77/s_cat_kai.c \
../osprey/libF77/s_cmp.c \
../osprey/libF77/s_copy.c \
../osprey/libF77/s_paus.c \
../osprey/libF77/s_rnge.c \
../osprey/libF77/s_srng.c \
../osprey/libF77/s_stop.c \
../osprey/libF77/set_args.c \
../osprey/libF77/shift_b.c \
../osprey/libF77/shift_h.c \
../osprey/libF77/shift_l.c \
../osprey/libF77/shift_ll.c \
../osprey/libF77/shiftc_b.c \
../osprey/libF77/shiftc_h.c \
../osprey/libF77/shiftc_l.c \
../osprey/libF77/shiftc_ll.c \
../osprey/libF77/signal_.c \
../osprey/libF77/sinh.c \
../osprey/libF77/subout.c \
../osprey/libF77/tanh.c \
../osprey/libF77/vararg.c \
../osprey/libF77/xor_b.c \
../osprey/libF77/xor_h.c \
../osprey/libF77/xor_l.c \
../osprey/libF77/xor_ll.c \
../osprey/libF77/z_abs.c \
../osprey/libF77/z_cos.c \
../osprey/libF77/z_div.c \
../osprey/libF77/z_exp.c \
../osprey/libF77/z_log.c \
../osprey/libF77/z_sin.c \
../osprey/libF77/z_sqrt.c 

OBJS += \
./osprey/libF77/_powci.o \
./osprey/libF77/_powcl.o \
./osprey/libF77/_powdi.o \
./osprey/libF77/_powdl.o \
./osprey/libF77/_powii.o \
./osprey/libF77/_powll.o \
./osprey/libF77/_powri.o \
./osprey/libF77/_powrl.o \
./osprey/libF77/_powzi.o \
./osprey/libF77/_powzl.o \
./osprey/libF77/and_b.o \
./osprey/libF77/and_h.o \
./osprey/libF77/and_l.o \
./osprey/libF77/and_ll.o \
./osprey/libF77/b_abs.o \
./osprey/libF77/b_dim.o \
./osprey/libF77/b_mod.o \
./osprey/libF77/b_sign.o \
./osprey/libF77/bclr_b.o \
./osprey/libF77/bclr_h.o \
./osprey/libF77/bclr_l.o \
./osprey/libF77/bclr_ll.o \
./osprey/libF77/bext_b.o \
./osprey/libF77/bext_h.o \
./osprey/libF77/bext_l.o \
./osprey/libF77/bext_ll.o \
./osprey/libF77/bittab.o \
./osprey/libF77/bset_b.o \
./osprey/libF77/bset_h.o \
./osprey/libF77/bset_l.o \
./osprey/libF77/bset_ll.o \
./osprey/libF77/btest_b.o \
./osprey/libF77/btest_h.o \
./osprey/libF77/btest_l.o \
./osprey/libF77/btest_ll.o \
./osprey/libF77/c_abs.o \
./osprey/libF77/c_cos.o \
./osprey/libF77/c_div.o \
./osprey/libF77/c_exp.o \
./osprey/libF77/c_log.o \
./osprey/libF77/c_sin.o \
./osprey/libF77/c_sqrt.o \
./osprey/libF77/cis_stubs.o \
./osprey/libF77/d_abs.o \
./osprey/libF77/d_acos.o \
./osprey/libF77/d_acosd.o \
./osprey/libF77/d_asin.o \
./osprey/libF77/d_asind.o \
./osprey/libF77/d_atan.o \
./osprey/libF77/d_atand.o \
./osprey/libF77/d_atn2.o \
./osprey/libF77/d_atn2d.o \
./osprey/libF77/d_cis.o \
./osprey/libF77/d_cnjg.o \
./osprey/libF77/d_cos.o \
./osprey/libF77/d_cosd.o \
./osprey/libF77/d_cosh.o \
./osprey/libF77/d_dim.o \
./osprey/libF77/d_exp.o \
./osprey/libF77/d_imag.o \
./osprey/libF77/d_imagalt.o \
./osprey/libF77/d_int.o \
./osprey/libF77/d_lg10.o \
./osprey/libF77/d_log.o \
./osprey/libF77/d_mod.o \
./osprey/libF77/d_nint.o \
./osprey/libF77/d_prod.o \
./osprey/libF77/d_sign.o \
./osprey/libF77/d_sin.o \
./osprey/libF77/d_sind.o \
./osprey/libF77/d_sinh.o \
./osprey/libF77/d_sqrt.o \
./osprey/libF77/d_tan.o \
./osprey/libF77/d_tand.o \
./osprey/libF77/d_tanh.o \
./osprey/libF77/derf_.o \
./osprey/libF77/derfc_.o \
./osprey/libF77/ef1asc_.o \
./osprey/libF77/ef1cmc_.o \
./osprey/libF77/erf_.o \
./osprey/libF77/erfc_.o \
./osprey/libF77/frts.o \
./osprey/libF77/gamma.o \
./osprey/libF77/h_abs.o \
./osprey/libF77/h_dim.o \
./osprey/libF77/h_dnnt.o \
./osprey/libF77/h_indx.o \
./osprey/libF77/h_len.o \
./osprey/libF77/h_lentrim.o \
./osprey/libF77/h_mod.o \
./osprey/libF77/h_nint.o \
./osprey/libF77/h_sign.o \
./osprey/libF77/hl_ge.o \
./osprey/libF77/hl_gt.o \
./osprey/libF77/hl_le.o \
./osprey/libF77/hl_lt.o \
./osprey/libF77/i_abs.o \
./osprey/libF77/i_dim.o \
./osprey/libF77/i_dnnt.o \
./osprey/libF77/i_indx.o \
./osprey/libF77/i_len.o \
./osprey/libF77/i_lentrim.o \
./osprey/libF77/i_mod.o \
./osprey/libF77/i_nint.o \
./osprey/libF77/i_sign.o \
./osprey/libF77/idint.o \
./osprey/libF77/irint.o \
./osprey/libF77/l_abs.o \
./osprey/libF77/l_dim.o \
./osprey/libF77/l_dnnt.o \
./osprey/libF77/l_ge.o \
./osprey/libF77/l_gt.o \
./osprey/libF77/l_indx.o \
./osprey/libF77/l_le.o \
./osprey/libF77/l_len.o \
./osprey/libF77/l_lentrim.o \
./osprey/libF77/l_lt.o \
./osprey/libF77/l_mod.o \
./osprey/libF77/l_nint.o \
./osprey/libF77/l_sign.o \
./osprey/libF77/lgamma.o \
./osprey/libF77/lnblnk_.o \
./osprey/libF77/main.o \
./osprey/libF77/map_datapool_.o \
./osprey/libF77/mclock_.o \
./osprey/libF77/mvbits.o \
./osprey/libF77/nargum.o \
./osprey/libF77/not_b.o \
./osprey/libF77/not_h.o \
./osprey/libF77/not_l.o \
./osprey/libF77/not_ll.o \
./osprey/libF77/or_b.o \
./osprey/libF77/or_h.o \
./osprey/libF77/or_l.o \
./osprey/libF77/or_ll.o \
./osprey/libF77/outstr_.o \
./osprey/libF77/pow_cc.o \
./osprey/libF77/pow_ci.o \
./osprey/libF77/pow_dd.o \
./osprey/libF77/pow_di.o \
./osprey/libF77/pow_hh.o \
./osprey/libF77/pow_ii.o \
./osprey/libF77/pow_ri.o \
./osprey/libF77/pow_zi.o \
./osprey/libF77/pow_zz.o \
./osprey/libF77/r_abs.o \
./osprey/libF77/r_acos.o \
./osprey/libF77/r_acosd.o \
./osprey/libF77/r_asin.o \
./osprey/libF77/r_asind.o \
./osprey/libF77/r_atan.o \
./osprey/libF77/r_atand.o \
./osprey/libF77/r_atn2.o \
./osprey/libF77/r_atn2d.o \
./osprey/libF77/r_cis.o \
./osprey/libF77/r_cnjg.o \
./osprey/libF77/r_cos.o \
./osprey/libF77/r_cosd.o \
./osprey/libF77/r_cosh.o \
./osprey/libF77/r_dim.o \
./osprey/libF77/r_exp.o \
./osprey/libF77/r_imag.o \
./osprey/libF77/r_int.o \
./osprey/libF77/r_lg10.o \
./osprey/libF77/r_log.o \
./osprey/libF77/r_mod.o \
./osprey/libF77/r_nint.o \
./osprey/libF77/r_sign.o \
./osprey/libF77/r_sin.o \
./osprey/libF77/r_sind.o \
./osprey/libF77/r_sinh.o \
./osprey/libF77/r_sqrt.o \
./osprey/libF77/r_tan.o \
./osprey/libF77/r_tand.o \
./osprey/libF77/r_tanh.o \
./osprey/libF77/ran_.o \
./osprey/libF77/s_abort.o \
./osprey/libF77/s_cat.o \
./osprey/libF77/s_cat_kai.o \
./osprey/libF77/s_cmp.o \
./osprey/libF77/s_copy.o \
./osprey/libF77/s_paus.o \
./osprey/libF77/s_rnge.o \
./osprey/libF77/s_srng.o \
./osprey/libF77/s_stop.o \
./osprey/libF77/set_args.o \
./osprey/libF77/shift_b.o \
./osprey/libF77/shift_h.o \
./osprey/libF77/shift_l.o \
./osprey/libF77/shift_ll.o \
./osprey/libF77/shiftc_b.o \
./osprey/libF77/shiftc_h.o \
./osprey/libF77/shiftc_l.o \
./osprey/libF77/shiftc_ll.o \
./osprey/libF77/signal_.o \
./osprey/libF77/sinh.o \
./osprey/libF77/subout.o \
./osprey/libF77/tanh.o \
./osprey/libF77/vararg.o \
./osprey/libF77/xor_b.o \
./osprey/libF77/xor_h.o \
./osprey/libF77/xor_l.o \
./osprey/libF77/xor_ll.o \
./osprey/libF77/z_abs.o \
./osprey/libF77/z_cos.o \
./osprey/libF77/z_div.o \
./osprey/libF77/z_exp.o \
./osprey/libF77/z_log.o \
./osprey/libF77/z_sin.o \
./osprey/libF77/z_sqrt.o 

C_DEPS += \
./osprey/libF77/_powci.d \
./osprey/libF77/_powcl.d \
./osprey/libF77/_powdi.d \
./osprey/libF77/_powdl.d \
./osprey/libF77/_powii.d \
./osprey/libF77/_powll.d \
./osprey/libF77/_powri.d \
./osprey/libF77/_powrl.d \
./osprey/libF77/_powzi.d \
./osprey/libF77/_powzl.d \
./osprey/libF77/and_b.d \
./osprey/libF77/and_h.d \
./osprey/libF77/and_l.d \
./osprey/libF77/and_ll.d \
./osprey/libF77/b_abs.d \
./osprey/libF77/b_dim.d \
./osprey/libF77/b_mod.d \
./osprey/libF77/b_sign.d \
./osprey/libF77/bclr_b.d \
./osprey/libF77/bclr_h.d \
./osprey/libF77/bclr_l.d \
./osprey/libF77/bclr_ll.d \
./osprey/libF77/bext_b.d \
./osprey/libF77/bext_h.d \
./osprey/libF77/bext_l.d \
./osprey/libF77/bext_ll.d \
./osprey/libF77/bittab.d \
./osprey/libF77/bset_b.d \
./osprey/libF77/bset_h.d \
./osprey/libF77/bset_l.d \
./osprey/libF77/bset_ll.d \
./osprey/libF77/btest_b.d \
./osprey/libF77/btest_h.d \
./osprey/libF77/btest_l.d \
./osprey/libF77/btest_ll.d \
./osprey/libF77/c_abs.d \
./osprey/libF77/c_cos.d \
./osprey/libF77/c_div.d \
./osprey/libF77/c_exp.d \
./osprey/libF77/c_log.d \
./osprey/libF77/c_sin.d \
./osprey/libF77/c_sqrt.d \
./osprey/libF77/cis_stubs.d \
./osprey/libF77/d_abs.d \
./osprey/libF77/d_acos.d \
./osprey/libF77/d_acosd.d \
./osprey/libF77/d_asin.d \
./osprey/libF77/d_asind.d \
./osprey/libF77/d_atan.d \
./osprey/libF77/d_atand.d \
./osprey/libF77/d_atn2.d \
./osprey/libF77/d_atn2d.d \
./osprey/libF77/d_cis.d \
./osprey/libF77/d_cnjg.d \
./osprey/libF77/d_cos.d \
./osprey/libF77/d_cosd.d \
./osprey/libF77/d_cosh.d \
./osprey/libF77/d_dim.d \
./osprey/libF77/d_exp.d \
./osprey/libF77/d_imag.d \
./osprey/libF77/d_imagalt.d \
./osprey/libF77/d_int.d \
./osprey/libF77/d_lg10.d \
./osprey/libF77/d_log.d \
./osprey/libF77/d_mod.d \
./osprey/libF77/d_nint.d \
./osprey/libF77/d_prod.d \
./osprey/libF77/d_sign.d \
./osprey/libF77/d_sin.d \
./osprey/libF77/d_sind.d \
./osprey/libF77/d_sinh.d \
./osprey/libF77/d_sqrt.d \
./osprey/libF77/d_tan.d \
./osprey/libF77/d_tand.d \
./osprey/libF77/d_tanh.d \
./osprey/libF77/derf_.d \
./osprey/libF77/derfc_.d \
./osprey/libF77/ef1asc_.d \
./osprey/libF77/ef1cmc_.d \
./osprey/libF77/erf_.d \
./osprey/libF77/erfc_.d \
./osprey/libF77/frts.d \
./osprey/libF77/gamma.d \
./osprey/libF77/h_abs.d \
./osprey/libF77/h_dim.d \
./osprey/libF77/h_dnnt.d \
./osprey/libF77/h_indx.d \
./osprey/libF77/h_len.d \
./osprey/libF77/h_lentrim.d \
./osprey/libF77/h_mod.d \
./osprey/libF77/h_nint.d \
./osprey/libF77/h_sign.d \
./osprey/libF77/hl_ge.d \
./osprey/libF77/hl_gt.d \
./osprey/libF77/hl_le.d \
./osprey/libF77/hl_lt.d \
./osprey/libF77/i_abs.d \
./osprey/libF77/i_dim.d \
./osprey/libF77/i_dnnt.d \
./osprey/libF77/i_indx.d \
./osprey/libF77/i_len.d \
./osprey/libF77/i_lentrim.d \
./osprey/libF77/i_mod.d \
./osprey/libF77/i_nint.d \
./osprey/libF77/i_sign.d \
./osprey/libF77/idint.d \
./osprey/libF77/irint.d \
./osprey/libF77/l_abs.d \
./osprey/libF77/l_dim.d \
./osprey/libF77/l_dnnt.d \
./osprey/libF77/l_ge.d \
./osprey/libF77/l_gt.d \
./osprey/libF77/l_indx.d \
./osprey/libF77/l_le.d \
./osprey/libF77/l_len.d \
./osprey/libF77/l_lentrim.d \
./osprey/libF77/l_lt.d \
./osprey/libF77/l_mod.d \
./osprey/libF77/l_nint.d \
./osprey/libF77/l_sign.d \
./osprey/libF77/lgamma.d \
./osprey/libF77/lnblnk_.d \
./osprey/libF77/main.d \
./osprey/libF77/map_datapool_.d \
./osprey/libF77/mclock_.d \
./osprey/libF77/mvbits.d \
./osprey/libF77/nargum.d \
./osprey/libF77/not_b.d \
./osprey/libF77/not_h.d \
./osprey/libF77/not_l.d \
./osprey/libF77/not_ll.d \
./osprey/libF77/or_b.d \
./osprey/libF77/or_h.d \
./osprey/libF77/or_l.d \
./osprey/libF77/or_ll.d \
./osprey/libF77/outstr_.d \
./osprey/libF77/pow_cc.d \
./osprey/libF77/pow_ci.d \
./osprey/libF77/pow_dd.d \
./osprey/libF77/pow_di.d \
./osprey/libF77/pow_hh.d \
./osprey/libF77/pow_ii.d \
./osprey/libF77/pow_ri.d \
./osprey/libF77/pow_zi.d \
./osprey/libF77/pow_zz.d \
./osprey/libF77/r_abs.d \
./osprey/libF77/r_acos.d \
./osprey/libF77/r_acosd.d \
./osprey/libF77/r_asin.d \
./osprey/libF77/r_asind.d \
./osprey/libF77/r_atan.d \
./osprey/libF77/r_atand.d \
./osprey/libF77/r_atn2.d \
./osprey/libF77/r_atn2d.d \
./osprey/libF77/r_cis.d \
./osprey/libF77/r_cnjg.d \
./osprey/libF77/r_cos.d \
./osprey/libF77/r_cosd.d \
./osprey/libF77/r_cosh.d \
./osprey/libF77/r_dim.d \
./osprey/libF77/r_exp.d \
./osprey/libF77/r_imag.d \
./osprey/libF77/r_int.d \
./osprey/libF77/r_lg10.d \
./osprey/libF77/r_log.d \
./osprey/libF77/r_mod.d \
./osprey/libF77/r_nint.d \
./osprey/libF77/r_sign.d \
./osprey/libF77/r_sin.d \
./osprey/libF77/r_sind.d \
./osprey/libF77/r_sinh.d \
./osprey/libF77/r_sqrt.d \
./osprey/libF77/r_tan.d \
./osprey/libF77/r_tand.d \
./osprey/libF77/r_tanh.d \
./osprey/libF77/ran_.d \
./osprey/libF77/s_abort.d \
./osprey/libF77/s_cat.d \
./osprey/libF77/s_cat_kai.d \
./osprey/libF77/s_cmp.d \
./osprey/libF77/s_copy.d \
./osprey/libF77/s_paus.d \
./osprey/libF77/s_rnge.d \
./osprey/libF77/s_srng.d \
./osprey/libF77/s_stop.d \
./osprey/libF77/set_args.d \
./osprey/libF77/shift_b.d \
./osprey/libF77/shift_h.d \
./osprey/libF77/shift_l.d \
./osprey/libF77/shift_ll.d \
./osprey/libF77/shiftc_b.d \
./osprey/libF77/shiftc_h.d \
./osprey/libF77/shiftc_l.d \
./osprey/libF77/shiftc_ll.d \
./osprey/libF77/signal_.d \
./osprey/libF77/sinh.d \
./osprey/libF77/subout.d \
./osprey/libF77/tanh.d \
./osprey/libF77/vararg.d \
./osprey/libF77/xor_b.d \
./osprey/libF77/xor_h.d \
./osprey/libF77/xor_l.d \
./osprey/libF77/xor_ll.d \
./osprey/libF77/z_abs.d \
./osprey/libF77/z_cos.d \
./osprey/libF77/z_div.d \
./osprey/libF77/z_exp.d \
./osprey/libF77/z_log.d \
./osprey/libF77/z_sin.d \
./osprey/libF77/z_sqrt.d 


# Each subdirectory must supply rules for building sources it contributes
osprey/libF77/%.o: ../osprey/libF77/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


