################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../osprey/libacml_mv/src/acos.c \
../osprey/libacml_mv/src/acosf.c \
../osprey/libacml_mv/src/acosh.c \
../osprey/libacml_mv/src/acoshf.c \
../osprey/libacml_mv/src/asin.c \
../osprey/libacml_mv/src/asinf.c \
../osprey/libacml_mv/src/asinh.c \
../osprey/libacml_mv/src/asinhf.c \
../osprey/libacml_mv/src/atan.c \
../osprey/libacml_mv/src/atan2.c \
../osprey/libacml_mv/src/atan2f.c \
../osprey/libacml_mv/src/atanf.c \
../osprey/libacml_mv/src/atanh.c \
../osprey/libacml_mv/src/atanhf.c \
../osprey/libacml_mv/src/ceil.c \
../osprey/libacml_mv/src/ceilf.c \
../osprey/libacml_mv/src/cosh.c \
../osprey/libacml_mv/src/coshf.c \
../osprey/libacml_mv/src/exp_special.c \
../osprey/libacml_mv/src/finite.c \
../osprey/libacml_mv/src/finitef.c \
../osprey/libacml_mv/src/floor.c \
../osprey/libacml_mv/src/floorf.c \
../osprey/libacml_mv/src/frexp.c \
../osprey/libacml_mv/src/frexpf.c \
../osprey/libacml_mv/src/hypot.c \
../osprey/libacml_mv/src/hypotf.c \
../osprey/libacml_mv/src/ilogb.c \
../osprey/libacml_mv/src/ilogbf.c \
../osprey/libacml_mv/src/ldexp.c \
../osprey/libacml_mv/src/ldexpf.c \
../osprey/libacml_mv/src/libm_special.c \
../osprey/libacml_mv/src/llrint.c \
../osprey/libacml_mv/src/llrintf.c \
../osprey/libacml_mv/src/llround.c \
../osprey/libacml_mv/src/llroundf.c \
../osprey/libacml_mv/src/log1p.c \
../osprey/libacml_mv/src/log1pf.c \
../osprey/libacml_mv/src/log_special.c \
../osprey/libacml_mv/src/logb.c \
../osprey/libacml_mv/src/logbf.c \
../osprey/libacml_mv/src/lrint.c \
../osprey/libacml_mv/src/lrintf.c \
../osprey/libacml_mv/src/lround.c \
../osprey/libacml_mv/src/lroundf.c \
../osprey/libacml_mv/src/modf.c \
../osprey/libacml_mv/src/modff.c \
../osprey/libacml_mv/src/nan.c \
../osprey/libacml_mv/src/nanf.c \
../osprey/libacml_mv/src/nearbyintf.c \
../osprey/libacml_mv/src/nextafter.c \
../osprey/libacml_mv/src/nextafterf.c \
../osprey/libacml_mv/src/nexttoward.c \
../osprey/libacml_mv/src/nexttowardf.c \
../osprey/libacml_mv/src/pow_special.c \
../osprey/libacml_mv/src/remainder_piby2.c \
../osprey/libacml_mv/src/remainder_piby2d2f.c \
../osprey/libacml_mv/src/rint.c \
../osprey/libacml_mv/src/rintf.c \
../osprey/libacml_mv/src/roundf.c \
../osprey/libacml_mv/src/scalbln.c \
../osprey/libacml_mv/src/scalblnf.c \
../osprey/libacml_mv/src/scalbn.c \
../osprey/libacml_mv/src/scalbnf.c \
../osprey/libacml_mv/src/sincos_special.c \
../osprey/libacml_mv/src/sinh.c \
../osprey/libacml_mv/src/sinhf.c \
../osprey/libacml_mv/src/sqrt.c \
../osprey/libacml_mv/src/sqrtf.c \
../osprey/libacml_mv/src/tan.c \
../osprey/libacml_mv/src/tanf.c \
../osprey/libacml_mv/src/tanh.c \
../osprey/libacml_mv/src/tanhf.c 

OBJS += \
./osprey/libacml_mv/src/acos.o \
./osprey/libacml_mv/src/acosf.o \
./osprey/libacml_mv/src/acosh.o \
./osprey/libacml_mv/src/acoshf.o \
./osprey/libacml_mv/src/asin.o \
./osprey/libacml_mv/src/asinf.o \
./osprey/libacml_mv/src/asinh.o \
./osprey/libacml_mv/src/asinhf.o \
./osprey/libacml_mv/src/atan.o \
./osprey/libacml_mv/src/atan2.o \
./osprey/libacml_mv/src/atan2f.o \
./osprey/libacml_mv/src/atanf.o \
./osprey/libacml_mv/src/atanh.o \
./osprey/libacml_mv/src/atanhf.o \
./osprey/libacml_mv/src/ceil.o \
./osprey/libacml_mv/src/ceilf.o \
./osprey/libacml_mv/src/cosh.o \
./osprey/libacml_mv/src/coshf.o \
./osprey/libacml_mv/src/exp_special.o \
./osprey/libacml_mv/src/finite.o \
./osprey/libacml_mv/src/finitef.o \
./osprey/libacml_mv/src/floor.o \
./osprey/libacml_mv/src/floorf.o \
./osprey/libacml_mv/src/frexp.o \
./osprey/libacml_mv/src/frexpf.o \
./osprey/libacml_mv/src/hypot.o \
./osprey/libacml_mv/src/hypotf.o \
./osprey/libacml_mv/src/ilogb.o \
./osprey/libacml_mv/src/ilogbf.o \
./osprey/libacml_mv/src/ldexp.o \
./osprey/libacml_mv/src/ldexpf.o \
./osprey/libacml_mv/src/libm_special.o \
./osprey/libacml_mv/src/llrint.o \
./osprey/libacml_mv/src/llrintf.o \
./osprey/libacml_mv/src/llround.o \
./osprey/libacml_mv/src/llroundf.o \
./osprey/libacml_mv/src/log1p.o \
./osprey/libacml_mv/src/log1pf.o \
./osprey/libacml_mv/src/log_special.o \
./osprey/libacml_mv/src/logb.o \
./osprey/libacml_mv/src/logbf.o \
./osprey/libacml_mv/src/lrint.o \
./osprey/libacml_mv/src/lrintf.o \
./osprey/libacml_mv/src/lround.o \
./osprey/libacml_mv/src/lroundf.o \
./osprey/libacml_mv/src/modf.o \
./osprey/libacml_mv/src/modff.o \
./osprey/libacml_mv/src/nan.o \
./osprey/libacml_mv/src/nanf.o \
./osprey/libacml_mv/src/nearbyintf.o \
./osprey/libacml_mv/src/nextafter.o \
./osprey/libacml_mv/src/nextafterf.o \
./osprey/libacml_mv/src/nexttoward.o \
./osprey/libacml_mv/src/nexttowardf.o \
./osprey/libacml_mv/src/pow_special.o \
./osprey/libacml_mv/src/remainder_piby2.o \
./osprey/libacml_mv/src/remainder_piby2d2f.o \
./osprey/libacml_mv/src/rint.o \
./osprey/libacml_mv/src/rintf.o \
./osprey/libacml_mv/src/roundf.o \
./osprey/libacml_mv/src/scalbln.o \
./osprey/libacml_mv/src/scalblnf.o \
./osprey/libacml_mv/src/scalbn.o \
./osprey/libacml_mv/src/scalbnf.o \
./osprey/libacml_mv/src/sincos_special.o \
./osprey/libacml_mv/src/sinh.o \
./osprey/libacml_mv/src/sinhf.o \
./osprey/libacml_mv/src/sqrt.o \
./osprey/libacml_mv/src/sqrtf.o \
./osprey/libacml_mv/src/tan.o \
./osprey/libacml_mv/src/tanf.o \
./osprey/libacml_mv/src/tanh.o \
./osprey/libacml_mv/src/tanhf.o 

C_DEPS += \
./osprey/libacml_mv/src/acos.d \
./osprey/libacml_mv/src/acosf.d \
./osprey/libacml_mv/src/acosh.d \
./osprey/libacml_mv/src/acoshf.d \
./osprey/libacml_mv/src/asin.d \
./osprey/libacml_mv/src/asinf.d \
./osprey/libacml_mv/src/asinh.d \
./osprey/libacml_mv/src/asinhf.d \
./osprey/libacml_mv/src/atan.d \
./osprey/libacml_mv/src/atan2.d \
./osprey/libacml_mv/src/atan2f.d \
./osprey/libacml_mv/src/atanf.d \
./osprey/libacml_mv/src/atanh.d \
./osprey/libacml_mv/src/atanhf.d \
./osprey/libacml_mv/src/ceil.d \
./osprey/libacml_mv/src/ceilf.d \
./osprey/libacml_mv/src/cosh.d \
./osprey/libacml_mv/src/coshf.d \
./osprey/libacml_mv/src/exp_special.d \
./osprey/libacml_mv/src/finite.d \
./osprey/libacml_mv/src/finitef.d \
./osprey/libacml_mv/src/floor.d \
./osprey/libacml_mv/src/floorf.d \
./osprey/libacml_mv/src/frexp.d \
./osprey/libacml_mv/src/frexpf.d \
./osprey/libacml_mv/src/hypot.d \
./osprey/libacml_mv/src/hypotf.d \
./osprey/libacml_mv/src/ilogb.d \
./osprey/libacml_mv/src/ilogbf.d \
./osprey/libacml_mv/src/ldexp.d \
./osprey/libacml_mv/src/ldexpf.d \
./osprey/libacml_mv/src/libm_special.d \
./osprey/libacml_mv/src/llrint.d \
./osprey/libacml_mv/src/llrintf.d \
./osprey/libacml_mv/src/llround.d \
./osprey/libacml_mv/src/llroundf.d \
./osprey/libacml_mv/src/log1p.d \
./osprey/libacml_mv/src/log1pf.d \
./osprey/libacml_mv/src/log_special.d \
./osprey/libacml_mv/src/logb.d \
./osprey/libacml_mv/src/logbf.d \
./osprey/libacml_mv/src/lrint.d \
./osprey/libacml_mv/src/lrintf.d \
./osprey/libacml_mv/src/lround.d \
./osprey/libacml_mv/src/lroundf.d \
./osprey/libacml_mv/src/modf.d \
./osprey/libacml_mv/src/modff.d \
./osprey/libacml_mv/src/nan.d \
./osprey/libacml_mv/src/nanf.d \
./osprey/libacml_mv/src/nearbyintf.d \
./osprey/libacml_mv/src/nextafter.d \
./osprey/libacml_mv/src/nextafterf.d \
./osprey/libacml_mv/src/nexttoward.d \
./osprey/libacml_mv/src/nexttowardf.d \
./osprey/libacml_mv/src/pow_special.d \
./osprey/libacml_mv/src/remainder_piby2.d \
./osprey/libacml_mv/src/remainder_piby2d2f.d \
./osprey/libacml_mv/src/rint.d \
./osprey/libacml_mv/src/rintf.d \
./osprey/libacml_mv/src/roundf.d \
./osprey/libacml_mv/src/scalbln.d \
./osprey/libacml_mv/src/scalblnf.d \
./osprey/libacml_mv/src/scalbn.d \
./osprey/libacml_mv/src/scalbnf.d \
./osprey/libacml_mv/src/sincos_special.d \
./osprey/libacml_mv/src/sinh.d \
./osprey/libacml_mv/src/sinhf.d \
./osprey/libacml_mv/src/sqrt.d \
./osprey/libacml_mv/src/sqrtf.d \
./osprey/libacml_mv/src/tan.d \
./osprey/libacml_mv/src/tanf.d \
./osprey/libacml_mv/src/tanh.d \
./osprey/libacml_mv/src/tanhf.d 


# Each subdirectory must supply rules for building sources it contributes
osprey/libacml_mv/src/%.o: ../osprey/libacml_mv/src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


