################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../osprey/libu/clib/access.c \
../osprey/libu/clib/alarm.c \
../osprey/libu/clib/atexit.c \
../osprey/libu/clib/brk.c \
../osprey/libu/clib/chdir.c \
../osprey/libu/clib/chmod.c \
../osprey/libu/clib/chown.c \
../osprey/libu/clib/chroot.c \
../osprey/libu/clib/clibcall.c \
../osprey/libu/clib/close.c \
../osprey/libu/clib/cpselect.c \
../osprey/libu/clib/creat.c \
../osprey/libu/clib/dup.c \
../osprey/libu/clib/exit.c \
../osprey/libu/clib/fclose.c \
../osprey/libu/clib/fcntl.c \
../osprey/libu/clib/fdopen.c \
../osprey/libu/clib/fflush.c \
../osprey/libu/clib/fgets.c \
../osprey/libu/clib/fileno.c \
../osprey/libu/clib/fopen.c \
../osprey/libu/clib/fork.c \
../osprey/libu/clib/fputs.c \
../osprey/libu/clib/fread.c \
../osprey/libu/clib/freopen.c \
../osprey/libu/clib/fseek.c \
../osprey/libu/clib/ftell.c \
../osprey/libu/clib/fwrite.c \
../osprey/libu/clib/getcwd.c \
../osprey/libu/clib/getegid.c \
../osprey/libu/clib/getenv.c \
../osprey/libu/clib/geteuid.c \
../osprey/libu/clib/getgid.c \
../osprey/libu/clib/gethost.c \
../osprey/libu/clib/getopt.c \
../osprey/libu/clib/getpgrp.c \
../osprey/libu/clib/getpid.c \
../osprey/libu/clib/getppid.c \
../osprey/libu/clib/getuid.c \
../osprey/libu/clib/ialloc.c \
../osprey/libu/clib/ioctl.c \
../osprey/libu/clib/kill.c \
../osprey/libu/clib/limit.c \
../osprey/libu/clib/link.c \
../osprey/libu/clib/lseek.c \
../osprey/libu/clib/mknod.c \
../osprey/libu/clib/mktemp.c \
../osprey/libu/clib/newexit.c \
../osprey/libu/clib/newgetpid.c \
../osprey/libu/clib/newgetppid.c \
../osprey/libu/clib/nice.c \
../osprey/libu/clib/nicem.c \
../osprey/libu/clib/nlimit.c \
../osprey/libu/clib/open.c \
../osprey/libu/clib/pause.c \
../osprey/libu/clib/pipe.c \
../osprey/libu/clib/plock.c \
../osprey/libu/clib/ptrace.c \
../osprey/libu/clib/putenv.c \
../osprey/libu/clib/reada.c \
../osprey/libu/clib/rename.c \
../osprey/libu/clib/resume.c \
../osprey/libu/clib/sbreak.c \
../osprey/libu/clib/sbrk.c \
../osprey/libu/clib/setgid.c \
../osprey/libu/clib/setpgrp.c \
../osprey/libu/clib/setuid.c \
../osprey/libu/clib/shutdreg.c \
../osprey/libu/clib/shutdsav.c \
../osprey/libu/clib/sigctl.c \
../osprey/libu/clib/signal.c \
../osprey/libu/clib/sleep.c \
../osprey/libu/clib/stat.c \
../osprey/libu/clib/suspend.c \
../osprey/libu/clib/sync.c \
../osprey/libu/clib/tempnam.c \
../osprey/libu/clib/time.c \
../osprey/libu/clib/times.c \
../osprey/libu/clib/tmpfile.c \
../osprey/libu/clib/trunc.c \
../osprey/libu/clib/ulimit.c \
../osprey/libu/clib/umask.c \
../osprey/libu/clib/uname.c \
../osprey/libu/clib/unlink.c \
../osprey/libu/clib/ustat.c \
../osprey/libu/clib/utime.c \
../osprey/libu/clib/wait.c \
../osprey/libu/clib/writea.c 

OBJS += \
./osprey/libu/clib/access.o \
./osprey/libu/clib/alarm.o \
./osprey/libu/clib/atexit.o \
./osprey/libu/clib/brk.o \
./osprey/libu/clib/chdir.o \
./osprey/libu/clib/chmod.o \
./osprey/libu/clib/chown.o \
./osprey/libu/clib/chroot.o \
./osprey/libu/clib/clibcall.o \
./osprey/libu/clib/close.o \
./osprey/libu/clib/cpselect.o \
./osprey/libu/clib/creat.o \
./osprey/libu/clib/dup.o \
./osprey/libu/clib/exit.o \
./osprey/libu/clib/fclose.o \
./osprey/libu/clib/fcntl.o \
./osprey/libu/clib/fdopen.o \
./osprey/libu/clib/fflush.o \
./osprey/libu/clib/fgets.o \
./osprey/libu/clib/fileno.o \
./osprey/libu/clib/fopen.o \
./osprey/libu/clib/fork.o \
./osprey/libu/clib/fputs.o \
./osprey/libu/clib/fread.o \
./osprey/libu/clib/freopen.o \
./osprey/libu/clib/fseek.o \
./osprey/libu/clib/ftell.o \
./osprey/libu/clib/fwrite.o \
./osprey/libu/clib/getcwd.o \
./osprey/libu/clib/getegid.o \
./osprey/libu/clib/getenv.o \
./osprey/libu/clib/geteuid.o \
./osprey/libu/clib/getgid.o \
./osprey/libu/clib/gethost.o \
./osprey/libu/clib/getopt.o \
./osprey/libu/clib/getpgrp.o \
./osprey/libu/clib/getpid.o \
./osprey/libu/clib/getppid.o \
./osprey/libu/clib/getuid.o \
./osprey/libu/clib/ialloc.o \
./osprey/libu/clib/ioctl.o \
./osprey/libu/clib/kill.o \
./osprey/libu/clib/limit.o \
./osprey/libu/clib/link.o \
./osprey/libu/clib/lseek.o \
./osprey/libu/clib/mknod.o \
./osprey/libu/clib/mktemp.o \
./osprey/libu/clib/newexit.o \
./osprey/libu/clib/newgetpid.o \
./osprey/libu/clib/newgetppid.o \
./osprey/libu/clib/nice.o \
./osprey/libu/clib/nicem.o \
./osprey/libu/clib/nlimit.o \
./osprey/libu/clib/open.o \
./osprey/libu/clib/pause.o \
./osprey/libu/clib/pipe.o \
./osprey/libu/clib/plock.o \
./osprey/libu/clib/ptrace.o \
./osprey/libu/clib/putenv.o \
./osprey/libu/clib/reada.o \
./osprey/libu/clib/rename.o \
./osprey/libu/clib/resume.o \
./osprey/libu/clib/sbreak.o \
./osprey/libu/clib/sbrk.o \
./osprey/libu/clib/setgid.o \
./osprey/libu/clib/setpgrp.o \
./osprey/libu/clib/setuid.o \
./osprey/libu/clib/shutdreg.o \
./osprey/libu/clib/shutdsav.o \
./osprey/libu/clib/sigctl.o \
./osprey/libu/clib/signal.o \
./osprey/libu/clib/sleep.o \
./osprey/libu/clib/stat.o \
./osprey/libu/clib/suspend.o \
./osprey/libu/clib/sync.o \
./osprey/libu/clib/tempnam.o \
./osprey/libu/clib/time.o \
./osprey/libu/clib/times.o \
./osprey/libu/clib/tmpfile.o \
./osprey/libu/clib/trunc.o \
./osprey/libu/clib/ulimit.o \
./osprey/libu/clib/umask.o \
./osprey/libu/clib/uname.o \
./osprey/libu/clib/unlink.o \
./osprey/libu/clib/ustat.o \
./osprey/libu/clib/utime.o \
./osprey/libu/clib/wait.o \
./osprey/libu/clib/writea.o 

C_DEPS += \
./osprey/libu/clib/access.d \
./osprey/libu/clib/alarm.d \
./osprey/libu/clib/atexit.d \
./osprey/libu/clib/brk.d \
./osprey/libu/clib/chdir.d \
./osprey/libu/clib/chmod.d \
./osprey/libu/clib/chown.d \
./osprey/libu/clib/chroot.d \
./osprey/libu/clib/clibcall.d \
./osprey/libu/clib/close.d \
./osprey/libu/clib/cpselect.d \
./osprey/libu/clib/creat.d \
./osprey/libu/clib/dup.d \
./osprey/libu/clib/exit.d \
./osprey/libu/clib/fclose.d \
./osprey/libu/clib/fcntl.d \
./osprey/libu/clib/fdopen.d \
./osprey/libu/clib/fflush.d \
./osprey/libu/clib/fgets.d \
./osprey/libu/clib/fileno.d \
./osprey/libu/clib/fopen.d \
./osprey/libu/clib/fork.d \
./osprey/libu/clib/fputs.d \
./osprey/libu/clib/fread.d \
./osprey/libu/clib/freopen.d \
./osprey/libu/clib/fseek.d \
./osprey/libu/clib/ftell.d \
./osprey/libu/clib/fwrite.d \
./osprey/libu/clib/getcwd.d \
./osprey/libu/clib/getegid.d \
./osprey/libu/clib/getenv.d \
./osprey/libu/clib/geteuid.d \
./osprey/libu/clib/getgid.d \
./osprey/libu/clib/gethost.d \
./osprey/libu/clib/getopt.d \
./osprey/libu/clib/getpgrp.d \
./osprey/libu/clib/getpid.d \
./osprey/libu/clib/getppid.d \
./osprey/libu/clib/getuid.d \
./osprey/libu/clib/ialloc.d \
./osprey/libu/clib/ioctl.d \
./osprey/libu/clib/kill.d \
./osprey/libu/clib/limit.d \
./osprey/libu/clib/link.d \
./osprey/libu/clib/lseek.d \
./osprey/libu/clib/mknod.d \
./osprey/libu/clib/mktemp.d \
./osprey/libu/clib/newexit.d \
./osprey/libu/clib/newgetpid.d \
./osprey/libu/clib/newgetppid.d \
./osprey/libu/clib/nice.d \
./osprey/libu/clib/nicem.d \
./osprey/libu/clib/nlimit.d \
./osprey/libu/clib/open.d \
./osprey/libu/clib/pause.d \
./osprey/libu/clib/pipe.d \
./osprey/libu/clib/plock.d \
./osprey/libu/clib/ptrace.d \
./osprey/libu/clib/putenv.d \
./osprey/libu/clib/reada.d \
./osprey/libu/clib/rename.d \
./osprey/libu/clib/resume.d \
./osprey/libu/clib/sbreak.d \
./osprey/libu/clib/sbrk.d \
./osprey/libu/clib/setgid.d \
./osprey/libu/clib/setpgrp.d \
./osprey/libu/clib/setuid.d \
./osprey/libu/clib/shutdreg.d \
./osprey/libu/clib/shutdsav.d \
./osprey/libu/clib/sigctl.d \
./osprey/libu/clib/signal.d \
./osprey/libu/clib/sleep.d \
./osprey/libu/clib/stat.d \
./osprey/libu/clib/suspend.d \
./osprey/libu/clib/sync.d \
./osprey/libu/clib/tempnam.d \
./osprey/libu/clib/time.d \
./osprey/libu/clib/times.d \
./osprey/libu/clib/tmpfile.d \
./osprey/libu/clib/trunc.d \
./osprey/libu/clib/ulimit.d \
./osprey/libu/clib/umask.d \
./osprey/libu/clib/uname.d \
./osprey/libu/clib/unlink.d \
./osprey/libu/clib/ustat.d \
./osprey/libu/clib/utime.d \
./osprey/libu/clib/wait.d \
./osprey/libu/clib/writea.d 


# Each subdirectory must supply rules for building sources it contributes
osprey/libu/clib/%.o: ../osprey/libu/clib/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


