################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../testsuite/libgomp.c/atomic-1.c \
../testsuite/libgomp.c/atomic-10.c \
../testsuite/libgomp.c/atomic-2.c \
../testsuite/libgomp.c/atomic-3.c \
../testsuite/libgomp.c/atomic-4.c \
../testsuite/libgomp.c/atomic-5.c \
../testsuite/libgomp.c/atomic-6.c \
../testsuite/libgomp.c/autopar-1.c \
../testsuite/libgomp.c/barrier-1.c \
../testsuite/libgomp.c/collapse-1.c \
../testsuite/libgomp.c/collapse-2.c \
../testsuite/libgomp.c/collapse-3.c \
../testsuite/libgomp.c/copyin-1.c \
../testsuite/libgomp.c/copyin-2.c \
../testsuite/libgomp.c/copyin-3.c \
../testsuite/libgomp.c/critical-1.c \
../testsuite/libgomp.c/critical-2.c \
../testsuite/libgomp.c/debug-1.c \
../testsuite/libgomp.c/icv-1.c \
../testsuite/libgomp.c/icv-2.c \
../testsuite/libgomp.c/lib-1.c \
../testsuite/libgomp.c/lib-2.c \
../testsuite/libgomp.c/lock-1.c \
../testsuite/libgomp.c/lock-2.c \
../testsuite/libgomp.c/lock-3.c \
../testsuite/libgomp.c/loop-1.c \
../testsuite/libgomp.c/loop-10.c \
../testsuite/libgomp.c/loop-11.c \
../testsuite/libgomp.c/loop-12.c \
../testsuite/libgomp.c/loop-2.c \
../testsuite/libgomp.c/loop-3.c \
../testsuite/libgomp.c/loop-4.c \
../testsuite/libgomp.c/loop-5.c \
../testsuite/libgomp.c/loop-6.c \
../testsuite/libgomp.c/loop-7.c \
../testsuite/libgomp.c/loop-8.c \
../testsuite/libgomp.c/loop-9.c \
../testsuite/libgomp.c/nested-1.c \
../testsuite/libgomp.c/nested-2.c \
../testsuite/libgomp.c/nested-3.c \
../testsuite/libgomp.c/nestedfn-1.c \
../testsuite/libgomp.c/nestedfn-2.c \
../testsuite/libgomp.c/nestedfn-3.c \
../testsuite/libgomp.c/nestedfn-4.c \
../testsuite/libgomp.c/nestedfn-5.c \
../testsuite/libgomp.c/nestedfn-6.c \
../testsuite/libgomp.c/nqueens-1.c \
../testsuite/libgomp.c/omp-loop01.c \
../testsuite/libgomp.c/omp-loop02.c \
../testsuite/libgomp.c/omp-loop03.c \
../testsuite/libgomp.c/omp-nested-1.c \
../testsuite/libgomp.c/omp-parallel-for.c \
../testsuite/libgomp.c/omp-parallel-if.c \
../testsuite/libgomp.c/omp-single-1.c \
../testsuite/libgomp.c/omp-single-2.c \
../testsuite/libgomp.c/omp-single-3.c \
../testsuite/libgomp.c/omp_hello.c \
../testsuite/libgomp.c/omp_matvec.c \
../testsuite/libgomp.c/omp_orphan.c \
../testsuite/libgomp.c/omp_reduction.c \
../testsuite/libgomp.c/omp_workshare1.c \
../testsuite/libgomp.c/omp_workshare2.c \
../testsuite/libgomp.c/omp_workshare3.c \
../testsuite/libgomp.c/omp_workshare4.c \
../testsuite/libgomp.c/ordered-1.c \
../testsuite/libgomp.c/ordered-2.c \
../testsuite/libgomp.c/ordered-3.c \
../testsuite/libgomp.c/parallel-1.c \
../testsuite/libgomp.c/pr24455-1.c \
../testsuite/libgomp.c/pr24455.c \
../testsuite/libgomp.c/pr26171.c \
../testsuite/libgomp.c/pr26943-1.c \
../testsuite/libgomp.c/pr26943-2.c \
../testsuite/libgomp.c/pr26943-3.c \
../testsuite/libgomp.c/pr26943-4.c \
../testsuite/libgomp.c/pr29947-1.c \
../testsuite/libgomp.c/pr29947-2.c \
../testsuite/libgomp.c/pr30494.c \
../testsuite/libgomp.c/pr32362-1.c \
../testsuite/libgomp.c/pr32362-2.c \
../testsuite/libgomp.c/pr32362-3.c \
../testsuite/libgomp.c/pr32468.c \
../testsuite/libgomp.c/pr33880.c \
../testsuite/libgomp.c/pr34513.c \
../testsuite/libgomp.c/pr35130.c \
../testsuite/libgomp.c/pr35196.c \
../testsuite/libgomp.c/pr35549.c \
../testsuite/libgomp.c/pr35625.c \
../testsuite/libgomp.c/pr36802-1.c \
../testsuite/libgomp.c/pr36802-2.c \
../testsuite/libgomp.c/pr36802-3.c \
../testsuite/libgomp.c/pr38650.c \
../testsuite/libgomp.c/pr39154.c \
../testsuite/libgomp.c/pr39591-1.c \
../testsuite/libgomp.c/pr39591-2.c \
../testsuite/libgomp.c/pr39591-3.c \
../testsuite/libgomp.c/pr42029.c \
../testsuite/libgomp.c/pr42942.c \
../testsuite/libgomp.c/pr43893.c \
../testsuite/libgomp.c/private-1.c \
../testsuite/libgomp.c/reduction-1.c \
../testsuite/libgomp.c/reduction-2.c \
../testsuite/libgomp.c/reduction-3.c \
../testsuite/libgomp.c/reduction-4.c \
../testsuite/libgomp.c/reduction-5.c \
../testsuite/libgomp.c/sections-1.c \
../testsuite/libgomp.c/shared-1.c \
../testsuite/libgomp.c/shared-2.c \
../testsuite/libgomp.c/shared-3.c \
../testsuite/libgomp.c/single-1.c \
../testsuite/libgomp.c/single-2.c \
../testsuite/libgomp.c/sort-1.c \
../testsuite/libgomp.c/task-1.c \
../testsuite/libgomp.c/task-2.c \
../testsuite/libgomp.c/task-3.c \
../testsuite/libgomp.c/task-4.c \
../testsuite/libgomp.c/vla-1.c 

OBJS += \
./testsuite/libgomp.c/atomic-1.o \
./testsuite/libgomp.c/atomic-10.o \
./testsuite/libgomp.c/atomic-2.o \
./testsuite/libgomp.c/atomic-3.o \
./testsuite/libgomp.c/atomic-4.o \
./testsuite/libgomp.c/atomic-5.o \
./testsuite/libgomp.c/atomic-6.o \
./testsuite/libgomp.c/autopar-1.o \
./testsuite/libgomp.c/barrier-1.o \
./testsuite/libgomp.c/collapse-1.o \
./testsuite/libgomp.c/collapse-2.o \
./testsuite/libgomp.c/collapse-3.o \
./testsuite/libgomp.c/copyin-1.o \
./testsuite/libgomp.c/copyin-2.o \
./testsuite/libgomp.c/copyin-3.o \
./testsuite/libgomp.c/critical-1.o \
./testsuite/libgomp.c/critical-2.o \
./testsuite/libgomp.c/debug-1.o \
./testsuite/libgomp.c/icv-1.o \
./testsuite/libgomp.c/icv-2.o \
./testsuite/libgomp.c/lib-1.o \
./testsuite/libgomp.c/lib-2.o \
./testsuite/libgomp.c/lock-1.o \
./testsuite/libgomp.c/lock-2.o \
./testsuite/libgomp.c/lock-3.o \
./testsuite/libgomp.c/loop-1.o \
./testsuite/libgomp.c/loop-10.o \
./testsuite/libgomp.c/loop-11.o \
./testsuite/libgomp.c/loop-12.o \
./testsuite/libgomp.c/loop-2.o \
./testsuite/libgomp.c/loop-3.o \
./testsuite/libgomp.c/loop-4.o \
./testsuite/libgomp.c/loop-5.o \
./testsuite/libgomp.c/loop-6.o \
./testsuite/libgomp.c/loop-7.o \
./testsuite/libgomp.c/loop-8.o \
./testsuite/libgomp.c/loop-9.o \
./testsuite/libgomp.c/nested-1.o \
./testsuite/libgomp.c/nested-2.o \
./testsuite/libgomp.c/nested-3.o \
./testsuite/libgomp.c/nestedfn-1.o \
./testsuite/libgomp.c/nestedfn-2.o \
./testsuite/libgomp.c/nestedfn-3.o \
./testsuite/libgomp.c/nestedfn-4.o \
./testsuite/libgomp.c/nestedfn-5.o \
./testsuite/libgomp.c/nestedfn-6.o \
./testsuite/libgomp.c/nqueens-1.o \
./testsuite/libgomp.c/omp-loop01.o \
./testsuite/libgomp.c/omp-loop02.o \
./testsuite/libgomp.c/omp-loop03.o \
./testsuite/libgomp.c/omp-nested-1.o \
./testsuite/libgomp.c/omp-parallel-for.o \
./testsuite/libgomp.c/omp-parallel-if.o \
./testsuite/libgomp.c/omp-single-1.o \
./testsuite/libgomp.c/omp-single-2.o \
./testsuite/libgomp.c/omp-single-3.o \
./testsuite/libgomp.c/omp_hello.o \
./testsuite/libgomp.c/omp_matvec.o \
./testsuite/libgomp.c/omp_orphan.o \
./testsuite/libgomp.c/omp_reduction.o \
./testsuite/libgomp.c/omp_workshare1.o \
./testsuite/libgomp.c/omp_workshare2.o \
./testsuite/libgomp.c/omp_workshare3.o \
./testsuite/libgomp.c/omp_workshare4.o \
./testsuite/libgomp.c/ordered-1.o \
./testsuite/libgomp.c/ordered-2.o \
./testsuite/libgomp.c/ordered-3.o \
./testsuite/libgomp.c/parallel-1.o \
./testsuite/libgomp.c/pr24455-1.o \
./testsuite/libgomp.c/pr24455.o \
./testsuite/libgomp.c/pr26171.o \
./testsuite/libgomp.c/pr26943-1.o \
./testsuite/libgomp.c/pr26943-2.o \
./testsuite/libgomp.c/pr26943-3.o \
./testsuite/libgomp.c/pr26943-4.o \
./testsuite/libgomp.c/pr29947-1.o \
./testsuite/libgomp.c/pr29947-2.o \
./testsuite/libgomp.c/pr30494.o \
./testsuite/libgomp.c/pr32362-1.o \
./testsuite/libgomp.c/pr32362-2.o \
./testsuite/libgomp.c/pr32362-3.o \
./testsuite/libgomp.c/pr32468.o \
./testsuite/libgomp.c/pr33880.o \
./testsuite/libgomp.c/pr34513.o \
./testsuite/libgomp.c/pr35130.o \
./testsuite/libgomp.c/pr35196.o \
./testsuite/libgomp.c/pr35549.o \
./testsuite/libgomp.c/pr35625.o \
./testsuite/libgomp.c/pr36802-1.o \
./testsuite/libgomp.c/pr36802-2.o \
./testsuite/libgomp.c/pr36802-3.o \
./testsuite/libgomp.c/pr38650.o \
./testsuite/libgomp.c/pr39154.o \
./testsuite/libgomp.c/pr39591-1.o \
./testsuite/libgomp.c/pr39591-2.o \
./testsuite/libgomp.c/pr39591-3.o \
./testsuite/libgomp.c/pr42029.o \
./testsuite/libgomp.c/pr42942.o \
./testsuite/libgomp.c/pr43893.o \
./testsuite/libgomp.c/private-1.o \
./testsuite/libgomp.c/reduction-1.o \
./testsuite/libgomp.c/reduction-2.o \
./testsuite/libgomp.c/reduction-3.o \
./testsuite/libgomp.c/reduction-4.o \
./testsuite/libgomp.c/reduction-5.o \
./testsuite/libgomp.c/sections-1.o \
./testsuite/libgomp.c/shared-1.o \
./testsuite/libgomp.c/shared-2.o \
./testsuite/libgomp.c/shared-3.o \
./testsuite/libgomp.c/single-1.o \
./testsuite/libgomp.c/single-2.o \
./testsuite/libgomp.c/sort-1.o \
./testsuite/libgomp.c/task-1.o \
./testsuite/libgomp.c/task-2.o \
./testsuite/libgomp.c/task-3.o \
./testsuite/libgomp.c/task-4.o \
./testsuite/libgomp.c/vla-1.o 

C_DEPS += \
./testsuite/libgomp.c/atomic-1.d \
./testsuite/libgomp.c/atomic-10.d \
./testsuite/libgomp.c/atomic-2.d \
./testsuite/libgomp.c/atomic-3.d \
./testsuite/libgomp.c/atomic-4.d \
./testsuite/libgomp.c/atomic-5.d \
./testsuite/libgomp.c/atomic-6.d \
./testsuite/libgomp.c/autopar-1.d \
./testsuite/libgomp.c/barrier-1.d \
./testsuite/libgomp.c/collapse-1.d \
./testsuite/libgomp.c/collapse-2.d \
./testsuite/libgomp.c/collapse-3.d \
./testsuite/libgomp.c/copyin-1.d \
./testsuite/libgomp.c/copyin-2.d \
./testsuite/libgomp.c/copyin-3.d \
./testsuite/libgomp.c/critical-1.d \
./testsuite/libgomp.c/critical-2.d \
./testsuite/libgomp.c/debug-1.d \
./testsuite/libgomp.c/icv-1.d \
./testsuite/libgomp.c/icv-2.d \
./testsuite/libgomp.c/lib-1.d \
./testsuite/libgomp.c/lib-2.d \
./testsuite/libgomp.c/lock-1.d \
./testsuite/libgomp.c/lock-2.d \
./testsuite/libgomp.c/lock-3.d \
./testsuite/libgomp.c/loop-1.d \
./testsuite/libgomp.c/loop-10.d \
./testsuite/libgomp.c/loop-11.d \
./testsuite/libgomp.c/loop-12.d \
./testsuite/libgomp.c/loop-2.d \
./testsuite/libgomp.c/loop-3.d \
./testsuite/libgomp.c/loop-4.d \
./testsuite/libgomp.c/loop-5.d \
./testsuite/libgomp.c/loop-6.d \
./testsuite/libgomp.c/loop-7.d \
./testsuite/libgomp.c/loop-8.d \
./testsuite/libgomp.c/loop-9.d \
./testsuite/libgomp.c/nested-1.d \
./testsuite/libgomp.c/nested-2.d \
./testsuite/libgomp.c/nested-3.d \
./testsuite/libgomp.c/nestedfn-1.d \
./testsuite/libgomp.c/nestedfn-2.d \
./testsuite/libgomp.c/nestedfn-3.d \
./testsuite/libgomp.c/nestedfn-4.d \
./testsuite/libgomp.c/nestedfn-5.d \
./testsuite/libgomp.c/nestedfn-6.d \
./testsuite/libgomp.c/nqueens-1.d \
./testsuite/libgomp.c/omp-loop01.d \
./testsuite/libgomp.c/omp-loop02.d \
./testsuite/libgomp.c/omp-loop03.d \
./testsuite/libgomp.c/omp-nested-1.d \
./testsuite/libgomp.c/omp-parallel-for.d \
./testsuite/libgomp.c/omp-parallel-if.d \
./testsuite/libgomp.c/omp-single-1.d \
./testsuite/libgomp.c/omp-single-2.d \
./testsuite/libgomp.c/omp-single-3.d \
./testsuite/libgomp.c/omp_hello.d \
./testsuite/libgomp.c/omp_matvec.d \
./testsuite/libgomp.c/omp_orphan.d \
./testsuite/libgomp.c/omp_reduction.d \
./testsuite/libgomp.c/omp_workshare1.d \
./testsuite/libgomp.c/omp_workshare2.d \
./testsuite/libgomp.c/omp_workshare3.d \
./testsuite/libgomp.c/omp_workshare4.d \
./testsuite/libgomp.c/ordered-1.d \
./testsuite/libgomp.c/ordered-2.d \
./testsuite/libgomp.c/ordered-3.d \
./testsuite/libgomp.c/parallel-1.d \
./testsuite/libgomp.c/pr24455-1.d \
./testsuite/libgomp.c/pr24455.d \
./testsuite/libgomp.c/pr26171.d \
./testsuite/libgomp.c/pr26943-1.d \
./testsuite/libgomp.c/pr26943-2.d \
./testsuite/libgomp.c/pr26943-3.d \
./testsuite/libgomp.c/pr26943-4.d \
./testsuite/libgomp.c/pr29947-1.d \
./testsuite/libgomp.c/pr29947-2.d \
./testsuite/libgomp.c/pr30494.d \
./testsuite/libgomp.c/pr32362-1.d \
./testsuite/libgomp.c/pr32362-2.d \
./testsuite/libgomp.c/pr32362-3.d \
./testsuite/libgomp.c/pr32468.d \
./testsuite/libgomp.c/pr33880.d \
./testsuite/libgomp.c/pr34513.d \
./testsuite/libgomp.c/pr35130.d \
./testsuite/libgomp.c/pr35196.d \
./testsuite/libgomp.c/pr35549.d \
./testsuite/libgomp.c/pr35625.d \
./testsuite/libgomp.c/pr36802-1.d \
./testsuite/libgomp.c/pr36802-2.d \
./testsuite/libgomp.c/pr36802-3.d \
./testsuite/libgomp.c/pr38650.d \
./testsuite/libgomp.c/pr39154.d \
./testsuite/libgomp.c/pr39591-1.d \
./testsuite/libgomp.c/pr39591-2.d \
./testsuite/libgomp.c/pr39591-3.d \
./testsuite/libgomp.c/pr42029.d \
./testsuite/libgomp.c/pr42942.d \
./testsuite/libgomp.c/pr43893.d \
./testsuite/libgomp.c/private-1.d \
./testsuite/libgomp.c/reduction-1.d \
./testsuite/libgomp.c/reduction-2.d \
./testsuite/libgomp.c/reduction-3.d \
./testsuite/libgomp.c/reduction-4.d \
./testsuite/libgomp.c/reduction-5.d \
./testsuite/libgomp.c/sections-1.d \
./testsuite/libgomp.c/shared-1.d \
./testsuite/libgomp.c/shared-2.d \
./testsuite/libgomp.c/shared-3.d \
./testsuite/libgomp.c/single-1.d \
./testsuite/libgomp.c/single-2.d \
./testsuite/libgomp.c/sort-1.d \
./testsuite/libgomp.c/task-1.d \
./testsuite/libgomp.c/task-2.d \
./testsuite/libgomp.c/task-3.d \
./testsuite/libgomp.c/task-4.d \
./testsuite/libgomp.c/vla-1.d 


# Each subdirectory must supply rules for building sources it contributes
testsuite/libgomp.c/%.o: ../testsuite/libgomp.c/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


