################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../osprey/cygnus/bfd/aout32.o \
../osprey/cygnus/bfd/archive.o \
../osprey/cygnus/bfd/archive64.o \
../osprey/cygnus/bfd/archures.o \
../osprey/cygnus/bfd/bfd.o \
../osprey/cygnus/bfd/bfdio.o \
../osprey/cygnus/bfd/bfdwin.o \
../osprey/cygnus/bfd/binary.o \
../osprey/cygnus/bfd/cache.o \
../osprey/cygnus/bfd/coffgen.o \
../osprey/cygnus/bfd/cofflink.o \
../osprey/cygnus/bfd/corefile.o \
../osprey/cygnus/bfd/cpu-i386.o \
../osprey/cygnus/bfd/dwarf1.o \
../osprey/cygnus/bfd/dwarf2.o \
../osprey/cygnus/bfd/efi-app-ia32.o \
../osprey/cygnus/bfd/elf-eh-frame.o \
../osprey/cygnus/bfd/elf-strtab.o \
../osprey/cygnus/bfd/elf.o \
../osprey/cygnus/bfd/elf32-gen.o \
../osprey/cygnus/bfd/elf32-i386.o \
../osprey/cygnus/bfd/elf32.o \
../osprey/cygnus/bfd/elf64-gen.o \
../osprey/cygnus/bfd/elf64-x86-64.o \
../osprey/cygnus/bfd/elf64.o \
../osprey/cygnus/bfd/elflink.o \
../osprey/cygnus/bfd/format.o \
../osprey/cygnus/bfd/hash.o \
../osprey/cygnus/bfd/i386linux.o \
../osprey/cygnus/bfd/ihex.o \
../osprey/cygnus/bfd/init.o \
../osprey/cygnus/bfd/ipa_cmdline.o \
../osprey/cygnus/bfd/ipa_ld.o \
../osprey/cygnus/bfd/libbfd.o \
../osprey/cygnus/bfd/linker.o \
../osprey/cygnus/bfd/merge.o \
../osprey/cygnus/bfd/opncls.o \
../osprey/cygnus/bfd/peigen.o \
../osprey/cygnus/bfd/reloc.o \
../osprey/cygnus/bfd/section.o \
../osprey/cygnus/bfd/simple.o \
../osprey/cygnus/bfd/srec.o \
../osprey/cygnus/bfd/stab-syms.o \
../osprey/cygnus/bfd/stabs.o \
../osprey/cygnus/bfd/syms.o \
../osprey/cygnus/bfd/targets.o \
../osprey/cygnus/bfd/tekhex.o 

C_SRCS += \
../osprey/cygnus/bfd/aix386-core.c \
../osprey/cygnus/bfd/aix5ppc-core.c \
../osprey/cygnus/bfd/aout-adobe.c \
../osprey/cygnus/bfd/aout-arm.c \
../osprey/cygnus/bfd/aout-cris.c \
../osprey/cygnus/bfd/aout-encap.c \
../osprey/cygnus/bfd/aout-ns32k.c \
../osprey/cygnus/bfd/aout-sparcle.c \
../osprey/cygnus/bfd/aout-tic30.c \
../osprey/cygnus/bfd/aout0.c \
../osprey/cygnus/bfd/aout32.c \
../osprey/cygnus/bfd/aout64.c \
../osprey/cygnus/bfd/archive.c \
../osprey/cygnus/bfd/archive64.c \
../osprey/cygnus/bfd/archures.c \
../osprey/cygnus/bfd/armnetbsd.c \
../osprey/cygnus/bfd/bfd.c \
../osprey/cygnus/bfd/bfdio.c \
../osprey/cygnus/bfd/bfdwin.c \
../osprey/cygnus/bfd/binary.c \
../osprey/cygnus/bfd/bout.c \
../osprey/cygnus/bfd/cache.c \
../osprey/cygnus/bfd/cf-i386lynx.c \
../osprey/cygnus/bfd/cf-m68klynx.c \
../osprey/cygnus/bfd/cf-sparclynx.c \
../osprey/cygnus/bfd/cisco-core.c \
../osprey/cygnus/bfd/coff-a29k.c \
../osprey/cygnus/bfd/coff-alpha.c \
../osprey/cygnus/bfd/coff-apollo.c \
../osprey/cygnus/bfd/coff-arm.c \
../osprey/cygnus/bfd/coff-aux.c \
../osprey/cygnus/bfd/coff-go32.c \
../osprey/cygnus/bfd/coff-h8300.c \
../osprey/cygnus/bfd/coff-h8500.c \
../osprey/cygnus/bfd/coff-i386.c \
../osprey/cygnus/bfd/coff-i860.c \
../osprey/cygnus/bfd/coff-i960.c \
../osprey/cygnus/bfd/coff-ia64.c \
../osprey/cygnus/bfd/coff-m68k.c \
../osprey/cygnus/bfd/coff-m88k.c \
../osprey/cygnus/bfd/coff-mcore.c \
../osprey/cygnus/bfd/coff-mips.c \
../osprey/cygnus/bfd/coff-or32.c \
../osprey/cygnus/bfd/coff-pmac.c \
../osprey/cygnus/bfd/coff-ppc.c \
../osprey/cygnus/bfd/coff-rs6000.c \
../osprey/cygnus/bfd/coff-sh.c \
../osprey/cygnus/bfd/coff-sparc.c \
../osprey/cygnus/bfd/coff-stgo32.c \
../osprey/cygnus/bfd/coff-svm68k.c \
../osprey/cygnus/bfd/coff-tic30.c \
../osprey/cygnus/bfd/coff-tic4x.c \
../osprey/cygnus/bfd/coff-tic54x.c \
../osprey/cygnus/bfd/coff-tic80.c \
../osprey/cygnus/bfd/coff-u68k.c \
../osprey/cygnus/bfd/coff-w65.c \
../osprey/cygnus/bfd/coff-we32k.c \
../osprey/cygnus/bfd/coff-z8k.c \
../osprey/cygnus/bfd/coff64-rs6000.c \
../osprey/cygnus/bfd/coffgen.c \
../osprey/cygnus/bfd/cofflink.c \
../osprey/cygnus/bfd/corefile.c \
../osprey/cygnus/bfd/cpu-a29k.c \
../osprey/cygnus/bfd/cpu-alpha.c \
../osprey/cygnus/bfd/cpu-arc.c \
../osprey/cygnus/bfd/cpu-arm.c \
../osprey/cygnus/bfd/cpu-avr.c \
../osprey/cygnus/bfd/cpu-cris.c \
../osprey/cygnus/bfd/cpu-d10v.c \
../osprey/cygnus/bfd/cpu-d30v.c \
../osprey/cygnus/bfd/cpu-dlx.c \
../osprey/cygnus/bfd/cpu-fr30.c \
../osprey/cygnus/bfd/cpu-frv.c \
../osprey/cygnus/bfd/cpu-h8300.c \
../osprey/cygnus/bfd/cpu-h8500.c \
../osprey/cygnus/bfd/cpu-hppa.c \
../osprey/cygnus/bfd/cpu-i370.c \
../osprey/cygnus/bfd/cpu-i386.c \
../osprey/cygnus/bfd/cpu-i860.c \
../osprey/cygnus/bfd/cpu-i960.c \
../osprey/cygnus/bfd/cpu-ia64-opc.c \
../osprey/cygnus/bfd/cpu-ia64.c \
../osprey/cygnus/bfd/cpu-ip2k.c \
../osprey/cygnus/bfd/cpu-iq2000.c \
../osprey/cygnus/bfd/cpu-m10200.c \
../osprey/cygnus/bfd/cpu-m10300.c \
../osprey/cygnus/bfd/cpu-m32r.c \
../osprey/cygnus/bfd/cpu-m68hc11.c \
../osprey/cygnus/bfd/cpu-m68hc12.c \
../osprey/cygnus/bfd/cpu-m68k.c \
../osprey/cygnus/bfd/cpu-m88k.c \
../osprey/cygnus/bfd/cpu-mcore.c \
../osprey/cygnus/bfd/cpu-mips.c \
../osprey/cygnus/bfd/cpu-mmix.c \
../osprey/cygnus/bfd/cpu-msp430.c \
../osprey/cygnus/bfd/cpu-ns32k.c \
../osprey/cygnus/bfd/cpu-openrisc.c \
../osprey/cygnus/bfd/cpu-or32.c \
../osprey/cygnus/bfd/cpu-pdp11.c \
../osprey/cygnus/bfd/cpu-pj.c \
../osprey/cygnus/bfd/cpu-powerpc.c \
../osprey/cygnus/bfd/cpu-rs6000.c \
../osprey/cygnus/bfd/cpu-s390.c \
../osprey/cygnus/bfd/cpu-sh.c \
../osprey/cygnus/bfd/cpu-sparc.c \
../osprey/cygnus/bfd/cpu-tic30.c \
../osprey/cygnus/bfd/cpu-tic4x.c \
../osprey/cygnus/bfd/cpu-tic54x.c \
../osprey/cygnus/bfd/cpu-tic80.c \
../osprey/cygnus/bfd/cpu-v850.c \
../osprey/cygnus/bfd/cpu-vax.c \
../osprey/cygnus/bfd/cpu-w65.c \
../osprey/cygnus/bfd/cpu-we32k.c \
../osprey/cygnus/bfd/cpu-xstormy16.c \
../osprey/cygnus/bfd/cpu-xtensa.c \
../osprey/cygnus/bfd/cpu-z8k.c \
../osprey/cygnus/bfd/demo64.c \
../osprey/cygnus/bfd/dwarf1.c \
../osprey/cygnus/bfd/dwarf2.c \
../osprey/cygnus/bfd/ecoff.c \
../osprey/cygnus/bfd/ecofflink.c \
../osprey/cygnus/bfd/efi-app-ia32.c \
../osprey/cygnus/bfd/efi-app-ia64.c \
../osprey/cygnus/bfd/elf-eh-frame.c \
../osprey/cygnus/bfd/elf-m10200.c \
../osprey/cygnus/bfd/elf-m10300.c \
../osprey/cygnus/bfd/elf-strtab.c \
../osprey/cygnus/bfd/elf.c \
../osprey/cygnus/bfd/elf32-am33lin.c \
../osprey/cygnus/bfd/elf32-arc.c \
../osprey/cygnus/bfd/elf32-avr.c \
../osprey/cygnus/bfd/elf32-cris.c \
../osprey/cygnus/bfd/elf32-d10v.c \
../osprey/cygnus/bfd/elf32-d30v.c \
../osprey/cygnus/bfd/elf32-dlx.c \
../osprey/cygnus/bfd/elf32-fr30.c \
../osprey/cygnus/bfd/elf32-frv.c \
../osprey/cygnus/bfd/elf32-gen.c \
../osprey/cygnus/bfd/elf32-h8300.c \
../osprey/cygnus/bfd/elf32-hppa.c \
../osprey/cygnus/bfd/elf32-i370.c \
../osprey/cygnus/bfd/elf32-i386.c \
../osprey/cygnus/bfd/elf32-i860.c \
../osprey/cygnus/bfd/elf32-i960.c \
../osprey/cygnus/bfd/elf32-ip2k.c \
../osprey/cygnus/bfd/elf32-iq2000.c \
../osprey/cygnus/bfd/elf32-m32r.c \
../osprey/cygnus/bfd/elf32-m68hc11.c \
../osprey/cygnus/bfd/elf32-m68hc12.c \
../osprey/cygnus/bfd/elf32-m68hc1x.c \
../osprey/cygnus/bfd/elf32-m68k.c \
../osprey/cygnus/bfd/elf32-m88k.c \
../osprey/cygnus/bfd/elf32-mcore.c \
../osprey/cygnus/bfd/elf32-mips.c \
../osprey/cygnus/bfd/elf32-msp430.c \
../osprey/cygnus/bfd/elf32-openrisc.c \
../osprey/cygnus/bfd/elf32-or32.c \
../osprey/cygnus/bfd/elf32-pj.c \
../osprey/cygnus/bfd/elf32-ppc.c \
../osprey/cygnus/bfd/elf32-s390.c \
../osprey/cygnus/bfd/elf32-sh.c \
../osprey/cygnus/bfd/elf32-sh64-com.c \
../osprey/cygnus/bfd/elf32-sh64.c \
../osprey/cygnus/bfd/elf32-sparc.c \
../osprey/cygnus/bfd/elf32-v850.c \
../osprey/cygnus/bfd/elf32-vax.c \
../osprey/cygnus/bfd/elf32-xstormy16.c \
../osprey/cygnus/bfd/elf32-xtensa.c \
../osprey/cygnus/bfd/elf32.c \
../osprey/cygnus/bfd/elf64-alpha.c \
../osprey/cygnus/bfd/elf64-gen.c \
../osprey/cygnus/bfd/elf64-hppa.c \
../osprey/cygnus/bfd/elf64-mips.c \
../osprey/cygnus/bfd/elf64-mmix.c \
../osprey/cygnus/bfd/elf64-ppc.c \
../osprey/cygnus/bfd/elf64-s390.c \
../osprey/cygnus/bfd/elf64-sh64.c \
../osprey/cygnus/bfd/elf64-sparc.c \
../osprey/cygnus/bfd/elf64-x86-64.c \
../osprey/cygnus/bfd/elf64.c \
../osprey/cygnus/bfd/elfarm-nabi.c \
../osprey/cygnus/bfd/elfarm-oabi.c \
../osprey/cygnus/bfd/elflink.c \
../osprey/cygnus/bfd/elfn32-mips.c \
../osprey/cygnus/bfd/elfxx-ia64.c \
../osprey/cygnus/bfd/elfxx-mips.c \
../osprey/cygnus/bfd/epoc-pe-arm.c \
../osprey/cygnus/bfd/epoc-pei-arm.c \
../osprey/cygnus/bfd/format.c \
../osprey/cygnus/bfd/gen-aout.c \
../osprey/cygnus/bfd/hash.c \
../osprey/cygnus/bfd/host-aout.c \
../osprey/cygnus/bfd/hp300bsd.c \
../osprey/cygnus/bfd/hp300hpux.c \
../osprey/cygnus/bfd/hppabsd-core.c \
../osprey/cygnus/bfd/hpux-core.c \
../osprey/cygnus/bfd/i386aout.c \
../osprey/cygnus/bfd/i386bsd.c \
../osprey/cygnus/bfd/i386dynix.c \
../osprey/cygnus/bfd/i386freebsd.c \
../osprey/cygnus/bfd/i386linux.c \
../osprey/cygnus/bfd/i386lynx.c \
../osprey/cygnus/bfd/i386mach3.c \
../osprey/cygnus/bfd/i386msdos.c \
../osprey/cygnus/bfd/i386netbsd.c \
../osprey/cygnus/bfd/i386os9k.c \
../osprey/cygnus/bfd/ieee.c \
../osprey/cygnus/bfd/ihex.c \
../osprey/cygnus/bfd/init.c \
../osprey/cygnus/bfd/ipa_cmdline.c \
../osprey/cygnus/bfd/ipa_ld.c \
../osprey/cygnus/bfd/irix-core.c \
../osprey/cygnus/bfd/libbfd.c \
../osprey/cygnus/bfd/linker.c \
../osprey/cygnus/bfd/lynx-core.c \
../osprey/cygnus/bfd/m68k4knetbsd.c \
../osprey/cygnus/bfd/m68klinux.c \
../osprey/cygnus/bfd/m68klynx.c \
../osprey/cygnus/bfd/m68knetbsd.c \
../osprey/cygnus/bfd/m88kmach3.c \
../osprey/cygnus/bfd/mach-o-target.c \
../osprey/cygnus/bfd/mach-o.c \
../osprey/cygnus/bfd/merge.c \
../osprey/cygnus/bfd/mipsbsd.c \
../osprey/cygnus/bfd/mmo.c \
../osprey/cygnus/bfd/netbsd-core.c \
../osprey/cygnus/bfd/newsos3.c \
../osprey/cygnus/bfd/nlm.c \
../osprey/cygnus/bfd/nlm32-alpha.c \
../osprey/cygnus/bfd/nlm32-i386.c \
../osprey/cygnus/bfd/nlm32-ppc.c \
../osprey/cygnus/bfd/nlm32-sparc.c \
../osprey/cygnus/bfd/nlm32.c \
../osprey/cygnus/bfd/nlm64.c \
../osprey/cygnus/bfd/ns32knetbsd.c \
../osprey/cygnus/bfd/oasys.c \
../osprey/cygnus/bfd/opncls.c \
../osprey/cygnus/bfd/osf-core.c \
../osprey/cygnus/bfd/pc532-mach.c \
../osprey/cygnus/bfd/pdp11.c \
../osprey/cygnus/bfd/pe-arm.c \
../osprey/cygnus/bfd/pe-i386.c \
../osprey/cygnus/bfd/pe-mcore.c \
../osprey/cygnus/bfd/pe-mips.c \
../osprey/cygnus/bfd/pe-ppc.c \
../osprey/cygnus/bfd/pe-sh.c \
../osprey/cygnus/bfd/peXXigen.c \
../osprey/cygnus/bfd/pef.c \
../osprey/cygnus/bfd/pei-arm.c \
../osprey/cygnus/bfd/pei-i386.c \
../osprey/cygnus/bfd/pei-mcore.c \
../osprey/cygnus/bfd/pei-mips.c \
../osprey/cygnus/bfd/pei-ppc.c \
../osprey/cygnus/bfd/pei-sh.c \
../osprey/cygnus/bfd/peigen.c \
../osprey/cygnus/bfd/ppcboot.c \
../osprey/cygnus/bfd/ptrace-core.c \
../osprey/cygnus/bfd/reloc.c \
../osprey/cygnus/bfd/reloc16.c \
../osprey/cygnus/bfd/riscix.c \
../osprey/cygnus/bfd/rs6000-core.c \
../osprey/cygnus/bfd/sco5-core.c \
../osprey/cygnus/bfd/section.c \
../osprey/cygnus/bfd/simple.c \
../osprey/cygnus/bfd/som.c \
../osprey/cygnus/bfd/sparclinux.c \
../osprey/cygnus/bfd/sparclynx.c \
../osprey/cygnus/bfd/sparcnetbsd.c \
../osprey/cygnus/bfd/srec.c \
../osprey/cygnus/bfd/stab-syms.c \
../osprey/cygnus/bfd/stabs.c \
../osprey/cygnus/bfd/sunos.c \
../osprey/cygnus/bfd/syms.c \
../osprey/cygnus/bfd/targets.c \
../osprey/cygnus/bfd/tekhex.c \
../osprey/cygnus/bfd/trad-core.c \
../osprey/cygnus/bfd/vax1knetbsd.c \
../osprey/cygnus/bfd/vaxbsd.c \
../osprey/cygnus/bfd/vaxnetbsd.c \
../osprey/cygnus/bfd/versados.c \
../osprey/cygnus/bfd/vms-gsd.c \
../osprey/cygnus/bfd/vms-hdr.c \
../osprey/cygnus/bfd/vms-misc.c \
../osprey/cygnus/bfd/vms-tir.c \
../osprey/cygnus/bfd/vms.c \
../osprey/cygnus/bfd/xcofflink.c \
../osprey/cygnus/bfd/xsym.c \
../osprey/cygnus/bfd/xtensa-isa.c \
../osprey/cygnus/bfd/xtensa-modules.c 

OBJS += \
./osprey/cygnus/bfd/aix386-core.o \
./osprey/cygnus/bfd/aix5ppc-core.o \
./osprey/cygnus/bfd/aout-adobe.o \
./osprey/cygnus/bfd/aout-arm.o \
./osprey/cygnus/bfd/aout-cris.o \
./osprey/cygnus/bfd/aout-encap.o \
./osprey/cygnus/bfd/aout-ns32k.o \
./osprey/cygnus/bfd/aout-sparcle.o \
./osprey/cygnus/bfd/aout-tic30.o \
./osprey/cygnus/bfd/aout0.o \
./osprey/cygnus/bfd/aout32.o \
./osprey/cygnus/bfd/aout64.o \
./osprey/cygnus/bfd/archive.o \
./osprey/cygnus/bfd/archive64.o \
./osprey/cygnus/bfd/archures.o \
./osprey/cygnus/bfd/armnetbsd.o \
./osprey/cygnus/bfd/bfd.o \
./osprey/cygnus/bfd/bfdio.o \
./osprey/cygnus/bfd/bfdwin.o \
./osprey/cygnus/bfd/binary.o \
./osprey/cygnus/bfd/bout.o \
./osprey/cygnus/bfd/cache.o \
./osprey/cygnus/bfd/cf-i386lynx.o \
./osprey/cygnus/bfd/cf-m68klynx.o \
./osprey/cygnus/bfd/cf-sparclynx.o \
./osprey/cygnus/bfd/cisco-core.o \
./osprey/cygnus/bfd/coff-a29k.o \
./osprey/cygnus/bfd/coff-alpha.o \
./osprey/cygnus/bfd/coff-apollo.o \
./osprey/cygnus/bfd/coff-arm.o \
./osprey/cygnus/bfd/coff-aux.o \
./osprey/cygnus/bfd/coff-go32.o \
./osprey/cygnus/bfd/coff-h8300.o \
./osprey/cygnus/bfd/coff-h8500.o \
./osprey/cygnus/bfd/coff-i386.o \
./osprey/cygnus/bfd/coff-i860.o \
./osprey/cygnus/bfd/coff-i960.o \
./osprey/cygnus/bfd/coff-ia64.o \
./osprey/cygnus/bfd/coff-m68k.o \
./osprey/cygnus/bfd/coff-m88k.o \
./osprey/cygnus/bfd/coff-mcore.o \
./osprey/cygnus/bfd/coff-mips.o \
./osprey/cygnus/bfd/coff-or32.o \
./osprey/cygnus/bfd/coff-pmac.o \
./osprey/cygnus/bfd/coff-ppc.o \
./osprey/cygnus/bfd/coff-rs6000.o \
./osprey/cygnus/bfd/coff-sh.o \
./osprey/cygnus/bfd/coff-sparc.o \
./osprey/cygnus/bfd/coff-stgo32.o \
./osprey/cygnus/bfd/coff-svm68k.o \
./osprey/cygnus/bfd/coff-tic30.o \
./osprey/cygnus/bfd/coff-tic4x.o \
./osprey/cygnus/bfd/coff-tic54x.o \
./osprey/cygnus/bfd/coff-tic80.o \
./osprey/cygnus/bfd/coff-u68k.o \
./osprey/cygnus/bfd/coff-w65.o \
./osprey/cygnus/bfd/coff-we32k.o \
./osprey/cygnus/bfd/coff-z8k.o \
./osprey/cygnus/bfd/coff64-rs6000.o \
./osprey/cygnus/bfd/coffgen.o \
./osprey/cygnus/bfd/cofflink.o \
./osprey/cygnus/bfd/corefile.o \
./osprey/cygnus/bfd/cpu-a29k.o \
./osprey/cygnus/bfd/cpu-alpha.o \
./osprey/cygnus/bfd/cpu-arc.o \
./osprey/cygnus/bfd/cpu-arm.o \
./osprey/cygnus/bfd/cpu-avr.o \
./osprey/cygnus/bfd/cpu-cris.o \
./osprey/cygnus/bfd/cpu-d10v.o \
./osprey/cygnus/bfd/cpu-d30v.o \
./osprey/cygnus/bfd/cpu-dlx.o \
./osprey/cygnus/bfd/cpu-fr30.o \
./osprey/cygnus/bfd/cpu-frv.o \
./osprey/cygnus/bfd/cpu-h8300.o \
./osprey/cygnus/bfd/cpu-h8500.o \
./osprey/cygnus/bfd/cpu-hppa.o \
./osprey/cygnus/bfd/cpu-i370.o \
./osprey/cygnus/bfd/cpu-i386.o \
./osprey/cygnus/bfd/cpu-i860.o \
./osprey/cygnus/bfd/cpu-i960.o \
./osprey/cygnus/bfd/cpu-ia64-opc.o \
./osprey/cygnus/bfd/cpu-ia64.o \
./osprey/cygnus/bfd/cpu-ip2k.o \
./osprey/cygnus/bfd/cpu-iq2000.o \
./osprey/cygnus/bfd/cpu-m10200.o \
./osprey/cygnus/bfd/cpu-m10300.o \
./osprey/cygnus/bfd/cpu-m32r.o \
./osprey/cygnus/bfd/cpu-m68hc11.o \
./osprey/cygnus/bfd/cpu-m68hc12.o \
./osprey/cygnus/bfd/cpu-m68k.o \
./osprey/cygnus/bfd/cpu-m88k.o \
./osprey/cygnus/bfd/cpu-mcore.o \
./osprey/cygnus/bfd/cpu-mips.o \
./osprey/cygnus/bfd/cpu-mmix.o \
./osprey/cygnus/bfd/cpu-msp430.o \
./osprey/cygnus/bfd/cpu-ns32k.o \
./osprey/cygnus/bfd/cpu-openrisc.o \
./osprey/cygnus/bfd/cpu-or32.o \
./osprey/cygnus/bfd/cpu-pdp11.o \
./osprey/cygnus/bfd/cpu-pj.o \
./osprey/cygnus/bfd/cpu-powerpc.o \
./osprey/cygnus/bfd/cpu-rs6000.o \
./osprey/cygnus/bfd/cpu-s390.o \
./osprey/cygnus/bfd/cpu-sh.o \
./osprey/cygnus/bfd/cpu-sparc.o \
./osprey/cygnus/bfd/cpu-tic30.o \
./osprey/cygnus/bfd/cpu-tic4x.o \
./osprey/cygnus/bfd/cpu-tic54x.o \
./osprey/cygnus/bfd/cpu-tic80.o \
./osprey/cygnus/bfd/cpu-v850.o \
./osprey/cygnus/bfd/cpu-vax.o \
./osprey/cygnus/bfd/cpu-w65.o \
./osprey/cygnus/bfd/cpu-we32k.o \
./osprey/cygnus/bfd/cpu-xstormy16.o \
./osprey/cygnus/bfd/cpu-xtensa.o \
./osprey/cygnus/bfd/cpu-z8k.o \
./osprey/cygnus/bfd/demo64.o \
./osprey/cygnus/bfd/dwarf1.o \
./osprey/cygnus/bfd/dwarf2.o \
./osprey/cygnus/bfd/ecoff.o \
./osprey/cygnus/bfd/ecofflink.o \
./osprey/cygnus/bfd/efi-app-ia32.o \
./osprey/cygnus/bfd/efi-app-ia64.o \
./osprey/cygnus/bfd/elf-eh-frame.o \
./osprey/cygnus/bfd/elf-m10200.o \
./osprey/cygnus/bfd/elf-m10300.o \
./osprey/cygnus/bfd/elf-strtab.o \
./osprey/cygnus/bfd/elf.o \
./osprey/cygnus/bfd/elf32-am33lin.o \
./osprey/cygnus/bfd/elf32-arc.o \
./osprey/cygnus/bfd/elf32-avr.o \
./osprey/cygnus/bfd/elf32-cris.o \
./osprey/cygnus/bfd/elf32-d10v.o \
./osprey/cygnus/bfd/elf32-d30v.o \
./osprey/cygnus/bfd/elf32-dlx.o \
./osprey/cygnus/bfd/elf32-fr30.o \
./osprey/cygnus/bfd/elf32-frv.o \
./osprey/cygnus/bfd/elf32-gen.o \
./osprey/cygnus/bfd/elf32-h8300.o \
./osprey/cygnus/bfd/elf32-hppa.o \
./osprey/cygnus/bfd/elf32-i370.o \
./osprey/cygnus/bfd/elf32-i386.o \
./osprey/cygnus/bfd/elf32-i860.o \
./osprey/cygnus/bfd/elf32-i960.o \
./osprey/cygnus/bfd/elf32-ip2k.o \
./osprey/cygnus/bfd/elf32-iq2000.o \
./osprey/cygnus/bfd/elf32-m32r.o \
./osprey/cygnus/bfd/elf32-m68hc11.o \
./osprey/cygnus/bfd/elf32-m68hc12.o \
./osprey/cygnus/bfd/elf32-m68hc1x.o \
./osprey/cygnus/bfd/elf32-m68k.o \
./osprey/cygnus/bfd/elf32-m88k.o \
./osprey/cygnus/bfd/elf32-mcore.o \
./osprey/cygnus/bfd/elf32-mips.o \
./osprey/cygnus/bfd/elf32-msp430.o \
./osprey/cygnus/bfd/elf32-openrisc.o \
./osprey/cygnus/bfd/elf32-or32.o \
./osprey/cygnus/bfd/elf32-pj.o \
./osprey/cygnus/bfd/elf32-ppc.o \
./osprey/cygnus/bfd/elf32-s390.o \
./osprey/cygnus/bfd/elf32-sh.o \
./osprey/cygnus/bfd/elf32-sh64-com.o \
./osprey/cygnus/bfd/elf32-sh64.o \
./osprey/cygnus/bfd/elf32-sparc.o \
./osprey/cygnus/bfd/elf32-v850.o \
./osprey/cygnus/bfd/elf32-vax.o \
./osprey/cygnus/bfd/elf32-xstormy16.o \
./osprey/cygnus/bfd/elf32-xtensa.o \
./osprey/cygnus/bfd/elf32.o \
./osprey/cygnus/bfd/elf64-alpha.o \
./osprey/cygnus/bfd/elf64-gen.o \
./osprey/cygnus/bfd/elf64-hppa.o \
./osprey/cygnus/bfd/elf64-mips.o \
./osprey/cygnus/bfd/elf64-mmix.o \
./osprey/cygnus/bfd/elf64-ppc.o \
./osprey/cygnus/bfd/elf64-s390.o \
./osprey/cygnus/bfd/elf64-sh64.o \
./osprey/cygnus/bfd/elf64-sparc.o \
./osprey/cygnus/bfd/elf64-x86-64.o \
./osprey/cygnus/bfd/elf64.o \
./osprey/cygnus/bfd/elfarm-nabi.o \
./osprey/cygnus/bfd/elfarm-oabi.o \
./osprey/cygnus/bfd/elflink.o \
./osprey/cygnus/bfd/elfn32-mips.o \
./osprey/cygnus/bfd/elfxx-ia64.o \
./osprey/cygnus/bfd/elfxx-mips.o \
./osprey/cygnus/bfd/epoc-pe-arm.o \
./osprey/cygnus/bfd/epoc-pei-arm.o \
./osprey/cygnus/bfd/format.o \
./osprey/cygnus/bfd/gen-aout.o \
./osprey/cygnus/bfd/hash.o \
./osprey/cygnus/bfd/host-aout.o \
./osprey/cygnus/bfd/hp300bsd.o \
./osprey/cygnus/bfd/hp300hpux.o \
./osprey/cygnus/bfd/hppabsd-core.o \
./osprey/cygnus/bfd/hpux-core.o \
./osprey/cygnus/bfd/i386aout.o \
./osprey/cygnus/bfd/i386bsd.o \
./osprey/cygnus/bfd/i386dynix.o \
./osprey/cygnus/bfd/i386freebsd.o \
./osprey/cygnus/bfd/i386linux.o \
./osprey/cygnus/bfd/i386lynx.o \
./osprey/cygnus/bfd/i386mach3.o \
./osprey/cygnus/bfd/i386msdos.o \
./osprey/cygnus/bfd/i386netbsd.o \
./osprey/cygnus/bfd/i386os9k.o \
./osprey/cygnus/bfd/ieee.o \
./osprey/cygnus/bfd/ihex.o \
./osprey/cygnus/bfd/init.o \
./osprey/cygnus/bfd/ipa_cmdline.o \
./osprey/cygnus/bfd/ipa_ld.o \
./osprey/cygnus/bfd/irix-core.o \
./osprey/cygnus/bfd/libbfd.o \
./osprey/cygnus/bfd/linker.o \
./osprey/cygnus/bfd/lynx-core.o \
./osprey/cygnus/bfd/m68k4knetbsd.o \
./osprey/cygnus/bfd/m68klinux.o \
./osprey/cygnus/bfd/m68klynx.o \
./osprey/cygnus/bfd/m68knetbsd.o \
./osprey/cygnus/bfd/m88kmach3.o \
./osprey/cygnus/bfd/mach-o-target.o \
./osprey/cygnus/bfd/mach-o.o \
./osprey/cygnus/bfd/merge.o \
./osprey/cygnus/bfd/mipsbsd.o \
./osprey/cygnus/bfd/mmo.o \
./osprey/cygnus/bfd/netbsd-core.o \
./osprey/cygnus/bfd/newsos3.o \
./osprey/cygnus/bfd/nlm.o \
./osprey/cygnus/bfd/nlm32-alpha.o \
./osprey/cygnus/bfd/nlm32-i386.o \
./osprey/cygnus/bfd/nlm32-ppc.o \
./osprey/cygnus/bfd/nlm32-sparc.o \
./osprey/cygnus/bfd/nlm32.o \
./osprey/cygnus/bfd/nlm64.o \
./osprey/cygnus/bfd/ns32knetbsd.o \
./osprey/cygnus/bfd/oasys.o \
./osprey/cygnus/bfd/opncls.o \
./osprey/cygnus/bfd/osf-core.o \
./osprey/cygnus/bfd/pc532-mach.o \
./osprey/cygnus/bfd/pdp11.o \
./osprey/cygnus/bfd/pe-arm.o \
./osprey/cygnus/bfd/pe-i386.o \
./osprey/cygnus/bfd/pe-mcore.o \
./osprey/cygnus/bfd/pe-mips.o \
./osprey/cygnus/bfd/pe-ppc.o \
./osprey/cygnus/bfd/pe-sh.o \
./osprey/cygnus/bfd/peXXigen.o \
./osprey/cygnus/bfd/pef.o \
./osprey/cygnus/bfd/pei-arm.o \
./osprey/cygnus/bfd/pei-i386.o \
./osprey/cygnus/bfd/pei-mcore.o \
./osprey/cygnus/bfd/pei-mips.o \
./osprey/cygnus/bfd/pei-ppc.o \
./osprey/cygnus/bfd/pei-sh.o \
./osprey/cygnus/bfd/peigen.o \
./osprey/cygnus/bfd/ppcboot.o \
./osprey/cygnus/bfd/ptrace-core.o \
./osprey/cygnus/bfd/reloc.o \
./osprey/cygnus/bfd/reloc16.o \
./osprey/cygnus/bfd/riscix.o \
./osprey/cygnus/bfd/rs6000-core.o \
./osprey/cygnus/bfd/sco5-core.o \
./osprey/cygnus/bfd/section.o \
./osprey/cygnus/bfd/simple.o \
./osprey/cygnus/bfd/som.o \
./osprey/cygnus/bfd/sparclinux.o \
./osprey/cygnus/bfd/sparclynx.o \
./osprey/cygnus/bfd/sparcnetbsd.o \
./osprey/cygnus/bfd/srec.o \
./osprey/cygnus/bfd/stab-syms.o \
./osprey/cygnus/bfd/stabs.o \
./osprey/cygnus/bfd/sunos.o \
./osprey/cygnus/bfd/syms.o \
./osprey/cygnus/bfd/targets.o \
./osprey/cygnus/bfd/tekhex.o \
./osprey/cygnus/bfd/trad-core.o \
./osprey/cygnus/bfd/vax1knetbsd.o \
./osprey/cygnus/bfd/vaxbsd.o \
./osprey/cygnus/bfd/vaxnetbsd.o \
./osprey/cygnus/bfd/versados.o \
./osprey/cygnus/bfd/vms-gsd.o \
./osprey/cygnus/bfd/vms-hdr.o \
./osprey/cygnus/bfd/vms-misc.o \
./osprey/cygnus/bfd/vms-tir.o \
./osprey/cygnus/bfd/vms.o \
./osprey/cygnus/bfd/xcofflink.o \
./osprey/cygnus/bfd/xsym.o \
./osprey/cygnus/bfd/xtensa-isa.o \
./osprey/cygnus/bfd/xtensa-modules.o 

C_DEPS += \
./osprey/cygnus/bfd/aix386-core.d \
./osprey/cygnus/bfd/aix5ppc-core.d \
./osprey/cygnus/bfd/aout-adobe.d \
./osprey/cygnus/bfd/aout-arm.d \
./osprey/cygnus/bfd/aout-cris.d \
./osprey/cygnus/bfd/aout-encap.d \
./osprey/cygnus/bfd/aout-ns32k.d \
./osprey/cygnus/bfd/aout-sparcle.d \
./osprey/cygnus/bfd/aout-tic30.d \
./osprey/cygnus/bfd/aout0.d \
./osprey/cygnus/bfd/aout32.d \
./osprey/cygnus/bfd/aout64.d \
./osprey/cygnus/bfd/archive.d \
./osprey/cygnus/bfd/archive64.d \
./osprey/cygnus/bfd/archures.d \
./osprey/cygnus/bfd/armnetbsd.d \
./osprey/cygnus/bfd/bfd.d \
./osprey/cygnus/bfd/bfdio.d \
./osprey/cygnus/bfd/bfdwin.d \
./osprey/cygnus/bfd/binary.d \
./osprey/cygnus/bfd/bout.d \
./osprey/cygnus/bfd/cache.d \
./osprey/cygnus/bfd/cf-i386lynx.d \
./osprey/cygnus/bfd/cf-m68klynx.d \
./osprey/cygnus/bfd/cf-sparclynx.d \
./osprey/cygnus/bfd/cisco-core.d \
./osprey/cygnus/bfd/coff-a29k.d \
./osprey/cygnus/bfd/coff-alpha.d \
./osprey/cygnus/bfd/coff-apollo.d \
./osprey/cygnus/bfd/coff-arm.d \
./osprey/cygnus/bfd/coff-aux.d \
./osprey/cygnus/bfd/coff-go32.d \
./osprey/cygnus/bfd/coff-h8300.d \
./osprey/cygnus/bfd/coff-h8500.d \
./osprey/cygnus/bfd/coff-i386.d \
./osprey/cygnus/bfd/coff-i860.d \
./osprey/cygnus/bfd/coff-i960.d \
./osprey/cygnus/bfd/coff-ia64.d \
./osprey/cygnus/bfd/coff-m68k.d \
./osprey/cygnus/bfd/coff-m88k.d \
./osprey/cygnus/bfd/coff-mcore.d \
./osprey/cygnus/bfd/coff-mips.d \
./osprey/cygnus/bfd/coff-or32.d \
./osprey/cygnus/bfd/coff-pmac.d \
./osprey/cygnus/bfd/coff-ppc.d \
./osprey/cygnus/bfd/coff-rs6000.d \
./osprey/cygnus/bfd/coff-sh.d \
./osprey/cygnus/bfd/coff-sparc.d \
./osprey/cygnus/bfd/coff-stgo32.d \
./osprey/cygnus/bfd/coff-svm68k.d \
./osprey/cygnus/bfd/coff-tic30.d \
./osprey/cygnus/bfd/coff-tic4x.d \
./osprey/cygnus/bfd/coff-tic54x.d \
./osprey/cygnus/bfd/coff-tic80.d \
./osprey/cygnus/bfd/coff-u68k.d \
./osprey/cygnus/bfd/coff-w65.d \
./osprey/cygnus/bfd/coff-we32k.d \
./osprey/cygnus/bfd/coff-z8k.d \
./osprey/cygnus/bfd/coff64-rs6000.d \
./osprey/cygnus/bfd/coffgen.d \
./osprey/cygnus/bfd/cofflink.d \
./osprey/cygnus/bfd/corefile.d \
./osprey/cygnus/bfd/cpu-a29k.d \
./osprey/cygnus/bfd/cpu-alpha.d \
./osprey/cygnus/bfd/cpu-arc.d \
./osprey/cygnus/bfd/cpu-arm.d \
./osprey/cygnus/bfd/cpu-avr.d \
./osprey/cygnus/bfd/cpu-cris.d \
./osprey/cygnus/bfd/cpu-d10v.d \
./osprey/cygnus/bfd/cpu-d30v.d \
./osprey/cygnus/bfd/cpu-dlx.d \
./osprey/cygnus/bfd/cpu-fr30.d \
./osprey/cygnus/bfd/cpu-frv.d \
./osprey/cygnus/bfd/cpu-h8300.d \
./osprey/cygnus/bfd/cpu-h8500.d \
./osprey/cygnus/bfd/cpu-hppa.d \
./osprey/cygnus/bfd/cpu-i370.d \
./osprey/cygnus/bfd/cpu-i386.d \
./osprey/cygnus/bfd/cpu-i860.d \
./osprey/cygnus/bfd/cpu-i960.d \
./osprey/cygnus/bfd/cpu-ia64-opc.d \
./osprey/cygnus/bfd/cpu-ia64.d \
./osprey/cygnus/bfd/cpu-ip2k.d \
./osprey/cygnus/bfd/cpu-iq2000.d \
./osprey/cygnus/bfd/cpu-m10200.d \
./osprey/cygnus/bfd/cpu-m10300.d \
./osprey/cygnus/bfd/cpu-m32r.d \
./osprey/cygnus/bfd/cpu-m68hc11.d \
./osprey/cygnus/bfd/cpu-m68hc12.d \
./osprey/cygnus/bfd/cpu-m68k.d \
./osprey/cygnus/bfd/cpu-m88k.d \
./osprey/cygnus/bfd/cpu-mcore.d \
./osprey/cygnus/bfd/cpu-mips.d \
./osprey/cygnus/bfd/cpu-mmix.d \
./osprey/cygnus/bfd/cpu-msp430.d \
./osprey/cygnus/bfd/cpu-ns32k.d \
./osprey/cygnus/bfd/cpu-openrisc.d \
./osprey/cygnus/bfd/cpu-or32.d \
./osprey/cygnus/bfd/cpu-pdp11.d \
./osprey/cygnus/bfd/cpu-pj.d \
./osprey/cygnus/bfd/cpu-powerpc.d \
./osprey/cygnus/bfd/cpu-rs6000.d \
./osprey/cygnus/bfd/cpu-s390.d \
./osprey/cygnus/bfd/cpu-sh.d \
./osprey/cygnus/bfd/cpu-sparc.d \
./osprey/cygnus/bfd/cpu-tic30.d \
./osprey/cygnus/bfd/cpu-tic4x.d \
./osprey/cygnus/bfd/cpu-tic54x.d \
./osprey/cygnus/bfd/cpu-tic80.d \
./osprey/cygnus/bfd/cpu-v850.d \
./osprey/cygnus/bfd/cpu-vax.d \
./osprey/cygnus/bfd/cpu-w65.d \
./osprey/cygnus/bfd/cpu-we32k.d \
./osprey/cygnus/bfd/cpu-xstormy16.d \
./osprey/cygnus/bfd/cpu-xtensa.d \
./osprey/cygnus/bfd/cpu-z8k.d \
./osprey/cygnus/bfd/demo64.d \
./osprey/cygnus/bfd/dwarf1.d \
./osprey/cygnus/bfd/dwarf2.d \
./osprey/cygnus/bfd/ecoff.d \
./osprey/cygnus/bfd/ecofflink.d \
./osprey/cygnus/bfd/efi-app-ia32.d \
./osprey/cygnus/bfd/efi-app-ia64.d \
./osprey/cygnus/bfd/elf-eh-frame.d \
./osprey/cygnus/bfd/elf-m10200.d \
./osprey/cygnus/bfd/elf-m10300.d \
./osprey/cygnus/bfd/elf-strtab.d \
./osprey/cygnus/bfd/elf.d \
./osprey/cygnus/bfd/elf32-am33lin.d \
./osprey/cygnus/bfd/elf32-arc.d \
./osprey/cygnus/bfd/elf32-avr.d \
./osprey/cygnus/bfd/elf32-cris.d \
./osprey/cygnus/bfd/elf32-d10v.d \
./osprey/cygnus/bfd/elf32-d30v.d \
./osprey/cygnus/bfd/elf32-dlx.d \
./osprey/cygnus/bfd/elf32-fr30.d \
./osprey/cygnus/bfd/elf32-frv.d \
./osprey/cygnus/bfd/elf32-gen.d \
./osprey/cygnus/bfd/elf32-h8300.d \
./osprey/cygnus/bfd/elf32-hppa.d \
./osprey/cygnus/bfd/elf32-i370.d \
./osprey/cygnus/bfd/elf32-i386.d \
./osprey/cygnus/bfd/elf32-i860.d \
./osprey/cygnus/bfd/elf32-i960.d \
./osprey/cygnus/bfd/elf32-ip2k.d \
./osprey/cygnus/bfd/elf32-iq2000.d \
./osprey/cygnus/bfd/elf32-m32r.d \
./osprey/cygnus/bfd/elf32-m68hc11.d \
./osprey/cygnus/bfd/elf32-m68hc12.d \
./osprey/cygnus/bfd/elf32-m68hc1x.d \
./osprey/cygnus/bfd/elf32-m68k.d \
./osprey/cygnus/bfd/elf32-m88k.d \
./osprey/cygnus/bfd/elf32-mcore.d \
./osprey/cygnus/bfd/elf32-mips.d \
./osprey/cygnus/bfd/elf32-msp430.d \
./osprey/cygnus/bfd/elf32-openrisc.d \
./osprey/cygnus/bfd/elf32-or32.d \
./osprey/cygnus/bfd/elf32-pj.d \
./osprey/cygnus/bfd/elf32-ppc.d \
./osprey/cygnus/bfd/elf32-s390.d \
./osprey/cygnus/bfd/elf32-sh.d \
./osprey/cygnus/bfd/elf32-sh64-com.d \
./osprey/cygnus/bfd/elf32-sh64.d \
./osprey/cygnus/bfd/elf32-sparc.d \
./osprey/cygnus/bfd/elf32-v850.d \
./osprey/cygnus/bfd/elf32-vax.d \
./osprey/cygnus/bfd/elf32-xstormy16.d \
./osprey/cygnus/bfd/elf32-xtensa.d \
./osprey/cygnus/bfd/elf32.d \
./osprey/cygnus/bfd/elf64-alpha.d \
./osprey/cygnus/bfd/elf64-gen.d \
./osprey/cygnus/bfd/elf64-hppa.d \
./osprey/cygnus/bfd/elf64-mips.d \
./osprey/cygnus/bfd/elf64-mmix.d \
./osprey/cygnus/bfd/elf64-ppc.d \
./osprey/cygnus/bfd/elf64-s390.d \
./osprey/cygnus/bfd/elf64-sh64.d \
./osprey/cygnus/bfd/elf64-sparc.d \
./osprey/cygnus/bfd/elf64-x86-64.d \
./osprey/cygnus/bfd/elf64.d \
./osprey/cygnus/bfd/elfarm-nabi.d \
./osprey/cygnus/bfd/elfarm-oabi.d \
./osprey/cygnus/bfd/elflink.d \
./osprey/cygnus/bfd/elfn32-mips.d \
./osprey/cygnus/bfd/elfxx-ia64.d \
./osprey/cygnus/bfd/elfxx-mips.d \
./osprey/cygnus/bfd/epoc-pe-arm.d \
./osprey/cygnus/bfd/epoc-pei-arm.d \
./osprey/cygnus/bfd/format.d \
./osprey/cygnus/bfd/gen-aout.d \
./osprey/cygnus/bfd/hash.d \
./osprey/cygnus/bfd/host-aout.d \
./osprey/cygnus/bfd/hp300bsd.d \
./osprey/cygnus/bfd/hp300hpux.d \
./osprey/cygnus/bfd/hppabsd-core.d \
./osprey/cygnus/bfd/hpux-core.d \
./osprey/cygnus/bfd/i386aout.d \
./osprey/cygnus/bfd/i386bsd.d \
./osprey/cygnus/bfd/i386dynix.d \
./osprey/cygnus/bfd/i386freebsd.d \
./osprey/cygnus/bfd/i386linux.d \
./osprey/cygnus/bfd/i386lynx.d \
./osprey/cygnus/bfd/i386mach3.d \
./osprey/cygnus/bfd/i386msdos.d \
./osprey/cygnus/bfd/i386netbsd.d \
./osprey/cygnus/bfd/i386os9k.d \
./osprey/cygnus/bfd/ieee.d \
./osprey/cygnus/bfd/ihex.d \
./osprey/cygnus/bfd/init.d \
./osprey/cygnus/bfd/ipa_cmdline.d \
./osprey/cygnus/bfd/ipa_ld.d \
./osprey/cygnus/bfd/irix-core.d \
./osprey/cygnus/bfd/libbfd.d \
./osprey/cygnus/bfd/linker.d \
./osprey/cygnus/bfd/lynx-core.d \
./osprey/cygnus/bfd/m68k4knetbsd.d \
./osprey/cygnus/bfd/m68klinux.d \
./osprey/cygnus/bfd/m68klynx.d \
./osprey/cygnus/bfd/m68knetbsd.d \
./osprey/cygnus/bfd/m88kmach3.d \
./osprey/cygnus/bfd/mach-o-target.d \
./osprey/cygnus/bfd/mach-o.d \
./osprey/cygnus/bfd/merge.d \
./osprey/cygnus/bfd/mipsbsd.d \
./osprey/cygnus/bfd/mmo.d \
./osprey/cygnus/bfd/netbsd-core.d \
./osprey/cygnus/bfd/newsos3.d \
./osprey/cygnus/bfd/nlm.d \
./osprey/cygnus/bfd/nlm32-alpha.d \
./osprey/cygnus/bfd/nlm32-i386.d \
./osprey/cygnus/bfd/nlm32-ppc.d \
./osprey/cygnus/bfd/nlm32-sparc.d \
./osprey/cygnus/bfd/nlm32.d \
./osprey/cygnus/bfd/nlm64.d \
./osprey/cygnus/bfd/ns32knetbsd.d \
./osprey/cygnus/bfd/oasys.d \
./osprey/cygnus/bfd/opncls.d \
./osprey/cygnus/bfd/osf-core.d \
./osprey/cygnus/bfd/pc532-mach.d \
./osprey/cygnus/bfd/pdp11.d \
./osprey/cygnus/bfd/pe-arm.d \
./osprey/cygnus/bfd/pe-i386.d \
./osprey/cygnus/bfd/pe-mcore.d \
./osprey/cygnus/bfd/pe-mips.d \
./osprey/cygnus/bfd/pe-ppc.d \
./osprey/cygnus/bfd/pe-sh.d \
./osprey/cygnus/bfd/peXXigen.d \
./osprey/cygnus/bfd/pef.d \
./osprey/cygnus/bfd/pei-arm.d \
./osprey/cygnus/bfd/pei-i386.d \
./osprey/cygnus/bfd/pei-mcore.d \
./osprey/cygnus/bfd/pei-mips.d \
./osprey/cygnus/bfd/pei-ppc.d \
./osprey/cygnus/bfd/pei-sh.d \
./osprey/cygnus/bfd/peigen.d \
./osprey/cygnus/bfd/ppcboot.d \
./osprey/cygnus/bfd/ptrace-core.d \
./osprey/cygnus/bfd/reloc.d \
./osprey/cygnus/bfd/reloc16.d \
./osprey/cygnus/bfd/riscix.d \
./osprey/cygnus/bfd/rs6000-core.d \
./osprey/cygnus/bfd/sco5-core.d \
./osprey/cygnus/bfd/section.d \
./osprey/cygnus/bfd/simple.d \
./osprey/cygnus/bfd/som.d \
./osprey/cygnus/bfd/sparclinux.d \
./osprey/cygnus/bfd/sparclynx.d \
./osprey/cygnus/bfd/sparcnetbsd.d \
./osprey/cygnus/bfd/srec.d \
./osprey/cygnus/bfd/stab-syms.d \
./osprey/cygnus/bfd/stabs.d \
./osprey/cygnus/bfd/sunos.d \
./osprey/cygnus/bfd/syms.d \
./osprey/cygnus/bfd/targets.d \
./osprey/cygnus/bfd/tekhex.d \
./osprey/cygnus/bfd/trad-core.d \
./osprey/cygnus/bfd/vax1knetbsd.d \
./osprey/cygnus/bfd/vaxbsd.d \
./osprey/cygnus/bfd/vaxnetbsd.d \
./osprey/cygnus/bfd/versados.d \
./osprey/cygnus/bfd/vms-gsd.d \
./osprey/cygnus/bfd/vms-hdr.d \
./osprey/cygnus/bfd/vms-misc.d \
./osprey/cygnus/bfd/vms-tir.d \
./osprey/cygnus/bfd/vms.d \
./osprey/cygnus/bfd/xcofflink.d \
./osprey/cygnus/bfd/xsym.d \
./osprey/cygnus/bfd/xtensa-isa.d \
./osprey/cygnus/bfd/xtensa-modules.d 


# Each subdirectory must supply rules for building sources it contributes
osprey/cygnus/bfd/%.o: ../osprey/cygnus/bfd/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


