################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../osprey/libf/fio/backspace.c \
../osprey/libf/fio/cls.c \
../osprey/libf/fio/cntigchk.c \
../osprey/libf/fio/dfi.c \
../osprey/libf/fio/dopexfer.c \
../osprey/libf/fio/dsetpos.c \
../osprey/libf/fio/dumppfmt.c \
../osprey/libf/fio/efi.c \
../osprey/libf/fio/endfile.c \
../osprey/libf/fio/f77wrappers.c \
../osprey/libf/fio/f90_main.c \
../osprey/libf/fio/fcleanup.c \
../osprey/libf/fio/fcontext.c \
../osprey/libf/fio/ferror.c \
../osprey/libf/fio/fffcntl.c \
../osprey/libf/fio/fgetc.c \
../osprey/libf/fio/finit.c \
../osprey/libf/fio/flsh_mem.c \
../osprey/libf/fio/flush.c \
../osprey/libf/fio/fmtchk.c \
../osprey/libf/fio/fmtparse.c \
../osprey/libf/fio/fnum.c \
../osprey/libf/fio/fopn.c \
../osprey/libf/fio/fork.c \
../osprey/libf/fio/fortunit.c \
../osprey/libf/fio/fputc.c \
../osprey/libf/fio/frch.c \
../osprey/libf/fio/frwd.c \
../osprey/libf/fio/fseek.c \
../osprey/libf/fio/fstat.c \
../osprey/libf/fio/fstring.c \
../osprey/libf/fio/ftell.c \
../osprey/libf/fio/fwarn.c \
../osprey/libf/fio/fwch.c \
../osprey/libf/fio/fwwd.c \
../osprey/libf/fio/getdcparam.c \
../osprey/libf/fio/getpos.c \
../osprey/libf/fio/globals.c \
../osprey/libf/fio/iconvtab.c \
../osprey/libf/fio/impopen.c \
../osprey/libf/fio/initunit.c \
../osprey/libf/fio/inq.c \
../osprey/libf/fio/inqil.c \
../osprey/libf/fio/inquire.c \
../osprey/libf/fio/iochunk.c \
../osprey/libf/fio/isatty.c \
../osprey/libf/fio/length.c \
../osprey/libf/fio/lread.c \
../osprey/libf/fio/lu2s.c \
../osprey/libf/fio/lwrite.c \
../osprey/libf/fio/main.c \
../osprey/libf/fio/numblks.c \
../osprey/libf/fio/oconvtab.c \
../osprey/libf/fio/open.c \
../osprey/libf/fio/openutil.c \
../osprey/libf/fio/opn.c \
../osprey/libf/fio/parse.c \
../osprey/libf/fio/parsfmt.c \
../osprey/libf/fio/rb.c \
../osprey/libf/fio/rdfmt.c \
../osprey/libf/fio/rdunf.c \
../osprey/libf/fio/read.c \
../osprey/libf/fio/readc.c \
../osprey/libf/fio/rewind.c \
../osprey/libf/fio/rf.c \
../osprey/libf/fio/rf90.c \
../osprey/libf/fio/rnl90.c \
../osprey/libf/fio/rnl90to77.c \
../osprey/libf/fio/rnldata.c \
../osprey/libf/fio/rnlutil.c \
../osprey/libf/fio/rnly.c \
../osprey/libf/fio/ru.c \
../osprey/libf/fio/ru90.c \
../osprey/libf/fio/s2ub.c \
../osprey/libf/fio/s2ul.c \
../osprey/libf/fio/s2uo.c \
../osprey/libf/fio/s2uz.c \
../osprey/libf/fio/scatgath.c \
../osprey/libf/fio/setbuf.c \
../osprey/libf/fio/setpos.c \
../osprey/libf/fio/setstride.c \
../osprey/libf/fio/skipf.c \
../osprey/libf/fio/stats.c \
../osprey/libf/fio/tables.c \
../osprey/libf/fio/ttynam.c \
../osprey/libf/fio/unit.c \
../osprey/libf/fio/unitbksp.c \
../osprey/libf/fio/unitclose.c \
../osprey/libf/fio/unitseek.c \
../osprey/libf/fio/unittrunc.c \
../osprey/libf/fio/uptr.c \
../osprey/libf/fio/usdumplock.c \
../osprey/libf/fio/usdumpsema.c \
../osprey/libf/fio/util.c \
../osprey/libf/fio/wb.c \
../osprey/libf/fio/wf.c \
../osprey/libf/fio/wf90.c \
../osprey/libf/fio/wnl90.c \
../osprey/libf/fio/wnl90to77.c \
../osprey/libf/fio/wnlutil.c \
../osprey/libf/fio/wnly.c \
../osprey/libf/fio/wrfmt.c \
../osprey/libf/fio/write.c \
../osprey/libf/fio/writec.c \
../osprey/libf/fio/wrunf.c \
../osprey/libf/fio/wu.c \
../osprey/libf/fio/wu90.c \
../osprey/libf/fio/xarg.c 

OBJS += \
./osprey/libf/fio/backspace.o \
./osprey/libf/fio/cls.o \
./osprey/libf/fio/cntigchk.o \
./osprey/libf/fio/dfi.o \
./osprey/libf/fio/dopexfer.o \
./osprey/libf/fio/dsetpos.o \
./osprey/libf/fio/dumppfmt.o \
./osprey/libf/fio/efi.o \
./osprey/libf/fio/endfile.o \
./osprey/libf/fio/f77wrappers.o \
./osprey/libf/fio/f90_main.o \
./osprey/libf/fio/fcleanup.o \
./osprey/libf/fio/fcontext.o \
./osprey/libf/fio/ferror.o \
./osprey/libf/fio/fffcntl.o \
./osprey/libf/fio/fgetc.o \
./osprey/libf/fio/finit.o \
./osprey/libf/fio/flsh_mem.o \
./osprey/libf/fio/flush.o \
./osprey/libf/fio/fmtchk.o \
./osprey/libf/fio/fmtparse.o \
./osprey/libf/fio/fnum.o \
./osprey/libf/fio/fopn.o \
./osprey/libf/fio/fork.o \
./osprey/libf/fio/fortunit.o \
./osprey/libf/fio/fputc.o \
./osprey/libf/fio/frch.o \
./osprey/libf/fio/frwd.o \
./osprey/libf/fio/fseek.o \
./osprey/libf/fio/fstat.o \
./osprey/libf/fio/fstring.o \
./osprey/libf/fio/ftell.o \
./osprey/libf/fio/fwarn.o \
./osprey/libf/fio/fwch.o \
./osprey/libf/fio/fwwd.o \
./osprey/libf/fio/getdcparam.o \
./osprey/libf/fio/getpos.o \
./osprey/libf/fio/globals.o \
./osprey/libf/fio/iconvtab.o \
./osprey/libf/fio/impopen.o \
./osprey/libf/fio/initunit.o \
./osprey/libf/fio/inq.o \
./osprey/libf/fio/inqil.o \
./osprey/libf/fio/inquire.o \
./osprey/libf/fio/iochunk.o \
./osprey/libf/fio/isatty.o \
./osprey/libf/fio/length.o \
./osprey/libf/fio/lread.o \
./osprey/libf/fio/lu2s.o \
./osprey/libf/fio/lwrite.o \
./osprey/libf/fio/main.o \
./osprey/libf/fio/numblks.o \
./osprey/libf/fio/oconvtab.o \
./osprey/libf/fio/open.o \
./osprey/libf/fio/openutil.o \
./osprey/libf/fio/opn.o \
./osprey/libf/fio/parse.o \
./osprey/libf/fio/parsfmt.o \
./osprey/libf/fio/rb.o \
./osprey/libf/fio/rdfmt.o \
./osprey/libf/fio/rdunf.o \
./osprey/libf/fio/read.o \
./osprey/libf/fio/readc.o \
./osprey/libf/fio/rewind.o \
./osprey/libf/fio/rf.o \
./osprey/libf/fio/rf90.o \
./osprey/libf/fio/rnl90.o \
./osprey/libf/fio/rnl90to77.o \
./osprey/libf/fio/rnldata.o \
./osprey/libf/fio/rnlutil.o \
./osprey/libf/fio/rnly.o \
./osprey/libf/fio/ru.o \
./osprey/libf/fio/ru90.o \
./osprey/libf/fio/s2ub.o \
./osprey/libf/fio/s2ul.o \
./osprey/libf/fio/s2uo.o \
./osprey/libf/fio/s2uz.o \
./osprey/libf/fio/scatgath.o \
./osprey/libf/fio/setbuf.o \
./osprey/libf/fio/setpos.o \
./osprey/libf/fio/setstride.o \
./osprey/libf/fio/skipf.o \
./osprey/libf/fio/stats.o \
./osprey/libf/fio/tables.o \
./osprey/libf/fio/ttynam.o \
./osprey/libf/fio/unit.o \
./osprey/libf/fio/unitbksp.o \
./osprey/libf/fio/unitclose.o \
./osprey/libf/fio/unitseek.o \
./osprey/libf/fio/unittrunc.o \
./osprey/libf/fio/uptr.o \
./osprey/libf/fio/usdumplock.o \
./osprey/libf/fio/usdumpsema.o \
./osprey/libf/fio/util.o \
./osprey/libf/fio/wb.o \
./osprey/libf/fio/wf.o \
./osprey/libf/fio/wf90.o \
./osprey/libf/fio/wnl90.o \
./osprey/libf/fio/wnl90to77.o \
./osprey/libf/fio/wnlutil.o \
./osprey/libf/fio/wnly.o \
./osprey/libf/fio/wrfmt.o \
./osprey/libf/fio/write.o \
./osprey/libf/fio/writec.o \
./osprey/libf/fio/wrunf.o \
./osprey/libf/fio/wu.o \
./osprey/libf/fio/wu90.o \
./osprey/libf/fio/xarg.o 

C_DEPS += \
./osprey/libf/fio/backspace.d \
./osprey/libf/fio/cls.d \
./osprey/libf/fio/cntigchk.d \
./osprey/libf/fio/dfi.d \
./osprey/libf/fio/dopexfer.d \
./osprey/libf/fio/dsetpos.d \
./osprey/libf/fio/dumppfmt.d \
./osprey/libf/fio/efi.d \
./osprey/libf/fio/endfile.d \
./osprey/libf/fio/f77wrappers.d \
./osprey/libf/fio/f90_main.d \
./osprey/libf/fio/fcleanup.d \
./osprey/libf/fio/fcontext.d \
./osprey/libf/fio/ferror.d \
./osprey/libf/fio/fffcntl.d \
./osprey/libf/fio/fgetc.d \
./osprey/libf/fio/finit.d \
./osprey/libf/fio/flsh_mem.d \
./osprey/libf/fio/flush.d \
./osprey/libf/fio/fmtchk.d \
./osprey/libf/fio/fmtparse.d \
./osprey/libf/fio/fnum.d \
./osprey/libf/fio/fopn.d \
./osprey/libf/fio/fork.d \
./osprey/libf/fio/fortunit.d \
./osprey/libf/fio/fputc.d \
./osprey/libf/fio/frch.d \
./osprey/libf/fio/frwd.d \
./osprey/libf/fio/fseek.d \
./osprey/libf/fio/fstat.d \
./osprey/libf/fio/fstring.d \
./osprey/libf/fio/ftell.d \
./osprey/libf/fio/fwarn.d \
./osprey/libf/fio/fwch.d \
./osprey/libf/fio/fwwd.d \
./osprey/libf/fio/getdcparam.d \
./osprey/libf/fio/getpos.d \
./osprey/libf/fio/globals.d \
./osprey/libf/fio/iconvtab.d \
./osprey/libf/fio/impopen.d \
./osprey/libf/fio/initunit.d \
./osprey/libf/fio/inq.d \
./osprey/libf/fio/inqil.d \
./osprey/libf/fio/inquire.d \
./osprey/libf/fio/iochunk.d \
./osprey/libf/fio/isatty.d \
./osprey/libf/fio/length.d \
./osprey/libf/fio/lread.d \
./osprey/libf/fio/lu2s.d \
./osprey/libf/fio/lwrite.d \
./osprey/libf/fio/main.d \
./osprey/libf/fio/numblks.d \
./osprey/libf/fio/oconvtab.d \
./osprey/libf/fio/open.d \
./osprey/libf/fio/openutil.d \
./osprey/libf/fio/opn.d \
./osprey/libf/fio/parse.d \
./osprey/libf/fio/parsfmt.d \
./osprey/libf/fio/rb.d \
./osprey/libf/fio/rdfmt.d \
./osprey/libf/fio/rdunf.d \
./osprey/libf/fio/read.d \
./osprey/libf/fio/readc.d \
./osprey/libf/fio/rewind.d \
./osprey/libf/fio/rf.d \
./osprey/libf/fio/rf90.d \
./osprey/libf/fio/rnl90.d \
./osprey/libf/fio/rnl90to77.d \
./osprey/libf/fio/rnldata.d \
./osprey/libf/fio/rnlutil.d \
./osprey/libf/fio/rnly.d \
./osprey/libf/fio/ru.d \
./osprey/libf/fio/ru90.d \
./osprey/libf/fio/s2ub.d \
./osprey/libf/fio/s2ul.d \
./osprey/libf/fio/s2uo.d \
./osprey/libf/fio/s2uz.d \
./osprey/libf/fio/scatgath.d \
./osprey/libf/fio/setbuf.d \
./osprey/libf/fio/setpos.d \
./osprey/libf/fio/setstride.d \
./osprey/libf/fio/skipf.d \
./osprey/libf/fio/stats.d \
./osprey/libf/fio/tables.d \
./osprey/libf/fio/ttynam.d \
./osprey/libf/fio/unit.d \
./osprey/libf/fio/unitbksp.d \
./osprey/libf/fio/unitclose.d \
./osprey/libf/fio/unitseek.d \
./osprey/libf/fio/unittrunc.d \
./osprey/libf/fio/uptr.d \
./osprey/libf/fio/usdumplock.d \
./osprey/libf/fio/usdumpsema.d \
./osprey/libf/fio/util.d \
./osprey/libf/fio/wb.d \
./osprey/libf/fio/wf.d \
./osprey/libf/fio/wf90.d \
./osprey/libf/fio/wnl90.d \
./osprey/libf/fio/wnl90to77.d \
./osprey/libf/fio/wnlutil.d \
./osprey/libf/fio/wnly.d \
./osprey/libf/fio/wrfmt.d \
./osprey/libf/fio/write.d \
./osprey/libf/fio/writec.d \
./osprey/libf/fio/wrunf.d \
./osprey/libf/fio/wu.d \
./osprey/libf/fio/wu90.d \
./osprey/libf/fio/xarg.d 


# Each subdirectory must supply rules for building sources it contributes
osprey/libf/fio/%.o: ../osprey/libf/fio/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


