################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../osprey/kgccfe/gnu/alias.c \
../osprey/kgccfe/gnu/attribs.c \
../osprey/kgccfe/gnu/bb-reorder.c \
../osprey/kgccfe/gnu/bitmap.c \
../osprey/kgccfe/gnu/builtins.c \
../osprey/kgccfe/gnu/c-aux-info.c \
../osprey/kgccfe/gnu/c-common.c \
../osprey/kgccfe/gnu/c-convert.c \
../osprey/kgccfe/gnu/c-decl.c \
../osprey/kgccfe/gnu/c-dump.c \
../osprey/kgccfe/gnu/c-errors.c \
../osprey/kgccfe/gnu/c-format.c \
../osprey/kgccfe/gnu/c-lang.c \
../osprey/kgccfe/gnu/c-lex.c \
../osprey/kgccfe/gnu/c-objc-common.c \
../osprey/kgccfe/gnu/c-opts.c \
../osprey/kgccfe/gnu/c-pragma.c \
../osprey/kgccfe/gnu/c-pretty-print.c \
../osprey/kgccfe/gnu/c-semantics.c \
../osprey/kgccfe/gnu/c-typeck.c \
../osprey/kgccfe/gnu/caller-save.c \
../osprey/kgccfe/gnu/calls.c \
../osprey/kgccfe/gnu/cfg.c \
../osprey/kgccfe/gnu/cfganal.c \
../osprey/kgccfe/gnu/cfgbuild.c \
../osprey/kgccfe/gnu/cfgcleanup.c \
../osprey/kgccfe/gnu/cfglayout.c \
../osprey/kgccfe/gnu/cfgloop.c \
../osprey/kgccfe/gnu/cfgrtl.c \
../osprey/kgccfe/gnu/collect2.c \
../osprey/kgccfe/gnu/combine.c \
../osprey/kgccfe/gnu/conflict.c \
../osprey/kgccfe/gnu/convert.c \
../osprey/kgccfe/gnu/cppdefault.c \
../osprey/kgccfe/gnu/cpperror.c \
../osprey/kgccfe/gnu/cppexp.c \
../osprey/kgccfe/gnu/cppfiles.c \
../osprey/kgccfe/gnu/cpphash.c \
../osprey/kgccfe/gnu/cppinit.c \
../osprey/kgccfe/gnu/cpplex.c \
../osprey/kgccfe/gnu/cpplib.c \
../osprey/kgccfe/gnu/cppmacro.c \
../osprey/kgccfe/gnu/cppmain.c \
../osprey/kgccfe/gnu/cppspec.c \
../osprey/kgccfe/gnu/cpptrad.c \
../osprey/kgccfe/gnu/crtstuff.c \
../osprey/kgccfe/gnu/cse.c \
../osprey/kgccfe/gnu/cselib.c \
../osprey/kgccfe/gnu/dbxout.c \
../osprey/kgccfe/gnu/debug.c \
../osprey/kgccfe/gnu/dependence.c \
../osprey/kgccfe/gnu/df.c \
../osprey/kgccfe/gnu/diagnostic.c \
../osprey/kgccfe/gnu/doloop.c \
../osprey/kgccfe/gnu/dominance.c \
../osprey/kgccfe/gnu/doschk.c \
../osprey/kgccfe/gnu/dummy-conditions.c \
../osprey/kgccfe/gnu/dwarf2asm.c \
../osprey/kgccfe/gnu/dwarf2out.c \
../osprey/kgccfe/gnu/dwarfout.c \
../osprey/kgccfe/gnu/emit-rtl.c \
../osprey/kgccfe/gnu/enquire.c \
../osprey/kgccfe/gnu/errors.c \
../osprey/kgccfe/gnu/et-forest.c \
../osprey/kgccfe/gnu/except.c \
../osprey/kgccfe/gnu/explow.c \
../osprey/kgccfe/gnu/expmed.c \
../osprey/kgccfe/gnu/expr.c \
../osprey/kgccfe/gnu/final.c \
../osprey/kgccfe/gnu/fix-header.c \
../osprey/kgccfe/gnu/floatlib.c \
../osprey/kgccfe/gnu/flow.c \
../osprey/kgccfe/gnu/fold-const.c \
../osprey/kgccfe/gnu/fp-test.c \
../osprey/kgccfe/gnu/function.c \
../osprey/kgccfe/gnu/gcc.c \
../osprey/kgccfe/gnu/gccspec.c \
../osprey/kgccfe/gnu/gcov.c \
../osprey/kgccfe/gnu/gcse.c \
../osprey/kgccfe/gnu/gen-protos.c \
../osprey/kgccfe/gnu/genattr.c \
../osprey/kgccfe/gnu/genattrtab.c \
../osprey/kgccfe/gnu/genautomata.c \
../osprey/kgccfe/gnu/gencheck.c \
../osprey/kgccfe/gnu/gencodes.c \
../osprey/kgccfe/gnu/genconditions.c \
../osprey/kgccfe/gnu/genconfig.c \
../osprey/kgccfe/gnu/genconstants.c \
../osprey/kgccfe/gnu/genemit.c \
../osprey/kgccfe/gnu/genextract.c \
../osprey/kgccfe/gnu/genflags.c \
../osprey/kgccfe/gnu/gengenrtl.c \
../osprey/kgccfe/gnu/gengtype.c \
../osprey/kgccfe/gnu/genopinit.c \
../osprey/kgccfe/gnu/genoutput.c \
../osprey/kgccfe/gnu/genpeep.c \
../osprey/kgccfe/gnu/genpreds.c \
../osprey/kgccfe/gnu/genrecog.c \
../osprey/kgccfe/gnu/gensupport.c \
../osprey/kgccfe/gnu/ggc-callbacks.c \
../osprey/kgccfe/gnu/ggc-common.c \
../osprey/kgccfe/gnu/ggc-none.c \
../osprey/kgccfe/gnu/ggc-page.c \
../osprey/kgccfe/gnu/ggc-simple.c \
../osprey/kgccfe/gnu/global.c \
../osprey/kgccfe/gnu/gmon.c \
../osprey/kgccfe/gnu/graph.c \
../osprey/kgccfe/gnu/haifa-sched.c \
../osprey/kgccfe/gnu/halfpic.c \
../osprey/kgccfe/gnu/hash.c \
../osprey/kgccfe/gnu/hashtable.c \
../osprey/kgccfe/gnu/hooks.c \
../osprey/kgccfe/gnu/ifcvt.c \
../osprey/kgccfe/gnu/integrate.c \
../osprey/kgccfe/gnu/intl.c \
../osprey/kgccfe/gnu/jump.c \
../osprey/kgccfe/gnu/langhooks.c \
../osprey/kgccfe/gnu/lcm.c \
../osprey/kgccfe/gnu/libgcc2.c \
../osprey/kgccfe/gnu/line-map.c \
../osprey/kgccfe/gnu/lists.c \
../osprey/kgccfe/gnu/local-alloc.c \
../osprey/kgccfe/gnu/loop.c \
../osprey/kgccfe/gnu/main.c \
../osprey/kgccfe/gnu/mbchar.c \
../osprey/kgccfe/gnu/mips-tdump.c \
../osprey/kgccfe/gnu/mips-tfile.c \
../osprey/kgccfe/gnu/mips.c \
../osprey/kgccfe/gnu/mkdeps.c \
../osprey/kgccfe/gnu/optabs.c \
../osprey/kgccfe/gnu/params.c \
../osprey/kgccfe/gnu/predict.c \
../osprey/kgccfe/gnu/prefix.c \
../osprey/kgccfe/gnu/print-rtl.c \
../osprey/kgccfe/gnu/print-tree.c \
../osprey/kgccfe/gnu/profile.c \
../osprey/kgccfe/gnu/protoize.c \
../osprey/kgccfe/gnu/ra-build.c \
../osprey/kgccfe/gnu/ra-colorize.c \
../osprey/kgccfe/gnu/ra-debug.c \
../osprey/kgccfe/gnu/ra-rewrite.c \
../osprey/kgccfe/gnu/ra.c \
../osprey/kgccfe/gnu/read-rtl.c \
../osprey/kgccfe/gnu/real.c \
../osprey/kgccfe/gnu/recog.c \
../osprey/kgccfe/gnu/reg-stack.c \
../osprey/kgccfe/gnu/regclass.c \
../osprey/kgccfe/gnu/regmove.c \
../osprey/kgccfe/gnu/regrename.c \
../osprey/kgccfe/gnu/reload.c \
../osprey/kgccfe/gnu/reload1.c \
../osprey/kgccfe/gnu/reorg.c \
../osprey/kgccfe/gnu/resource.c \
../osprey/kgccfe/gnu/rtl-error.c \
../osprey/kgccfe/gnu/rtl.c \
../osprey/kgccfe/gnu/rtlanal.c \
../osprey/kgccfe/gnu/sbitmap.c \
../osprey/kgccfe/gnu/scan-decls.c \
../osprey/kgccfe/gnu/scan.c \
../osprey/kgccfe/gnu/sched-deps.c \
../osprey/kgccfe/gnu/sched-ebb.c \
../osprey/kgccfe/gnu/sched-rgn.c \
../osprey/kgccfe/gnu/sched-vis.c \
../osprey/kgccfe/gnu/sdbout.c \
../osprey/kgccfe/gnu/sibcall.c \
../osprey/kgccfe/gnu/simplify-rtx.c \
../osprey/kgccfe/gnu/ssa-ccp.c \
../osprey/kgccfe/gnu/ssa-dce.c \
../osprey/kgccfe/gnu/ssa.c \
../osprey/kgccfe/gnu/stmt.c \
../osprey/kgccfe/gnu/stor-layout.c \
../osprey/kgccfe/gnu/stringpool.c \
../osprey/kgccfe/gnu/timevar.c \
../osprey/kgccfe/gnu/tlink.c \
../osprey/kgccfe/gnu/toplev.c \
../osprey/kgccfe/gnu/tracer.c \
../osprey/kgccfe/gnu/tradcpp.c \
../osprey/kgccfe/gnu/tree-dump.c \
../osprey/kgccfe/gnu/tree-inline.c \
../osprey/kgccfe/gnu/tree.c \
../osprey/kgccfe/gnu/unroll.c \
../osprey/kgccfe/gnu/unwind-c.c \
../osprey/kgccfe/gnu/unwind-dw2-fde-darwin.c \
../osprey/kgccfe/gnu/unwind-dw2-fde-glibc.c \
../osprey/kgccfe/gnu/unwind-dw2-fde.c \
../osprey/kgccfe/gnu/unwind-dw2.c \
../osprey/kgccfe/gnu/unwind-sjlj.c \
../osprey/kgccfe/gnu/varasm.c \
../osprey/kgccfe/gnu/varray.c \
../osprey/kgccfe/gnu/version.c \
../osprey/kgccfe/gnu/vmsdbgout.c \
../osprey/kgccfe/gnu/xcoffout.c \
../osprey/kgccfe/gnu/y.tab.c 

OBJS += \
./osprey/kgccfe/gnu/alias.o \
./osprey/kgccfe/gnu/attribs.o \
./osprey/kgccfe/gnu/bb-reorder.o \
./osprey/kgccfe/gnu/bitmap.o \
./osprey/kgccfe/gnu/builtins.o \
./osprey/kgccfe/gnu/c-aux-info.o \
./osprey/kgccfe/gnu/c-common.o \
./osprey/kgccfe/gnu/c-convert.o \
./osprey/kgccfe/gnu/c-decl.o \
./osprey/kgccfe/gnu/c-dump.o \
./osprey/kgccfe/gnu/c-errors.o \
./osprey/kgccfe/gnu/c-format.o \
./osprey/kgccfe/gnu/c-lang.o \
./osprey/kgccfe/gnu/c-lex.o \
./osprey/kgccfe/gnu/c-objc-common.o \
./osprey/kgccfe/gnu/c-opts.o \
./osprey/kgccfe/gnu/c-pragma.o \
./osprey/kgccfe/gnu/c-pretty-print.o \
./osprey/kgccfe/gnu/c-semantics.o \
./osprey/kgccfe/gnu/c-typeck.o \
./osprey/kgccfe/gnu/caller-save.o \
./osprey/kgccfe/gnu/calls.o \
./osprey/kgccfe/gnu/cfg.o \
./osprey/kgccfe/gnu/cfganal.o \
./osprey/kgccfe/gnu/cfgbuild.o \
./osprey/kgccfe/gnu/cfgcleanup.o \
./osprey/kgccfe/gnu/cfglayout.o \
./osprey/kgccfe/gnu/cfgloop.o \
./osprey/kgccfe/gnu/cfgrtl.o \
./osprey/kgccfe/gnu/collect2.o \
./osprey/kgccfe/gnu/combine.o \
./osprey/kgccfe/gnu/conflict.o \
./osprey/kgccfe/gnu/convert.o \
./osprey/kgccfe/gnu/cppdefault.o \
./osprey/kgccfe/gnu/cpperror.o \
./osprey/kgccfe/gnu/cppexp.o \
./osprey/kgccfe/gnu/cppfiles.o \
./osprey/kgccfe/gnu/cpphash.o \
./osprey/kgccfe/gnu/cppinit.o \
./osprey/kgccfe/gnu/cpplex.o \
./osprey/kgccfe/gnu/cpplib.o \
./osprey/kgccfe/gnu/cppmacro.o \
./osprey/kgccfe/gnu/cppmain.o \
./osprey/kgccfe/gnu/cppspec.o \
./osprey/kgccfe/gnu/cpptrad.o \
./osprey/kgccfe/gnu/crtstuff.o \
./osprey/kgccfe/gnu/cse.o \
./osprey/kgccfe/gnu/cselib.o \
./osprey/kgccfe/gnu/dbxout.o \
./osprey/kgccfe/gnu/debug.o \
./osprey/kgccfe/gnu/dependence.o \
./osprey/kgccfe/gnu/df.o \
./osprey/kgccfe/gnu/diagnostic.o \
./osprey/kgccfe/gnu/doloop.o \
./osprey/kgccfe/gnu/dominance.o \
./osprey/kgccfe/gnu/doschk.o \
./osprey/kgccfe/gnu/dummy-conditions.o \
./osprey/kgccfe/gnu/dwarf2asm.o \
./osprey/kgccfe/gnu/dwarf2out.o \
./osprey/kgccfe/gnu/dwarfout.o \
./osprey/kgccfe/gnu/emit-rtl.o \
./osprey/kgccfe/gnu/enquire.o \
./osprey/kgccfe/gnu/errors.o \
./osprey/kgccfe/gnu/et-forest.o \
./osprey/kgccfe/gnu/except.o \
./osprey/kgccfe/gnu/explow.o \
./osprey/kgccfe/gnu/expmed.o \
./osprey/kgccfe/gnu/expr.o \
./osprey/kgccfe/gnu/final.o \
./osprey/kgccfe/gnu/fix-header.o \
./osprey/kgccfe/gnu/floatlib.o \
./osprey/kgccfe/gnu/flow.o \
./osprey/kgccfe/gnu/fold-const.o \
./osprey/kgccfe/gnu/fp-test.o \
./osprey/kgccfe/gnu/function.o \
./osprey/kgccfe/gnu/gcc.o \
./osprey/kgccfe/gnu/gccspec.o \
./osprey/kgccfe/gnu/gcov.o \
./osprey/kgccfe/gnu/gcse.o \
./osprey/kgccfe/gnu/gen-protos.o \
./osprey/kgccfe/gnu/genattr.o \
./osprey/kgccfe/gnu/genattrtab.o \
./osprey/kgccfe/gnu/genautomata.o \
./osprey/kgccfe/gnu/gencheck.o \
./osprey/kgccfe/gnu/gencodes.o \
./osprey/kgccfe/gnu/genconditions.o \
./osprey/kgccfe/gnu/genconfig.o \
./osprey/kgccfe/gnu/genconstants.o \
./osprey/kgccfe/gnu/genemit.o \
./osprey/kgccfe/gnu/genextract.o \
./osprey/kgccfe/gnu/genflags.o \
./osprey/kgccfe/gnu/gengenrtl.o \
./osprey/kgccfe/gnu/gengtype.o \
./osprey/kgccfe/gnu/genopinit.o \
./osprey/kgccfe/gnu/genoutput.o \
./osprey/kgccfe/gnu/genpeep.o \
./osprey/kgccfe/gnu/genpreds.o \
./osprey/kgccfe/gnu/genrecog.o \
./osprey/kgccfe/gnu/gensupport.o \
./osprey/kgccfe/gnu/ggc-callbacks.o \
./osprey/kgccfe/gnu/ggc-common.o \
./osprey/kgccfe/gnu/ggc-none.o \
./osprey/kgccfe/gnu/ggc-page.o \
./osprey/kgccfe/gnu/ggc-simple.o \
./osprey/kgccfe/gnu/global.o \
./osprey/kgccfe/gnu/gmon.o \
./osprey/kgccfe/gnu/graph.o \
./osprey/kgccfe/gnu/haifa-sched.o \
./osprey/kgccfe/gnu/halfpic.o \
./osprey/kgccfe/gnu/hash.o \
./osprey/kgccfe/gnu/hashtable.o \
./osprey/kgccfe/gnu/hooks.o \
./osprey/kgccfe/gnu/ifcvt.o \
./osprey/kgccfe/gnu/integrate.o \
./osprey/kgccfe/gnu/intl.o \
./osprey/kgccfe/gnu/jump.o \
./osprey/kgccfe/gnu/langhooks.o \
./osprey/kgccfe/gnu/lcm.o \
./osprey/kgccfe/gnu/libgcc2.o \
./osprey/kgccfe/gnu/line-map.o \
./osprey/kgccfe/gnu/lists.o \
./osprey/kgccfe/gnu/local-alloc.o \
./osprey/kgccfe/gnu/loop.o \
./osprey/kgccfe/gnu/main.o \
./osprey/kgccfe/gnu/mbchar.o \
./osprey/kgccfe/gnu/mips-tdump.o \
./osprey/kgccfe/gnu/mips-tfile.o \
./osprey/kgccfe/gnu/mips.o \
./osprey/kgccfe/gnu/mkdeps.o \
./osprey/kgccfe/gnu/optabs.o \
./osprey/kgccfe/gnu/params.o \
./osprey/kgccfe/gnu/predict.o \
./osprey/kgccfe/gnu/prefix.o \
./osprey/kgccfe/gnu/print-rtl.o \
./osprey/kgccfe/gnu/print-tree.o \
./osprey/kgccfe/gnu/profile.o \
./osprey/kgccfe/gnu/protoize.o \
./osprey/kgccfe/gnu/ra-build.o \
./osprey/kgccfe/gnu/ra-colorize.o \
./osprey/kgccfe/gnu/ra-debug.o \
./osprey/kgccfe/gnu/ra-rewrite.o \
./osprey/kgccfe/gnu/ra.o \
./osprey/kgccfe/gnu/read-rtl.o \
./osprey/kgccfe/gnu/real.o \
./osprey/kgccfe/gnu/recog.o \
./osprey/kgccfe/gnu/reg-stack.o \
./osprey/kgccfe/gnu/regclass.o \
./osprey/kgccfe/gnu/regmove.o \
./osprey/kgccfe/gnu/regrename.o \
./osprey/kgccfe/gnu/reload.o \
./osprey/kgccfe/gnu/reload1.o \
./osprey/kgccfe/gnu/reorg.o \
./osprey/kgccfe/gnu/resource.o \
./osprey/kgccfe/gnu/rtl-error.o \
./osprey/kgccfe/gnu/rtl.o \
./osprey/kgccfe/gnu/rtlanal.o \
./osprey/kgccfe/gnu/sbitmap.o \
./osprey/kgccfe/gnu/scan-decls.o \
./osprey/kgccfe/gnu/scan.o \
./osprey/kgccfe/gnu/sched-deps.o \
./osprey/kgccfe/gnu/sched-ebb.o \
./osprey/kgccfe/gnu/sched-rgn.o \
./osprey/kgccfe/gnu/sched-vis.o \
./osprey/kgccfe/gnu/sdbout.o \
./osprey/kgccfe/gnu/sibcall.o \
./osprey/kgccfe/gnu/simplify-rtx.o \
./osprey/kgccfe/gnu/ssa-ccp.o \
./osprey/kgccfe/gnu/ssa-dce.o \
./osprey/kgccfe/gnu/ssa.o \
./osprey/kgccfe/gnu/stmt.o \
./osprey/kgccfe/gnu/stor-layout.o \
./osprey/kgccfe/gnu/stringpool.o \
./osprey/kgccfe/gnu/timevar.o \
./osprey/kgccfe/gnu/tlink.o \
./osprey/kgccfe/gnu/toplev.o \
./osprey/kgccfe/gnu/tracer.o \
./osprey/kgccfe/gnu/tradcpp.o \
./osprey/kgccfe/gnu/tree-dump.o \
./osprey/kgccfe/gnu/tree-inline.o \
./osprey/kgccfe/gnu/tree.o \
./osprey/kgccfe/gnu/unroll.o \
./osprey/kgccfe/gnu/unwind-c.o \
./osprey/kgccfe/gnu/unwind-dw2-fde-darwin.o \
./osprey/kgccfe/gnu/unwind-dw2-fde-glibc.o \
./osprey/kgccfe/gnu/unwind-dw2-fde.o \
./osprey/kgccfe/gnu/unwind-dw2.o \
./osprey/kgccfe/gnu/unwind-sjlj.o \
./osprey/kgccfe/gnu/varasm.o \
./osprey/kgccfe/gnu/varray.o \
./osprey/kgccfe/gnu/version.o \
./osprey/kgccfe/gnu/vmsdbgout.o \
./osprey/kgccfe/gnu/xcoffout.o \
./osprey/kgccfe/gnu/y.tab.o 

C_DEPS += \
./osprey/kgccfe/gnu/alias.d \
./osprey/kgccfe/gnu/attribs.d \
./osprey/kgccfe/gnu/bb-reorder.d \
./osprey/kgccfe/gnu/bitmap.d \
./osprey/kgccfe/gnu/builtins.d \
./osprey/kgccfe/gnu/c-aux-info.d \
./osprey/kgccfe/gnu/c-common.d \
./osprey/kgccfe/gnu/c-convert.d \
./osprey/kgccfe/gnu/c-decl.d \
./osprey/kgccfe/gnu/c-dump.d \
./osprey/kgccfe/gnu/c-errors.d \
./osprey/kgccfe/gnu/c-format.d \
./osprey/kgccfe/gnu/c-lang.d \
./osprey/kgccfe/gnu/c-lex.d \
./osprey/kgccfe/gnu/c-objc-common.d \
./osprey/kgccfe/gnu/c-opts.d \
./osprey/kgccfe/gnu/c-pragma.d \
./osprey/kgccfe/gnu/c-pretty-print.d \
./osprey/kgccfe/gnu/c-semantics.d \
./osprey/kgccfe/gnu/c-typeck.d \
./osprey/kgccfe/gnu/caller-save.d \
./osprey/kgccfe/gnu/calls.d \
./osprey/kgccfe/gnu/cfg.d \
./osprey/kgccfe/gnu/cfganal.d \
./osprey/kgccfe/gnu/cfgbuild.d \
./osprey/kgccfe/gnu/cfgcleanup.d \
./osprey/kgccfe/gnu/cfglayout.d \
./osprey/kgccfe/gnu/cfgloop.d \
./osprey/kgccfe/gnu/cfgrtl.d \
./osprey/kgccfe/gnu/collect2.d \
./osprey/kgccfe/gnu/combine.d \
./osprey/kgccfe/gnu/conflict.d \
./osprey/kgccfe/gnu/convert.d \
./osprey/kgccfe/gnu/cppdefault.d \
./osprey/kgccfe/gnu/cpperror.d \
./osprey/kgccfe/gnu/cppexp.d \
./osprey/kgccfe/gnu/cppfiles.d \
./osprey/kgccfe/gnu/cpphash.d \
./osprey/kgccfe/gnu/cppinit.d \
./osprey/kgccfe/gnu/cpplex.d \
./osprey/kgccfe/gnu/cpplib.d \
./osprey/kgccfe/gnu/cppmacro.d \
./osprey/kgccfe/gnu/cppmain.d \
./osprey/kgccfe/gnu/cppspec.d \
./osprey/kgccfe/gnu/cpptrad.d \
./osprey/kgccfe/gnu/crtstuff.d \
./osprey/kgccfe/gnu/cse.d \
./osprey/kgccfe/gnu/cselib.d \
./osprey/kgccfe/gnu/dbxout.d \
./osprey/kgccfe/gnu/debug.d \
./osprey/kgccfe/gnu/dependence.d \
./osprey/kgccfe/gnu/df.d \
./osprey/kgccfe/gnu/diagnostic.d \
./osprey/kgccfe/gnu/doloop.d \
./osprey/kgccfe/gnu/dominance.d \
./osprey/kgccfe/gnu/doschk.d \
./osprey/kgccfe/gnu/dummy-conditions.d \
./osprey/kgccfe/gnu/dwarf2asm.d \
./osprey/kgccfe/gnu/dwarf2out.d \
./osprey/kgccfe/gnu/dwarfout.d \
./osprey/kgccfe/gnu/emit-rtl.d \
./osprey/kgccfe/gnu/enquire.d \
./osprey/kgccfe/gnu/errors.d \
./osprey/kgccfe/gnu/et-forest.d \
./osprey/kgccfe/gnu/except.d \
./osprey/kgccfe/gnu/explow.d \
./osprey/kgccfe/gnu/expmed.d \
./osprey/kgccfe/gnu/expr.d \
./osprey/kgccfe/gnu/final.d \
./osprey/kgccfe/gnu/fix-header.d \
./osprey/kgccfe/gnu/floatlib.d \
./osprey/kgccfe/gnu/flow.d \
./osprey/kgccfe/gnu/fold-const.d \
./osprey/kgccfe/gnu/fp-test.d \
./osprey/kgccfe/gnu/function.d \
./osprey/kgccfe/gnu/gcc.d \
./osprey/kgccfe/gnu/gccspec.d \
./osprey/kgccfe/gnu/gcov.d \
./osprey/kgccfe/gnu/gcse.d \
./osprey/kgccfe/gnu/gen-protos.d \
./osprey/kgccfe/gnu/genattr.d \
./osprey/kgccfe/gnu/genattrtab.d \
./osprey/kgccfe/gnu/genautomata.d \
./osprey/kgccfe/gnu/gencheck.d \
./osprey/kgccfe/gnu/gencodes.d \
./osprey/kgccfe/gnu/genconditions.d \
./osprey/kgccfe/gnu/genconfig.d \
./osprey/kgccfe/gnu/genconstants.d \
./osprey/kgccfe/gnu/genemit.d \
./osprey/kgccfe/gnu/genextract.d \
./osprey/kgccfe/gnu/genflags.d \
./osprey/kgccfe/gnu/gengenrtl.d \
./osprey/kgccfe/gnu/gengtype.d \
./osprey/kgccfe/gnu/genopinit.d \
./osprey/kgccfe/gnu/genoutput.d \
./osprey/kgccfe/gnu/genpeep.d \
./osprey/kgccfe/gnu/genpreds.d \
./osprey/kgccfe/gnu/genrecog.d \
./osprey/kgccfe/gnu/gensupport.d \
./osprey/kgccfe/gnu/ggc-callbacks.d \
./osprey/kgccfe/gnu/ggc-common.d \
./osprey/kgccfe/gnu/ggc-none.d \
./osprey/kgccfe/gnu/ggc-page.d \
./osprey/kgccfe/gnu/ggc-simple.d \
./osprey/kgccfe/gnu/global.d \
./osprey/kgccfe/gnu/gmon.d \
./osprey/kgccfe/gnu/graph.d \
./osprey/kgccfe/gnu/haifa-sched.d \
./osprey/kgccfe/gnu/halfpic.d \
./osprey/kgccfe/gnu/hash.d \
./osprey/kgccfe/gnu/hashtable.d \
./osprey/kgccfe/gnu/hooks.d \
./osprey/kgccfe/gnu/ifcvt.d \
./osprey/kgccfe/gnu/integrate.d \
./osprey/kgccfe/gnu/intl.d \
./osprey/kgccfe/gnu/jump.d \
./osprey/kgccfe/gnu/langhooks.d \
./osprey/kgccfe/gnu/lcm.d \
./osprey/kgccfe/gnu/libgcc2.d \
./osprey/kgccfe/gnu/line-map.d \
./osprey/kgccfe/gnu/lists.d \
./osprey/kgccfe/gnu/local-alloc.d \
./osprey/kgccfe/gnu/loop.d \
./osprey/kgccfe/gnu/main.d \
./osprey/kgccfe/gnu/mbchar.d \
./osprey/kgccfe/gnu/mips-tdump.d \
./osprey/kgccfe/gnu/mips-tfile.d \
./osprey/kgccfe/gnu/mips.d \
./osprey/kgccfe/gnu/mkdeps.d \
./osprey/kgccfe/gnu/optabs.d \
./osprey/kgccfe/gnu/params.d \
./osprey/kgccfe/gnu/predict.d \
./osprey/kgccfe/gnu/prefix.d \
./osprey/kgccfe/gnu/print-rtl.d \
./osprey/kgccfe/gnu/print-tree.d \
./osprey/kgccfe/gnu/profile.d \
./osprey/kgccfe/gnu/protoize.d \
./osprey/kgccfe/gnu/ra-build.d \
./osprey/kgccfe/gnu/ra-colorize.d \
./osprey/kgccfe/gnu/ra-debug.d \
./osprey/kgccfe/gnu/ra-rewrite.d \
./osprey/kgccfe/gnu/ra.d \
./osprey/kgccfe/gnu/read-rtl.d \
./osprey/kgccfe/gnu/real.d \
./osprey/kgccfe/gnu/recog.d \
./osprey/kgccfe/gnu/reg-stack.d \
./osprey/kgccfe/gnu/regclass.d \
./osprey/kgccfe/gnu/regmove.d \
./osprey/kgccfe/gnu/regrename.d \
./osprey/kgccfe/gnu/reload.d \
./osprey/kgccfe/gnu/reload1.d \
./osprey/kgccfe/gnu/reorg.d \
./osprey/kgccfe/gnu/resource.d \
./osprey/kgccfe/gnu/rtl-error.d \
./osprey/kgccfe/gnu/rtl.d \
./osprey/kgccfe/gnu/rtlanal.d \
./osprey/kgccfe/gnu/sbitmap.d \
./osprey/kgccfe/gnu/scan-decls.d \
./osprey/kgccfe/gnu/scan.d \
./osprey/kgccfe/gnu/sched-deps.d \
./osprey/kgccfe/gnu/sched-ebb.d \
./osprey/kgccfe/gnu/sched-rgn.d \
./osprey/kgccfe/gnu/sched-vis.d \
./osprey/kgccfe/gnu/sdbout.d \
./osprey/kgccfe/gnu/sibcall.d \
./osprey/kgccfe/gnu/simplify-rtx.d \
./osprey/kgccfe/gnu/ssa-ccp.d \
./osprey/kgccfe/gnu/ssa-dce.d \
./osprey/kgccfe/gnu/ssa.d \
./osprey/kgccfe/gnu/stmt.d \
./osprey/kgccfe/gnu/stor-layout.d \
./osprey/kgccfe/gnu/stringpool.d \
./osprey/kgccfe/gnu/timevar.d \
./osprey/kgccfe/gnu/tlink.d \
./osprey/kgccfe/gnu/toplev.d \
./osprey/kgccfe/gnu/tracer.d \
./osprey/kgccfe/gnu/tradcpp.d \
./osprey/kgccfe/gnu/tree-dump.d \
./osprey/kgccfe/gnu/tree-inline.d \
./osprey/kgccfe/gnu/tree.d \
./osprey/kgccfe/gnu/unroll.d \
./osprey/kgccfe/gnu/unwind-c.d \
./osprey/kgccfe/gnu/unwind-dw2-fde-darwin.d \
./osprey/kgccfe/gnu/unwind-dw2-fde-glibc.d \
./osprey/kgccfe/gnu/unwind-dw2-fde.d \
./osprey/kgccfe/gnu/unwind-dw2.d \
./osprey/kgccfe/gnu/unwind-sjlj.d \
./osprey/kgccfe/gnu/varasm.d \
./osprey/kgccfe/gnu/varray.d \
./osprey/kgccfe/gnu/version.d \
./osprey/kgccfe/gnu/vmsdbgout.d \
./osprey/kgccfe/gnu/xcoffout.d \
./osprey/kgccfe/gnu/y.tab.d 


# Each subdirectory must supply rules for building sources it contributes
osprey/kgccfe/gnu/%.o: ../osprey/kgccfe/gnu/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


