################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../osprey/targdir/cg/annotations.o \
../osprey/targdir/cg/bb_list.o \
../osprey/targdir/cg/bb_map.o \
../osprey/targdir/cg/bblist.o \
../osprey/targdir/cg/bbutil.o \
../osprey/targdir/cg/bitset.o \
../osprey/targdir/cg/calls.o \
../osprey/targdir/cg/cflow.o \
../osprey/targdir/cg/cg.o \
../osprey/targdir/cg/cg_cflow.o \
../osprey/targdir/cg/cg_convert_x87.o \
../osprey/targdir/cg/cg_db_op.o \
../osprey/targdir/cg/cg_dep_graph.o \
../osprey/targdir/cg/cg_flags.o \
../osprey/targdir/cg/cg_flags_arch.o \
../osprey/targdir/cg/cg_gcov.o \
../osprey/targdir/cg/cg_loop.o \
../osprey/targdir/cg/cg_loop_mii.o \
../osprey/targdir/cg/cg_loop_recur.o \
../osprey/targdir/cg/cg_loop_scc.o \
../osprey/targdir/cg/cg_loop_scc_prop.o \
../osprey/targdir/cg/cg_misc.o \
../osprey/targdir/cg/cg_region.o \
../osprey/targdir/cg/cg_sched.o \
../osprey/targdir/cg/cg_sched_est.o \
../osprey/targdir/cg/cg_spill.o \
../osprey/targdir/cg/cg_swp.o \
../osprey/targdir/cg/cg_swp_allocator.o \
../osprey/targdir/cg/cg_swp_bundle.o \
../osprey/targdir/cg/cg_swp_emit.o \
../osprey/targdir/cg/cg_swp_sched.o \
../osprey/targdir/cg/cg_swp_target.o \
../osprey/targdir/cg/cg_thr.o \
../osprey/targdir/cg/cg_vector.o \
../osprey/targdir/cg/cgdriver.o \
../osprey/targdir/cg/cgdwarf.o \
../osprey/targdir/cg/cgdwarf_targ.o \
../osprey/targdir/cg/cgemit.o \
../osprey/targdir/cg/cgemit_targ.o \
../osprey/targdir/cg/cgexp.o \
../osprey/targdir/cg/cgprep.o \
../osprey/targdir/cg/cgtarget.o \
../osprey/targdir/cg/cio_rwtran.o \
../osprey/targdir/cg/comment.o \
../osprey/targdir/cg/cxx_memory.o \
../osprey/targdir/cg/dominate.o \
../osprey/targdir/cg/ebo.o \
../osprey/targdir/cg/ebo_special.o \
../osprey/targdir/cg/eh_region.o \
../osprey/targdir/cg/em_dwarf.o \
../osprey/targdir/cg/em_elf.o \
../osprey/targdir/cg/entry_exit_targ.o \
../osprey/targdir/cg/exp_branch.o \
../osprey/targdir/cg/exp_divrem.o \
../osprey/targdir/cg/exp_loadstore.o \
../osprey/targdir/cg/exp_predicate.o \
../osprey/targdir/cg/expand.o \
../osprey/targdir/cg/findloops.o \
../osprey/targdir/cg/freq.o \
../osprey/targdir/cg/gcm.o \
../osprey/targdir/cg/gra.o \
../osprey/targdir/cg/gra_bb.o \
../osprey/targdir/cg/gra_bb_list.o \
../osprey/targdir/cg/gra_cflow.o \
../osprey/targdir/cg/gra_color.o \
../osprey/targdir/cg/gra_create.o \
../osprey/targdir/cg/gra_grant.o \
../osprey/targdir/cg/gra_interfere.o \
../osprey/targdir/cg/gra_live.o \
../osprey/targdir/cg/gra_loop.o \
../osprey/targdir/cg/gra_lrange.o \
../osprey/targdir/cg/gra_lrange_subuniverse.o \
../osprey/targdir/cg/gra_lrange_vset.o \
../osprey/targdir/cg/gra_lunit.o \
../osprey/targdir/cg/gra_pref.o \
../osprey/targdir/cg/gra_region.o \
../osprey/targdir/cg/gra_spill.o \
../osprey/targdir/cg/gra_split.o \
../osprey/targdir/cg/gra_trace.o \
../osprey/targdir/cg/gtn_tn_set.o \
../osprey/targdir/cg/gtn_universe.o \
../osprey/targdir/cg/hb.o \
../osprey/targdir/cg/hb_block_select.o \
../osprey/targdir/cg/hb_cflow.o \
../osprey/targdir/cg/hb_hazards.o \
../osprey/targdir/cg/hb_id_candidates.o \
../osprey/targdir/cg/hb_if_convert.o \
../osprey/targdir/cg/hb_sched.o \
../osprey/targdir/cg/hb_tail_duplication.o \
../osprey/targdir/cg/hb_trace.o \
../osprey/targdir/cg/iface_scn.o \
../osprey/targdir/cg/igls.o \
../osprey/targdir/cg/init.o \
../osprey/targdir/cg/label_util.o \
../osprey/targdir/cg/localize.o \
../osprey/targdir/cg/lra.o \
../osprey/targdir/cg/lrange_list.o \
../osprey/targdir/cg/lrange_set.o \
../osprey/targdir/cg/note.o \
../osprey/targdir/cg/op_list.o \
../osprey/targdir/cg/op_map.o \
../osprey/targdir/cg/oputil.o \
../osprey/targdir/cg/pqs.o \
../osprey/targdir/cg/pqs_cg.o \
../osprey/targdir/cg/reg_live.o \
../osprey/targdir/cg/register.o \
../osprey/targdir/cg/register_targ.o \
../osprey/targdir/cg/st_list.o \
../osprey/targdir/cg/tag.o \
../osprey/targdir/cg/targ_em_const.o \
../osprey/targdir/cg/targ_em_dwarf.o \
../osprey/targdir/cg/targ_em_elf.o \
../osprey/targdir/cg/tn_list.o \
../osprey/targdir/cg/tn_map.o \
../osprey/targdir/cg/tn_prop.o \
../osprey/targdir/cg/tnutil.o \
../osprey/targdir/cg/variants.o \
../osprey/targdir/cg/void_list.o \
../osprey/targdir/cg/whirl2ops.o 


# Each subdirectory must supply rules for building sources it contributes

