################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../osprey/cygnus/opcodes/dis-buf.o \
../osprey/cygnus/opcodes/dis-init.o \
../osprey/cygnus/opcodes/disassemble.o \
../osprey/cygnus/opcodes/i386-dis.o 

C_SRCS += \
../osprey/cygnus/opcodes/a29k-dis.c \
../osprey/cygnus/opcodes/alpha-dis.c \
../osprey/cygnus/opcodes/alpha-opc.c \
../osprey/cygnus/opcodes/arc-dis.c \
../osprey/cygnus/opcodes/arc-ext.c \
../osprey/cygnus/opcodes/arc-opc.c \
../osprey/cygnus/opcodes/arm-dis.c \
../osprey/cygnus/opcodes/avr-dis.c \
../osprey/cygnus/opcodes/cgen-asm.c \
../osprey/cygnus/opcodes/cgen-dis.c \
../osprey/cygnus/opcodes/cgen-opc.c \
../osprey/cygnus/opcodes/cris-dis.c \
../osprey/cygnus/opcodes/cris-opc.c \
../osprey/cygnus/opcodes/d10v-dis.c \
../osprey/cygnus/opcodes/d10v-opc.c \
../osprey/cygnus/opcodes/d30v-dis.c \
../osprey/cygnus/opcodes/d30v-opc.c \
../osprey/cygnus/opcodes/dis-buf.c \
../osprey/cygnus/opcodes/dis-init.c \
../osprey/cygnus/opcodes/disassemble.c \
../osprey/cygnus/opcodes/dlx-dis.c \
../osprey/cygnus/opcodes/fr30-asm.c \
../osprey/cygnus/opcodes/fr30-desc.c \
../osprey/cygnus/opcodes/fr30-dis.c \
../osprey/cygnus/opcodes/fr30-ibld.c \
../osprey/cygnus/opcodes/fr30-opc.c \
../osprey/cygnus/opcodes/frv-asm.c \
../osprey/cygnus/opcodes/frv-desc.c \
../osprey/cygnus/opcodes/frv-dis.c \
../osprey/cygnus/opcodes/frv-ibld.c \
../osprey/cygnus/opcodes/frv-opc.c \
../osprey/cygnus/opcodes/h8300-dis.c \
../osprey/cygnus/opcodes/h8500-dis.c \
../osprey/cygnus/opcodes/hppa-dis.c \
../osprey/cygnus/opcodes/i370-dis.c \
../osprey/cygnus/opcodes/i370-opc.c \
../osprey/cygnus/opcodes/i386-dis.c \
../osprey/cygnus/opcodes/i860-dis.c \
../osprey/cygnus/opcodes/i960-dis.c \
../osprey/cygnus/opcodes/ia64-asmtab.c \
../osprey/cygnus/opcodes/ia64-dis.c \
../osprey/cygnus/opcodes/ia64-gen.c \
../osprey/cygnus/opcodes/ia64-opc-a.c \
../osprey/cygnus/opcodes/ia64-opc-b.c \
../osprey/cygnus/opcodes/ia64-opc-d.c \
../osprey/cygnus/opcodes/ia64-opc-f.c \
../osprey/cygnus/opcodes/ia64-opc-i.c \
../osprey/cygnus/opcodes/ia64-opc-m.c \
../osprey/cygnus/opcodes/ia64-opc-x.c \
../osprey/cygnus/opcodes/ia64-opc.c \
../osprey/cygnus/opcodes/ip2k-asm.c \
../osprey/cygnus/opcodes/ip2k-desc.c \
../osprey/cygnus/opcodes/ip2k-dis.c \
../osprey/cygnus/opcodes/ip2k-ibld.c \
../osprey/cygnus/opcodes/ip2k-opc.c \
../osprey/cygnus/opcodes/iq2000-asm.c \
../osprey/cygnus/opcodes/iq2000-desc.c \
../osprey/cygnus/opcodes/iq2000-dis.c \
../osprey/cygnus/opcodes/iq2000-ibld.c \
../osprey/cygnus/opcodes/iq2000-opc.c \
../osprey/cygnus/opcodes/m10200-dis.c \
../osprey/cygnus/opcodes/m10200-opc.c \
../osprey/cygnus/opcodes/m10300-dis.c \
../osprey/cygnus/opcodes/m10300-opc.c \
../osprey/cygnus/opcodes/m32r-asm.c \
../osprey/cygnus/opcodes/m32r-desc.c \
../osprey/cygnus/opcodes/m32r-dis.c \
../osprey/cygnus/opcodes/m32r-ibld.c \
../osprey/cygnus/opcodes/m32r-opc.c \
../osprey/cygnus/opcodes/m32r-opinst.c \
../osprey/cygnus/opcodes/m68hc11-dis.c \
../osprey/cygnus/opcodes/m68hc11-opc.c \
../osprey/cygnus/opcodes/m68k-dis.c \
../osprey/cygnus/opcodes/m68k-opc.c \
../osprey/cygnus/opcodes/m88k-dis.c \
../osprey/cygnus/opcodes/mcore-dis.c \
../osprey/cygnus/opcodes/mips-dis.c \
../osprey/cygnus/opcodes/mips-opc.c \
../osprey/cygnus/opcodes/mips16-opc.c \
../osprey/cygnus/opcodes/mmix-dis.c \
../osprey/cygnus/opcodes/mmix-opc.c \
../osprey/cygnus/opcodes/msp430-dis.c \
../osprey/cygnus/opcodes/ns32k-dis.c \
../osprey/cygnus/opcodes/openrisc-asm.c \
../osprey/cygnus/opcodes/openrisc-desc.c \
../osprey/cygnus/opcodes/openrisc-dis.c \
../osprey/cygnus/opcodes/openrisc-ibld.c \
../osprey/cygnus/opcodes/openrisc-opc.c \
../osprey/cygnus/opcodes/or32-dis.c \
../osprey/cygnus/opcodes/or32-opc.c \
../osprey/cygnus/opcodes/pdp11-dis.c \
../osprey/cygnus/opcodes/pdp11-opc.c \
../osprey/cygnus/opcodes/pj-dis.c \
../osprey/cygnus/opcodes/pj-opc.c \
../osprey/cygnus/opcodes/ppc-dis.c \
../osprey/cygnus/opcodes/ppc-opc.c \
../osprey/cygnus/opcodes/s390-dis.c \
../osprey/cygnus/opcodes/s390-mkopc.c \
../osprey/cygnus/opcodes/s390-opc.c \
../osprey/cygnus/opcodes/sh-dis.c \
../osprey/cygnus/opcodes/sh64-dis.c \
../osprey/cygnus/opcodes/sh64-opc.c \
../osprey/cygnus/opcodes/sparc-dis.c \
../osprey/cygnus/opcodes/sparc-opc.c \
../osprey/cygnus/opcodes/tic30-dis.c \
../osprey/cygnus/opcodes/tic4x-dis.c \
../osprey/cygnus/opcodes/tic54x-dis.c \
../osprey/cygnus/opcodes/tic54x-opc.c \
../osprey/cygnus/opcodes/tic80-dis.c \
../osprey/cygnus/opcodes/tic80-opc.c \
../osprey/cygnus/opcodes/v850-dis.c \
../osprey/cygnus/opcodes/v850-opc.c \
../osprey/cygnus/opcodes/vax-dis.c \
../osprey/cygnus/opcodes/w65-dis.c \
../osprey/cygnus/opcodes/xstormy16-asm.c \
../osprey/cygnus/opcodes/xstormy16-desc.c \
../osprey/cygnus/opcodes/xstormy16-dis.c \
../osprey/cygnus/opcodes/xstormy16-ibld.c \
../osprey/cygnus/opcodes/xstormy16-opc.c \
../osprey/cygnus/opcodes/xtensa-dis.c \
../osprey/cygnus/opcodes/z8k-dis.c \
../osprey/cygnus/opcodes/z8kgen.c 

OBJS += \
./osprey/cygnus/opcodes/a29k-dis.o \
./osprey/cygnus/opcodes/alpha-dis.o \
./osprey/cygnus/opcodes/alpha-opc.o \
./osprey/cygnus/opcodes/arc-dis.o \
./osprey/cygnus/opcodes/arc-ext.o \
./osprey/cygnus/opcodes/arc-opc.o \
./osprey/cygnus/opcodes/arm-dis.o \
./osprey/cygnus/opcodes/avr-dis.o \
./osprey/cygnus/opcodes/cgen-asm.o \
./osprey/cygnus/opcodes/cgen-dis.o \
./osprey/cygnus/opcodes/cgen-opc.o \
./osprey/cygnus/opcodes/cris-dis.o \
./osprey/cygnus/opcodes/cris-opc.o \
./osprey/cygnus/opcodes/d10v-dis.o \
./osprey/cygnus/opcodes/d10v-opc.o \
./osprey/cygnus/opcodes/d30v-dis.o \
./osprey/cygnus/opcodes/d30v-opc.o \
./osprey/cygnus/opcodes/dis-buf.o \
./osprey/cygnus/opcodes/dis-init.o \
./osprey/cygnus/opcodes/disassemble.o \
./osprey/cygnus/opcodes/dlx-dis.o \
./osprey/cygnus/opcodes/fr30-asm.o \
./osprey/cygnus/opcodes/fr30-desc.o \
./osprey/cygnus/opcodes/fr30-dis.o \
./osprey/cygnus/opcodes/fr30-ibld.o \
./osprey/cygnus/opcodes/fr30-opc.o \
./osprey/cygnus/opcodes/frv-asm.o \
./osprey/cygnus/opcodes/frv-desc.o \
./osprey/cygnus/opcodes/frv-dis.o \
./osprey/cygnus/opcodes/frv-ibld.o \
./osprey/cygnus/opcodes/frv-opc.o \
./osprey/cygnus/opcodes/h8300-dis.o \
./osprey/cygnus/opcodes/h8500-dis.o \
./osprey/cygnus/opcodes/hppa-dis.o \
./osprey/cygnus/opcodes/i370-dis.o \
./osprey/cygnus/opcodes/i370-opc.o \
./osprey/cygnus/opcodes/i386-dis.o \
./osprey/cygnus/opcodes/i860-dis.o \
./osprey/cygnus/opcodes/i960-dis.o \
./osprey/cygnus/opcodes/ia64-asmtab.o \
./osprey/cygnus/opcodes/ia64-dis.o \
./osprey/cygnus/opcodes/ia64-gen.o \
./osprey/cygnus/opcodes/ia64-opc-a.o \
./osprey/cygnus/opcodes/ia64-opc-b.o \
./osprey/cygnus/opcodes/ia64-opc-d.o \
./osprey/cygnus/opcodes/ia64-opc-f.o \
./osprey/cygnus/opcodes/ia64-opc-i.o \
./osprey/cygnus/opcodes/ia64-opc-m.o \
./osprey/cygnus/opcodes/ia64-opc-x.o \
./osprey/cygnus/opcodes/ia64-opc.o \
./osprey/cygnus/opcodes/ip2k-asm.o \
./osprey/cygnus/opcodes/ip2k-desc.o \
./osprey/cygnus/opcodes/ip2k-dis.o \
./osprey/cygnus/opcodes/ip2k-ibld.o \
./osprey/cygnus/opcodes/ip2k-opc.o \
./osprey/cygnus/opcodes/iq2000-asm.o \
./osprey/cygnus/opcodes/iq2000-desc.o \
./osprey/cygnus/opcodes/iq2000-dis.o \
./osprey/cygnus/opcodes/iq2000-ibld.o \
./osprey/cygnus/opcodes/iq2000-opc.o \
./osprey/cygnus/opcodes/m10200-dis.o \
./osprey/cygnus/opcodes/m10200-opc.o \
./osprey/cygnus/opcodes/m10300-dis.o \
./osprey/cygnus/opcodes/m10300-opc.o \
./osprey/cygnus/opcodes/m32r-asm.o \
./osprey/cygnus/opcodes/m32r-desc.o \
./osprey/cygnus/opcodes/m32r-dis.o \
./osprey/cygnus/opcodes/m32r-ibld.o \
./osprey/cygnus/opcodes/m32r-opc.o \
./osprey/cygnus/opcodes/m32r-opinst.o \
./osprey/cygnus/opcodes/m68hc11-dis.o \
./osprey/cygnus/opcodes/m68hc11-opc.o \
./osprey/cygnus/opcodes/m68k-dis.o \
./osprey/cygnus/opcodes/m68k-opc.o \
./osprey/cygnus/opcodes/m88k-dis.o \
./osprey/cygnus/opcodes/mcore-dis.o \
./osprey/cygnus/opcodes/mips-dis.o \
./osprey/cygnus/opcodes/mips-opc.o \
./osprey/cygnus/opcodes/mips16-opc.o \
./osprey/cygnus/opcodes/mmix-dis.o \
./osprey/cygnus/opcodes/mmix-opc.o \
./osprey/cygnus/opcodes/msp430-dis.o \
./osprey/cygnus/opcodes/ns32k-dis.o \
./osprey/cygnus/opcodes/openrisc-asm.o \
./osprey/cygnus/opcodes/openrisc-desc.o \
./osprey/cygnus/opcodes/openrisc-dis.o \
./osprey/cygnus/opcodes/openrisc-ibld.o \
./osprey/cygnus/opcodes/openrisc-opc.o \
./osprey/cygnus/opcodes/or32-dis.o \
./osprey/cygnus/opcodes/or32-opc.o \
./osprey/cygnus/opcodes/pdp11-dis.o \
./osprey/cygnus/opcodes/pdp11-opc.o \
./osprey/cygnus/opcodes/pj-dis.o \
./osprey/cygnus/opcodes/pj-opc.o \
./osprey/cygnus/opcodes/ppc-dis.o \
./osprey/cygnus/opcodes/ppc-opc.o \
./osprey/cygnus/opcodes/s390-dis.o \
./osprey/cygnus/opcodes/s390-mkopc.o \
./osprey/cygnus/opcodes/s390-opc.o \
./osprey/cygnus/opcodes/sh-dis.o \
./osprey/cygnus/opcodes/sh64-dis.o \
./osprey/cygnus/opcodes/sh64-opc.o \
./osprey/cygnus/opcodes/sparc-dis.o \
./osprey/cygnus/opcodes/sparc-opc.o \
./osprey/cygnus/opcodes/tic30-dis.o \
./osprey/cygnus/opcodes/tic4x-dis.o \
./osprey/cygnus/opcodes/tic54x-dis.o \
./osprey/cygnus/opcodes/tic54x-opc.o \
./osprey/cygnus/opcodes/tic80-dis.o \
./osprey/cygnus/opcodes/tic80-opc.o \
./osprey/cygnus/opcodes/v850-dis.o \
./osprey/cygnus/opcodes/v850-opc.o \
./osprey/cygnus/opcodes/vax-dis.o \
./osprey/cygnus/opcodes/w65-dis.o \
./osprey/cygnus/opcodes/xstormy16-asm.o \
./osprey/cygnus/opcodes/xstormy16-desc.o \
./osprey/cygnus/opcodes/xstormy16-dis.o \
./osprey/cygnus/opcodes/xstormy16-ibld.o \
./osprey/cygnus/opcodes/xstormy16-opc.o \
./osprey/cygnus/opcodes/xtensa-dis.o \
./osprey/cygnus/opcodes/z8k-dis.o \
./osprey/cygnus/opcodes/z8kgen.o 

C_DEPS += \
./osprey/cygnus/opcodes/a29k-dis.d \
./osprey/cygnus/opcodes/alpha-dis.d \
./osprey/cygnus/opcodes/alpha-opc.d \
./osprey/cygnus/opcodes/arc-dis.d \
./osprey/cygnus/opcodes/arc-ext.d \
./osprey/cygnus/opcodes/arc-opc.d \
./osprey/cygnus/opcodes/arm-dis.d \
./osprey/cygnus/opcodes/avr-dis.d \
./osprey/cygnus/opcodes/cgen-asm.d \
./osprey/cygnus/opcodes/cgen-dis.d \
./osprey/cygnus/opcodes/cgen-opc.d \
./osprey/cygnus/opcodes/cris-dis.d \
./osprey/cygnus/opcodes/cris-opc.d \
./osprey/cygnus/opcodes/d10v-dis.d \
./osprey/cygnus/opcodes/d10v-opc.d \
./osprey/cygnus/opcodes/d30v-dis.d \
./osprey/cygnus/opcodes/d30v-opc.d \
./osprey/cygnus/opcodes/dis-buf.d \
./osprey/cygnus/opcodes/dis-init.d \
./osprey/cygnus/opcodes/disassemble.d \
./osprey/cygnus/opcodes/dlx-dis.d \
./osprey/cygnus/opcodes/fr30-asm.d \
./osprey/cygnus/opcodes/fr30-desc.d \
./osprey/cygnus/opcodes/fr30-dis.d \
./osprey/cygnus/opcodes/fr30-ibld.d \
./osprey/cygnus/opcodes/fr30-opc.d \
./osprey/cygnus/opcodes/frv-asm.d \
./osprey/cygnus/opcodes/frv-desc.d \
./osprey/cygnus/opcodes/frv-dis.d \
./osprey/cygnus/opcodes/frv-ibld.d \
./osprey/cygnus/opcodes/frv-opc.d \
./osprey/cygnus/opcodes/h8300-dis.d \
./osprey/cygnus/opcodes/h8500-dis.d \
./osprey/cygnus/opcodes/hppa-dis.d \
./osprey/cygnus/opcodes/i370-dis.d \
./osprey/cygnus/opcodes/i370-opc.d \
./osprey/cygnus/opcodes/i386-dis.d \
./osprey/cygnus/opcodes/i860-dis.d \
./osprey/cygnus/opcodes/i960-dis.d \
./osprey/cygnus/opcodes/ia64-asmtab.d \
./osprey/cygnus/opcodes/ia64-dis.d \
./osprey/cygnus/opcodes/ia64-gen.d \
./osprey/cygnus/opcodes/ia64-opc-a.d \
./osprey/cygnus/opcodes/ia64-opc-b.d \
./osprey/cygnus/opcodes/ia64-opc-d.d \
./osprey/cygnus/opcodes/ia64-opc-f.d \
./osprey/cygnus/opcodes/ia64-opc-i.d \
./osprey/cygnus/opcodes/ia64-opc-m.d \
./osprey/cygnus/opcodes/ia64-opc-x.d \
./osprey/cygnus/opcodes/ia64-opc.d \
./osprey/cygnus/opcodes/ip2k-asm.d \
./osprey/cygnus/opcodes/ip2k-desc.d \
./osprey/cygnus/opcodes/ip2k-dis.d \
./osprey/cygnus/opcodes/ip2k-ibld.d \
./osprey/cygnus/opcodes/ip2k-opc.d \
./osprey/cygnus/opcodes/iq2000-asm.d \
./osprey/cygnus/opcodes/iq2000-desc.d \
./osprey/cygnus/opcodes/iq2000-dis.d \
./osprey/cygnus/opcodes/iq2000-ibld.d \
./osprey/cygnus/opcodes/iq2000-opc.d \
./osprey/cygnus/opcodes/m10200-dis.d \
./osprey/cygnus/opcodes/m10200-opc.d \
./osprey/cygnus/opcodes/m10300-dis.d \
./osprey/cygnus/opcodes/m10300-opc.d \
./osprey/cygnus/opcodes/m32r-asm.d \
./osprey/cygnus/opcodes/m32r-desc.d \
./osprey/cygnus/opcodes/m32r-dis.d \
./osprey/cygnus/opcodes/m32r-ibld.d \
./osprey/cygnus/opcodes/m32r-opc.d \
./osprey/cygnus/opcodes/m32r-opinst.d \
./osprey/cygnus/opcodes/m68hc11-dis.d \
./osprey/cygnus/opcodes/m68hc11-opc.d \
./osprey/cygnus/opcodes/m68k-dis.d \
./osprey/cygnus/opcodes/m68k-opc.d \
./osprey/cygnus/opcodes/m88k-dis.d \
./osprey/cygnus/opcodes/mcore-dis.d \
./osprey/cygnus/opcodes/mips-dis.d \
./osprey/cygnus/opcodes/mips-opc.d \
./osprey/cygnus/opcodes/mips16-opc.d \
./osprey/cygnus/opcodes/mmix-dis.d \
./osprey/cygnus/opcodes/mmix-opc.d \
./osprey/cygnus/opcodes/msp430-dis.d \
./osprey/cygnus/opcodes/ns32k-dis.d \
./osprey/cygnus/opcodes/openrisc-asm.d \
./osprey/cygnus/opcodes/openrisc-desc.d \
./osprey/cygnus/opcodes/openrisc-dis.d \
./osprey/cygnus/opcodes/openrisc-ibld.d \
./osprey/cygnus/opcodes/openrisc-opc.d \
./osprey/cygnus/opcodes/or32-dis.d \
./osprey/cygnus/opcodes/or32-opc.d \
./osprey/cygnus/opcodes/pdp11-dis.d \
./osprey/cygnus/opcodes/pdp11-opc.d \
./osprey/cygnus/opcodes/pj-dis.d \
./osprey/cygnus/opcodes/pj-opc.d \
./osprey/cygnus/opcodes/ppc-dis.d \
./osprey/cygnus/opcodes/ppc-opc.d \
./osprey/cygnus/opcodes/s390-dis.d \
./osprey/cygnus/opcodes/s390-mkopc.d \
./osprey/cygnus/opcodes/s390-opc.d \
./osprey/cygnus/opcodes/sh-dis.d \
./osprey/cygnus/opcodes/sh64-dis.d \
./osprey/cygnus/opcodes/sh64-opc.d \
./osprey/cygnus/opcodes/sparc-dis.d \
./osprey/cygnus/opcodes/sparc-opc.d \
./osprey/cygnus/opcodes/tic30-dis.d \
./osprey/cygnus/opcodes/tic4x-dis.d \
./osprey/cygnus/opcodes/tic54x-dis.d \
./osprey/cygnus/opcodes/tic54x-opc.d \
./osprey/cygnus/opcodes/tic80-dis.d \
./osprey/cygnus/opcodes/tic80-opc.d \
./osprey/cygnus/opcodes/v850-dis.d \
./osprey/cygnus/opcodes/v850-opc.d \
./osprey/cygnus/opcodes/vax-dis.d \
./osprey/cygnus/opcodes/w65-dis.d \
./osprey/cygnus/opcodes/xstormy16-asm.d \
./osprey/cygnus/opcodes/xstormy16-desc.d \
./osprey/cygnus/opcodes/xstormy16-dis.d \
./osprey/cygnus/opcodes/xstormy16-ibld.d \
./osprey/cygnus/opcodes/xstormy16-opc.d \
./osprey/cygnus/opcodes/xtensa-dis.d \
./osprey/cygnus/opcodes/z8k-dis.d \
./osprey/cygnus/opcodes/z8kgen.d 


# Each subdirectory must supply rules for building sources it contributes
osprey/cygnus/opcodes/%.o: ../osprey/cygnus/opcodes/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


