################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../osprey/libu/ffio/_ffopen.c \
../osprey/libu/ffio/asgrls.c \
../osprey/libu/ffio/binhex.c \
../osprey/libu/ffio/blxfcntl.c \
../osprey/libu/ffio/blxopen.c \
../osprey/libu/ffio/blxread.c \
../osprey/libu/ffio/blxwrite.c \
../osprey/libu/ffio/ccaclearpg.c \
../osprey/libu/ffio/ccaclosdiag.c \
../osprey/libu/ffio/ccaclose.c \
../osprey/libu/ffio/ccadmpcache.c \
../osprey/libu/ffio/ccafcntl.c \
../osprey/libu/ffio/ccaflush.c \
../osprey/libu/ffio/ccagetblk.c \
../osprey/libu/ffio/ccagetblkp.c \
../osprey/libu/ffio/ccalistio.c \
../osprey/libu/ffio/ccaopen.c \
../osprey/libu/ffio/ccardabuf.c \
../osprey/libu/ffio/ccaread.c \
../osprey/libu/ffio/ccareada.c \
../osprey/libu/ffio/ccaseek.c \
../osprey/libu/ffio/ccasyncpage.c \
../osprey/libu/ffio/ccatracker.c \
../osprey/libu/ffio/ccaweod.c \
../osprey/libu/ffio/ccawrabuf.c \
../osprey/libu/ffio/ccawrite.c \
../osprey/libu/ffio/ccawritea.c \
../osprey/libu/ffio/cchclose.c \
../osprey/libu/ffio/cchfcntl.c \
../osprey/libu/ffio/cchgetblk.c \
../osprey/libu/ffio/cchopen.c \
../osprey/libu/ffio/cchrdabuf.c \
../osprey/libu/ffio/cchread.c \
../osprey/libu/ffio/cchseek.c \
../osprey/libu/ffio/cchweod.c \
../osprey/libu/ffio/cchwrabuf.c \
../osprey/libu/ffio/cchwrite.c \
../osprey/libu/ffio/cdcfcntl.c \
../osprey/libu/ffio/cdcopen.c \
../osprey/libu/ffio/cdcread.c \
../osprey/libu/ffio/cdcwrite.c \
../osprey/libu/ffio/class_mr_sds_check.c \
../osprey/libu/ffio/class_vf_check.c \
../osprey/libu/ffio/class_vms_check.c \
../osprey/libu/ffio/cmpclose.c \
../osprey/libu/ffio/cmpfcntl.c \
../osprey/libu/ffio/cmplz.c \
../osprey/libu/ffio/cmpopen.c \
../osprey/libu/ffio/cmppos.c \
../osprey/libu/ffio/cmpread.c \
../osprey/libu/ffio/cmptrace.c \
../osprey/libu/ffio/cmpwrite.c \
../osprey/libu/ffio/convertc.c \
../osprey/libu/ffio/cosbksp.c \
../osprey/libu/ffio/cosclose.c \
../osprey/libu/ffio/cosfcntl.c \
../osprey/libu/ffio/cosopen.c \
../osprey/libu/ffio/cospos.c \
../osprey/libu/ffio/cosread.c \
../osprey/libu/ffio/cosseek.c \
../osprey/libu/ffio/coswrite.c \
../osprey/libu/ffio/errlist.c \
../osprey/libu/ffio/evnt_close_diags.c \
../osprey/libu/ffio/evnt_get_parent_child.c \
../osprey/libu/ffio/evnt_get_tracker.c \
../osprey/libu/ffio/evnt_trace_flush.c \
../osprey/libu/ffio/evntatexit.c \
../osprey/libu/ffio/evntbksp.c \
../osprey/libu/ffio/evntclose.c \
../osprey/libu/ffio/evntfcntl.c \
../osprey/libu/ffio/evntflush.c \
../osprey/libu/ffio/evntlistio.c \
../osprey/libu/ffio/evntopen.c \
../osprey/libu/ffio/evntread.c \
../osprey/libu/ffio/evntreada.c \
../osprey/libu/ffio/evntreadc.c \
../osprey/libu/ffio/evntseek.c \
../osprey/libu/ffio/evntweod.c \
../osprey/libu/ffio/evntweof.c \
../osprey/libu/ffio/evntwrite.c \
../osprey/libu/ffio/evntwritea.c \
../osprey/libu/ffio/evntwritec.c \
../osprey/libu/ffio/f77bksp.c \
../osprey/libu/ffio/f77close.c \
../osprey/libu/ffio/f77fcntl.c \
../osprey/libu/ffio/f77open.c \
../osprey/libu/ffio/f77read.c \
../osprey/libu/ffio/f77write.c \
../osprey/libu/ffio/fd_open.c \
../osprey/libu/ffio/ffbksp.c \
../osprey/libu/ffio/ffclose.c \
../osprey/libu/ffio/fferr.c \
../osprey/libu/ffio/fffcntl.c \
../osprey/libu/ffio/ffflush.c \
../osprey/libu/ffio/ffiolock.c \
../osprey/libu/ffio/fflistio.c \
../osprey/libu/ffio/ffnoop.c \
../osprey/libu/ffio/ffopen.c \
../osprey/libu/ffio/ffopens.c \
../osprey/libu/ffio/ffopensg.c \
../osprey/libu/ffio/ffpos.c \
../osprey/libu/ffio/ffread.c \
../osprey/libu/ffio/ffreada.c \
../osprey/libu/ffio/ffreadc.c \
../osprey/libu/ffio/ffseek.c \
../osprey/libu/ffio/ffspec.c \
../osprey/libu/ffio/ffstrerror.c \
../osprey/libu/ffio/ffweof.c \
../osprey/libu/ffio/ffwrite.c \
../osprey/libu/ffio/ffwritea.c \
../osprey/libu/ffio/ffwritec.c \
../osprey/libu/ffio/fssfcntl.c \
../osprey/libu/ffio/fssovfl.c \
../osprey/libu/ffio/fxrmain.c \
../osprey/libu/ffio/fxrmisc.c \
../osprey/libu/ffio/gfdc.c \
../osprey/libu/ffio/gffcntl.c \
../osprey/libu/ffio/gfopen.c \
../osprey/libu/ffio/gfread.c \
../osprey/libu/ffio/gfwrite.c \
../osprey/libu/ffio/globall.c \
../osprey/libu/ffio/globfcntl.c \
../osprey/libu/ffio/globgrmpi.c \
../osprey/libu/ffio/globgrshmem.c \
../osprey/libu/ffio/globopen.c \
../osprey/libu/ffio/globutil.c \
../osprey/libu/ffio/gvfcntl.c \
../osprey/libu/ffio/gvopen.c \
../osprey/libu/ffio/gvread.c \
../osprey/libu/ffio/gvwrite.c \
../osprey/libu/ffio/gxbksp.c \
../osprey/libu/ffio/gxfcntl.c \
../osprey/libu/ffio/gxopen.c \
../osprey/libu/ffio/gxread.c \
../osprey/libu/ffio/gxwrite.c \
../osprey/libu/ffio/lockclose.c \
../osprey/libu/ffio/lockfcntl.c \
../osprey/libu/ffio/locklistio.c \
../osprey/libu/ffio/lockopen.c \
../osprey/libu/ffio/lockpos.c \
../osprey/libu/ffio/lockread.c \
../osprey/libu/ffio/lockwrite.c \
../osprey/libu/ffio/mrclose.c \
../osprey/libu/ffio/mrgrow.c \
../osprey/libu/ffio/mropen.c \
../osprey/libu/ffio/mrread.c \
../osprey/libu/ffio/mrset.c \
../osprey/libu/ffio/mrwrite.c \
../osprey/libu/ffio/parse_data.c \
../osprey/libu/ffio/sectorsize.c \
../osprey/libu/ffio/set_layer_options.c \
../osprey/libu/ffio/sqbclose.c \
../osprey/libu/ffio/sqbfcntl.c \
../osprey/libu/ffio/sqbopen.c \
../osprey/libu/ffio/sqbpos.c \
../osprey/libu/ffio/sqbread.c \
../osprey/libu/ffio/sqbseek.c \
../osprey/libu/ffio/sqbweod.c \
../osprey/libu/ffio/sqbweof.c \
../osprey/libu/ffio/sqbwrite.c \
../osprey/libu/ffio/sysasg.c \
../osprey/libu/ffio/sysclose.c \
../osprey/libu/ffio/sysfcntl.c \
../osprey/libu/ffio/syslistio.c \
../osprey/libu/ffio/syslseek.c \
../osprey/libu/ffio/sysopen.c \
../osprey/libu/ffio/sysread.c \
../osprey/libu/ffio/sysreada.c \
../osprey/libu/ffio/systrunc.c \
../osprey/libu/ffio/syswrite.c \
../osprey/libu/ffio/syswritea.c \
../osprey/libu/ffio/tmfbksp.c \
../osprey/libu/ffio/tmfclose.c \
../osprey/libu/ffio/tmfclosev.c \
../osprey/libu/ffio/tmfeov.c \
../osprey/libu/ffio/tmffcntl.c \
../osprey/libu/ffio/tmfgtpos.c \
../osprey/libu/ffio/tmfopen.c \
../osprey/libu/ffio/tmfpos.c \
../osprey/libu/ffio/tmfread.c \
../osprey/libu/ffio/tmfseek.c \
../osprey/libu/ffio/tmfskipf.c \
../osprey/libu/ffio/tmfstpos.c \
../osprey/libu/ffio/tmftptsi.c \
../osprey/libu/ffio/tmfwrite.c \
../osprey/libu/ffio/trcbksp.c \
../osprey/libu/ffio/trcclose.c \
../osprey/libu/ffio/trcfcntl.c \
../osprey/libu/ffio/trclistio.c \
../osprey/libu/ffio/trcopen.c \
../osprey/libu/ffio/trcpos.c \
../osprey/libu/ffio/trcprint.c \
../osprey/libu/ffio/trcread.c \
../osprey/libu/ffio/trcwrite.c \
../osprey/libu/ffio/txtbksp.c \
../osprey/libu/ffio/txtfcntl.c \
../osprey/libu/ffio/txtopen.c \
../osprey/libu/ffio/txtread.c \
../osprey/libu/ffio/txtwrite.c \
../osprey/libu/ffio/xrtrace.c 

OBJS += \
./osprey/libu/ffio/_ffopen.o \
./osprey/libu/ffio/asgrls.o \
./osprey/libu/ffio/binhex.o \
./osprey/libu/ffio/blxfcntl.o \
./osprey/libu/ffio/blxopen.o \
./osprey/libu/ffio/blxread.o \
./osprey/libu/ffio/blxwrite.o \
./osprey/libu/ffio/ccaclearpg.o \
./osprey/libu/ffio/ccaclosdiag.o \
./osprey/libu/ffio/ccaclose.o \
./osprey/libu/ffio/ccadmpcache.o \
./osprey/libu/ffio/ccafcntl.o \
./osprey/libu/ffio/ccaflush.o \
./osprey/libu/ffio/ccagetblk.o \
./osprey/libu/ffio/ccagetblkp.o \
./osprey/libu/ffio/ccalistio.o \
./osprey/libu/ffio/ccaopen.o \
./osprey/libu/ffio/ccardabuf.o \
./osprey/libu/ffio/ccaread.o \
./osprey/libu/ffio/ccareada.o \
./osprey/libu/ffio/ccaseek.o \
./osprey/libu/ffio/ccasyncpage.o \
./osprey/libu/ffio/ccatracker.o \
./osprey/libu/ffio/ccaweod.o \
./osprey/libu/ffio/ccawrabuf.o \
./osprey/libu/ffio/ccawrite.o \
./osprey/libu/ffio/ccawritea.o \
./osprey/libu/ffio/cchclose.o \
./osprey/libu/ffio/cchfcntl.o \
./osprey/libu/ffio/cchgetblk.o \
./osprey/libu/ffio/cchopen.o \
./osprey/libu/ffio/cchrdabuf.o \
./osprey/libu/ffio/cchread.o \
./osprey/libu/ffio/cchseek.o \
./osprey/libu/ffio/cchweod.o \
./osprey/libu/ffio/cchwrabuf.o \
./osprey/libu/ffio/cchwrite.o \
./osprey/libu/ffio/cdcfcntl.o \
./osprey/libu/ffio/cdcopen.o \
./osprey/libu/ffio/cdcread.o \
./osprey/libu/ffio/cdcwrite.o \
./osprey/libu/ffio/class_mr_sds_check.o \
./osprey/libu/ffio/class_vf_check.o \
./osprey/libu/ffio/class_vms_check.o \
./osprey/libu/ffio/cmpclose.o \
./osprey/libu/ffio/cmpfcntl.o \
./osprey/libu/ffio/cmplz.o \
./osprey/libu/ffio/cmpopen.o \
./osprey/libu/ffio/cmppos.o \
./osprey/libu/ffio/cmpread.o \
./osprey/libu/ffio/cmptrace.o \
./osprey/libu/ffio/cmpwrite.o \
./osprey/libu/ffio/convertc.o \
./osprey/libu/ffio/cosbksp.o \
./osprey/libu/ffio/cosclose.o \
./osprey/libu/ffio/cosfcntl.o \
./osprey/libu/ffio/cosopen.o \
./osprey/libu/ffio/cospos.o \
./osprey/libu/ffio/cosread.o \
./osprey/libu/ffio/cosseek.o \
./osprey/libu/ffio/coswrite.o \
./osprey/libu/ffio/errlist.o \
./osprey/libu/ffio/evnt_close_diags.o \
./osprey/libu/ffio/evnt_get_parent_child.o \
./osprey/libu/ffio/evnt_get_tracker.o \
./osprey/libu/ffio/evnt_trace_flush.o \
./osprey/libu/ffio/evntatexit.o \
./osprey/libu/ffio/evntbksp.o \
./osprey/libu/ffio/evntclose.o \
./osprey/libu/ffio/evntfcntl.o \
./osprey/libu/ffio/evntflush.o \
./osprey/libu/ffio/evntlistio.o \
./osprey/libu/ffio/evntopen.o \
./osprey/libu/ffio/evntread.o \
./osprey/libu/ffio/evntreada.o \
./osprey/libu/ffio/evntreadc.o \
./osprey/libu/ffio/evntseek.o \
./osprey/libu/ffio/evntweod.o \
./osprey/libu/ffio/evntweof.o \
./osprey/libu/ffio/evntwrite.o \
./osprey/libu/ffio/evntwritea.o \
./osprey/libu/ffio/evntwritec.o \
./osprey/libu/ffio/f77bksp.o \
./osprey/libu/ffio/f77close.o \
./osprey/libu/ffio/f77fcntl.o \
./osprey/libu/ffio/f77open.o \
./osprey/libu/ffio/f77read.o \
./osprey/libu/ffio/f77write.o \
./osprey/libu/ffio/fd_open.o \
./osprey/libu/ffio/ffbksp.o \
./osprey/libu/ffio/ffclose.o \
./osprey/libu/ffio/fferr.o \
./osprey/libu/ffio/fffcntl.o \
./osprey/libu/ffio/ffflush.o \
./osprey/libu/ffio/ffiolock.o \
./osprey/libu/ffio/fflistio.o \
./osprey/libu/ffio/ffnoop.o \
./osprey/libu/ffio/ffopen.o \
./osprey/libu/ffio/ffopens.o \
./osprey/libu/ffio/ffopensg.o \
./osprey/libu/ffio/ffpos.o \
./osprey/libu/ffio/ffread.o \
./osprey/libu/ffio/ffreada.o \
./osprey/libu/ffio/ffreadc.o \
./osprey/libu/ffio/ffseek.o \
./osprey/libu/ffio/ffspec.o \
./osprey/libu/ffio/ffstrerror.o \
./osprey/libu/ffio/ffweof.o \
./osprey/libu/ffio/ffwrite.o \
./osprey/libu/ffio/ffwritea.o \
./osprey/libu/ffio/ffwritec.o \
./osprey/libu/ffio/fssfcntl.o \
./osprey/libu/ffio/fssovfl.o \
./osprey/libu/ffio/fxrmain.o \
./osprey/libu/ffio/fxrmisc.o \
./osprey/libu/ffio/gfdc.o \
./osprey/libu/ffio/gffcntl.o \
./osprey/libu/ffio/gfopen.o \
./osprey/libu/ffio/gfread.o \
./osprey/libu/ffio/gfwrite.o \
./osprey/libu/ffio/globall.o \
./osprey/libu/ffio/globfcntl.o \
./osprey/libu/ffio/globgrmpi.o \
./osprey/libu/ffio/globgrshmem.o \
./osprey/libu/ffio/globopen.o \
./osprey/libu/ffio/globutil.o \
./osprey/libu/ffio/gvfcntl.o \
./osprey/libu/ffio/gvopen.o \
./osprey/libu/ffio/gvread.o \
./osprey/libu/ffio/gvwrite.o \
./osprey/libu/ffio/gxbksp.o \
./osprey/libu/ffio/gxfcntl.o \
./osprey/libu/ffio/gxopen.o \
./osprey/libu/ffio/gxread.o \
./osprey/libu/ffio/gxwrite.o \
./osprey/libu/ffio/lockclose.o \
./osprey/libu/ffio/lockfcntl.o \
./osprey/libu/ffio/locklistio.o \
./osprey/libu/ffio/lockopen.o \
./osprey/libu/ffio/lockpos.o \
./osprey/libu/ffio/lockread.o \
./osprey/libu/ffio/lockwrite.o \
./osprey/libu/ffio/mrclose.o \
./osprey/libu/ffio/mrgrow.o \
./osprey/libu/ffio/mropen.o \
./osprey/libu/ffio/mrread.o \
./osprey/libu/ffio/mrset.o \
./osprey/libu/ffio/mrwrite.o \
./osprey/libu/ffio/parse_data.o \
./osprey/libu/ffio/sectorsize.o \
./osprey/libu/ffio/set_layer_options.o \
./osprey/libu/ffio/sqbclose.o \
./osprey/libu/ffio/sqbfcntl.o \
./osprey/libu/ffio/sqbopen.o \
./osprey/libu/ffio/sqbpos.o \
./osprey/libu/ffio/sqbread.o \
./osprey/libu/ffio/sqbseek.o \
./osprey/libu/ffio/sqbweod.o \
./osprey/libu/ffio/sqbweof.o \
./osprey/libu/ffio/sqbwrite.o \
./osprey/libu/ffio/sysasg.o \
./osprey/libu/ffio/sysclose.o \
./osprey/libu/ffio/sysfcntl.o \
./osprey/libu/ffio/syslistio.o \
./osprey/libu/ffio/syslseek.o \
./osprey/libu/ffio/sysopen.o \
./osprey/libu/ffio/sysread.o \
./osprey/libu/ffio/sysreada.o \
./osprey/libu/ffio/systrunc.o \
./osprey/libu/ffio/syswrite.o \
./osprey/libu/ffio/syswritea.o \
./osprey/libu/ffio/tmfbksp.o \
./osprey/libu/ffio/tmfclose.o \
./osprey/libu/ffio/tmfclosev.o \
./osprey/libu/ffio/tmfeov.o \
./osprey/libu/ffio/tmffcntl.o \
./osprey/libu/ffio/tmfgtpos.o \
./osprey/libu/ffio/tmfopen.o \
./osprey/libu/ffio/tmfpos.o \
./osprey/libu/ffio/tmfread.o \
./osprey/libu/ffio/tmfseek.o \
./osprey/libu/ffio/tmfskipf.o \
./osprey/libu/ffio/tmfstpos.o \
./osprey/libu/ffio/tmftptsi.o \
./osprey/libu/ffio/tmfwrite.o \
./osprey/libu/ffio/trcbksp.o \
./osprey/libu/ffio/trcclose.o \
./osprey/libu/ffio/trcfcntl.o \
./osprey/libu/ffio/trclistio.o \
./osprey/libu/ffio/trcopen.o \
./osprey/libu/ffio/trcpos.o \
./osprey/libu/ffio/trcprint.o \
./osprey/libu/ffio/trcread.o \
./osprey/libu/ffio/trcwrite.o \
./osprey/libu/ffio/txtbksp.o \
./osprey/libu/ffio/txtfcntl.o \
./osprey/libu/ffio/txtopen.o \
./osprey/libu/ffio/txtread.o \
./osprey/libu/ffio/txtwrite.o \
./osprey/libu/ffio/xrtrace.o 

C_DEPS += \
./osprey/libu/ffio/_ffopen.d \
./osprey/libu/ffio/asgrls.d \
./osprey/libu/ffio/binhex.d \
./osprey/libu/ffio/blxfcntl.d \
./osprey/libu/ffio/blxopen.d \
./osprey/libu/ffio/blxread.d \
./osprey/libu/ffio/blxwrite.d \
./osprey/libu/ffio/ccaclearpg.d \
./osprey/libu/ffio/ccaclosdiag.d \
./osprey/libu/ffio/ccaclose.d \
./osprey/libu/ffio/ccadmpcache.d \
./osprey/libu/ffio/ccafcntl.d \
./osprey/libu/ffio/ccaflush.d \
./osprey/libu/ffio/ccagetblk.d \
./osprey/libu/ffio/ccagetblkp.d \
./osprey/libu/ffio/ccalistio.d \
./osprey/libu/ffio/ccaopen.d \
./osprey/libu/ffio/ccardabuf.d \
./osprey/libu/ffio/ccaread.d \
./osprey/libu/ffio/ccareada.d \
./osprey/libu/ffio/ccaseek.d \
./osprey/libu/ffio/ccasyncpage.d \
./osprey/libu/ffio/ccatracker.d \
./osprey/libu/ffio/ccaweod.d \
./osprey/libu/ffio/ccawrabuf.d \
./osprey/libu/ffio/ccawrite.d \
./osprey/libu/ffio/ccawritea.d \
./osprey/libu/ffio/cchclose.d \
./osprey/libu/ffio/cchfcntl.d \
./osprey/libu/ffio/cchgetblk.d \
./osprey/libu/ffio/cchopen.d \
./osprey/libu/ffio/cchrdabuf.d \
./osprey/libu/ffio/cchread.d \
./osprey/libu/ffio/cchseek.d \
./osprey/libu/ffio/cchweod.d \
./osprey/libu/ffio/cchwrabuf.d \
./osprey/libu/ffio/cchwrite.d \
./osprey/libu/ffio/cdcfcntl.d \
./osprey/libu/ffio/cdcopen.d \
./osprey/libu/ffio/cdcread.d \
./osprey/libu/ffio/cdcwrite.d \
./osprey/libu/ffio/class_mr_sds_check.d \
./osprey/libu/ffio/class_vf_check.d \
./osprey/libu/ffio/class_vms_check.d \
./osprey/libu/ffio/cmpclose.d \
./osprey/libu/ffio/cmpfcntl.d \
./osprey/libu/ffio/cmplz.d \
./osprey/libu/ffio/cmpopen.d \
./osprey/libu/ffio/cmppos.d \
./osprey/libu/ffio/cmpread.d \
./osprey/libu/ffio/cmptrace.d \
./osprey/libu/ffio/cmpwrite.d \
./osprey/libu/ffio/convertc.d \
./osprey/libu/ffio/cosbksp.d \
./osprey/libu/ffio/cosclose.d \
./osprey/libu/ffio/cosfcntl.d \
./osprey/libu/ffio/cosopen.d \
./osprey/libu/ffio/cospos.d \
./osprey/libu/ffio/cosread.d \
./osprey/libu/ffio/cosseek.d \
./osprey/libu/ffio/coswrite.d \
./osprey/libu/ffio/errlist.d \
./osprey/libu/ffio/evnt_close_diags.d \
./osprey/libu/ffio/evnt_get_parent_child.d \
./osprey/libu/ffio/evnt_get_tracker.d \
./osprey/libu/ffio/evnt_trace_flush.d \
./osprey/libu/ffio/evntatexit.d \
./osprey/libu/ffio/evntbksp.d \
./osprey/libu/ffio/evntclose.d \
./osprey/libu/ffio/evntfcntl.d \
./osprey/libu/ffio/evntflush.d \
./osprey/libu/ffio/evntlistio.d \
./osprey/libu/ffio/evntopen.d \
./osprey/libu/ffio/evntread.d \
./osprey/libu/ffio/evntreada.d \
./osprey/libu/ffio/evntreadc.d \
./osprey/libu/ffio/evntseek.d \
./osprey/libu/ffio/evntweod.d \
./osprey/libu/ffio/evntweof.d \
./osprey/libu/ffio/evntwrite.d \
./osprey/libu/ffio/evntwritea.d \
./osprey/libu/ffio/evntwritec.d \
./osprey/libu/ffio/f77bksp.d \
./osprey/libu/ffio/f77close.d \
./osprey/libu/ffio/f77fcntl.d \
./osprey/libu/ffio/f77open.d \
./osprey/libu/ffio/f77read.d \
./osprey/libu/ffio/f77write.d \
./osprey/libu/ffio/fd_open.d \
./osprey/libu/ffio/ffbksp.d \
./osprey/libu/ffio/ffclose.d \
./osprey/libu/ffio/fferr.d \
./osprey/libu/ffio/fffcntl.d \
./osprey/libu/ffio/ffflush.d \
./osprey/libu/ffio/ffiolock.d \
./osprey/libu/ffio/fflistio.d \
./osprey/libu/ffio/ffnoop.d \
./osprey/libu/ffio/ffopen.d \
./osprey/libu/ffio/ffopens.d \
./osprey/libu/ffio/ffopensg.d \
./osprey/libu/ffio/ffpos.d \
./osprey/libu/ffio/ffread.d \
./osprey/libu/ffio/ffreada.d \
./osprey/libu/ffio/ffreadc.d \
./osprey/libu/ffio/ffseek.d \
./osprey/libu/ffio/ffspec.d \
./osprey/libu/ffio/ffstrerror.d \
./osprey/libu/ffio/ffweof.d \
./osprey/libu/ffio/ffwrite.d \
./osprey/libu/ffio/ffwritea.d \
./osprey/libu/ffio/ffwritec.d \
./osprey/libu/ffio/fssfcntl.d \
./osprey/libu/ffio/fssovfl.d \
./osprey/libu/ffio/fxrmain.d \
./osprey/libu/ffio/fxrmisc.d \
./osprey/libu/ffio/gfdc.d \
./osprey/libu/ffio/gffcntl.d \
./osprey/libu/ffio/gfopen.d \
./osprey/libu/ffio/gfread.d \
./osprey/libu/ffio/gfwrite.d \
./osprey/libu/ffio/globall.d \
./osprey/libu/ffio/globfcntl.d \
./osprey/libu/ffio/globgrmpi.d \
./osprey/libu/ffio/globgrshmem.d \
./osprey/libu/ffio/globopen.d \
./osprey/libu/ffio/globutil.d \
./osprey/libu/ffio/gvfcntl.d \
./osprey/libu/ffio/gvopen.d \
./osprey/libu/ffio/gvread.d \
./osprey/libu/ffio/gvwrite.d \
./osprey/libu/ffio/gxbksp.d \
./osprey/libu/ffio/gxfcntl.d \
./osprey/libu/ffio/gxopen.d \
./osprey/libu/ffio/gxread.d \
./osprey/libu/ffio/gxwrite.d \
./osprey/libu/ffio/lockclose.d \
./osprey/libu/ffio/lockfcntl.d \
./osprey/libu/ffio/locklistio.d \
./osprey/libu/ffio/lockopen.d \
./osprey/libu/ffio/lockpos.d \
./osprey/libu/ffio/lockread.d \
./osprey/libu/ffio/lockwrite.d \
./osprey/libu/ffio/mrclose.d \
./osprey/libu/ffio/mrgrow.d \
./osprey/libu/ffio/mropen.d \
./osprey/libu/ffio/mrread.d \
./osprey/libu/ffio/mrset.d \
./osprey/libu/ffio/mrwrite.d \
./osprey/libu/ffio/parse_data.d \
./osprey/libu/ffio/sectorsize.d \
./osprey/libu/ffio/set_layer_options.d \
./osprey/libu/ffio/sqbclose.d \
./osprey/libu/ffio/sqbfcntl.d \
./osprey/libu/ffio/sqbopen.d \
./osprey/libu/ffio/sqbpos.d \
./osprey/libu/ffio/sqbread.d \
./osprey/libu/ffio/sqbseek.d \
./osprey/libu/ffio/sqbweod.d \
./osprey/libu/ffio/sqbweof.d \
./osprey/libu/ffio/sqbwrite.d \
./osprey/libu/ffio/sysasg.d \
./osprey/libu/ffio/sysclose.d \
./osprey/libu/ffio/sysfcntl.d \
./osprey/libu/ffio/syslistio.d \
./osprey/libu/ffio/syslseek.d \
./osprey/libu/ffio/sysopen.d \
./osprey/libu/ffio/sysread.d \
./osprey/libu/ffio/sysreada.d \
./osprey/libu/ffio/systrunc.d \
./osprey/libu/ffio/syswrite.d \
./osprey/libu/ffio/syswritea.d \
./osprey/libu/ffio/tmfbksp.d \
./osprey/libu/ffio/tmfclose.d \
./osprey/libu/ffio/tmfclosev.d \
./osprey/libu/ffio/tmfeov.d \
./osprey/libu/ffio/tmffcntl.d \
./osprey/libu/ffio/tmfgtpos.d \
./osprey/libu/ffio/tmfopen.d \
./osprey/libu/ffio/tmfpos.d \
./osprey/libu/ffio/tmfread.d \
./osprey/libu/ffio/tmfseek.d \
./osprey/libu/ffio/tmfskipf.d \
./osprey/libu/ffio/tmfstpos.d \
./osprey/libu/ffio/tmftptsi.d \
./osprey/libu/ffio/tmfwrite.d \
./osprey/libu/ffio/trcbksp.d \
./osprey/libu/ffio/trcclose.d \
./osprey/libu/ffio/trcfcntl.d \
./osprey/libu/ffio/trclistio.d \
./osprey/libu/ffio/trcopen.d \
./osprey/libu/ffio/trcpos.d \
./osprey/libu/ffio/trcprint.d \
./osprey/libu/ffio/trcread.d \
./osprey/libu/ffio/trcwrite.d \
./osprey/libu/ffio/txtbksp.d \
./osprey/libu/ffio/txtfcntl.d \
./osprey/libu/ffio/txtopen.d \
./osprey/libu/ffio/txtread.d \
./osprey/libu/ffio/txtwrite.d \
./osprey/libu/ffio/xrtrace.d 


# Each subdirectory must supply rules for building sources it contributes
osprey/libu/ffio/%.o: ../osprey/libu/ffio/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


