#  Define build parameters
BUILD_BASE     = ../../../osprey/be/lno
TARG_INFO_SRC  = ../../../osprey/common/targ_info

#  Include setup file which will then include Makefile.base
include ../../..//osprey/Makefile.gsetup
