################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../osprey/libf/pxf/ipxfargc.c \
../osprey/libf/pxf/ipxfwexitstatus.c \
../osprey/libf/pxf/ipxfwstopsig.c \
../osprey/libf/pxf/ipxfwtermsig.c \
../osprey/libf/pxf/pxfaccess.c \
../osprey/libf/pxf/pxfaintget.c \
../osprey/libf/pxf/pxfalarm.c \
../osprey/libf/pxf/pxfcfgetospeed.c \
../osprey/libf/pxf/pxfchdir.c \
../osprey/libf/pxf/pxfchmod.c \
../osprey/libf/pxf/pxfchown.c \
../osprey/libf/pxf/pxfchroot.c \
../osprey/libf/pxf/pxfclearenv.c \
../osprey/libf/pxf/pxfclose.c \
../osprey/libf/pxf/pxfclosedir.c \
../osprey/libf/pxf/pxfconst.c \
../osprey/libf/pxf/pxfcreat.c \
../osprey/libf/pxf/pxfctermid.c \
../osprey/libf/pxf/pxfdup.c \
../osprey/libf/pxf/pxfestrget.c \
../osprey/libf/pxf/pxfexecv.c \
../osprey/libf/pxf/pxfexecve.c \
../osprey/libf/pxf/pxfexecvp.c \
../osprey/libf/pxf/pxffastexit.c \
../osprey/libf/pxf/pxffcntl.c \
../osprey/libf/pxf/pxffileno.c \
../osprey/libf/pxf/pxffork.c \
../osprey/libf/pxf/pxfget.c \
../osprey/libf/pxf/pxfgetarg.c \
../osprey/libf/pxf/pxfgetcwd.c \
../osprey/libf/pxf/pxfgetegid.c \
../osprey/libf/pxf/pxfgetenv.c \
../osprey/libf/pxf/pxfgeteuid.c \
../osprey/libf/pxf/pxfgetgid.c \
../osprey/libf/pxf/pxfgetgrgid.c \
../osprey/libf/pxf/pxfgetgrnam.c \
../osprey/libf/pxf/pxfgetgroups.c \
../osprey/libf/pxf/pxfgetlogin.c \
../osprey/libf/pxf/pxfgetpgrp.c \
../osprey/libf/pxf/pxfgetpid.c \
../osprey/libf/pxf/pxfgetppid.c \
../osprey/libf/pxf/pxfgetpwnam.c \
../osprey/libf/pxf/pxfgetpwuid.c \
../osprey/libf/pxf/pxfgetuid.c \
../osprey/libf/pxf/pxfisatty.c \
../osprey/libf/pxf/pxfisblk.c \
../osprey/libf/pxf/pxfischr.c \
../osprey/libf/pxf/pxfisdir.c \
../osprey/libf/pxf/pxfisfifo.c \
../osprey/libf/pxf/pxfisreg.c \
../osprey/libf/pxf/pxfkill.c \
../osprey/libf/pxf/pxflink.c \
../osprey/libf/pxf/pxflocaltime.c \
../osprey/libf/pxf/pxflseek.c \
../osprey/libf/pxf/pxfmkfifo.c \
../osprey/libf/pxf/pxfopen.c \
../osprey/libf/pxf/pxfopendir.c \
../osprey/libf/pxf/pxfpause.c \
../osprey/libf/pxf/pxfpipe.c \
../osprey/libf/pxf/pxfread.c \
../osprey/libf/pxf/pxfreaddir.c \
../osprey/libf/pxf/pxfrename.c \
../osprey/libf/pxf/pxfrewinddir.c \
../osprey/libf/pxf/pxfrmdir.c \
../osprey/libf/pxf/pxfsetenv.c \
../osprey/libf/pxf/pxfsetgid.c \
../osprey/libf/pxf/pxfsetpgid.c \
../osprey/libf/pxf/pxfsetsid.c \
../osprey/libf/pxf/pxfsetuid.c \
../osprey/libf/pxf/pxfsigaddset.c \
../osprey/libf/pxf/pxfsigdelset.c \
../osprey/libf/pxf/pxfsigemptyset.c \
../osprey/libf/pxf/pxfsigfillset.c \
../osprey/libf/pxf/pxfsigismember.c \
../osprey/libf/pxf/pxfsigpending.c \
../osprey/libf/pxf/pxfsigprocmask.c \
../osprey/libf/pxf/pxfsigsuspend.c \
../osprey/libf/pxf/pxfsleep.c \
../osprey/libf/pxf/pxfstat.c \
../osprey/libf/pxf/pxfstrget.c \
../osprey/libf/pxf/pxfstructcopy.c \
../osprey/libf/pxf/pxfstructcreate.c \
../osprey/libf/pxf/pxfsysconf.c \
../osprey/libf/pxf/pxfsystem.c \
../osprey/libf/pxf/pxftcgetattr.c \
../osprey/libf/pxf/pxftcgetpgrp.c \
../osprey/libf/pxf/pxftcsendbreak.c \
../osprey/libf/pxf/pxftcsetpgrp.c \
../osprey/libf/pxf/pxftime.c \
../osprey/libf/pxf/pxftimes.c \
../osprey/libf/pxf/pxfucompare.c \
../osprey/libf/pxf/pxfumask.c \
../osprey/libf/pxf/pxfuname.c \
../osprey/libf/pxf/pxfunlink.c \
../osprey/libf/pxf/pxfutime.c \
../osprey/libf/pxf/pxfwait.c \
../osprey/libf/pxf/pxfwaitpid.c \
../osprey/libf/pxf/pxfwifexited.c \
../osprey/libf/pxf/pxfwifsignaled.c \
../osprey/libf/pxf/pxfwifstopped.c \
../osprey/libf/pxf/pxfwrite.c \
../osprey/libf/pxf/table.c 

OBJS += \
./osprey/libf/pxf/ipxfargc.o \
./osprey/libf/pxf/ipxfwexitstatus.o \
./osprey/libf/pxf/ipxfwstopsig.o \
./osprey/libf/pxf/ipxfwtermsig.o \
./osprey/libf/pxf/pxfaccess.o \
./osprey/libf/pxf/pxfaintget.o \
./osprey/libf/pxf/pxfalarm.o \
./osprey/libf/pxf/pxfcfgetospeed.o \
./osprey/libf/pxf/pxfchdir.o \
./osprey/libf/pxf/pxfchmod.o \
./osprey/libf/pxf/pxfchown.o \
./osprey/libf/pxf/pxfchroot.o \
./osprey/libf/pxf/pxfclearenv.o \
./osprey/libf/pxf/pxfclose.o \
./osprey/libf/pxf/pxfclosedir.o \
./osprey/libf/pxf/pxfconst.o \
./osprey/libf/pxf/pxfcreat.o \
./osprey/libf/pxf/pxfctermid.o \
./osprey/libf/pxf/pxfdup.o \
./osprey/libf/pxf/pxfestrget.o \
./osprey/libf/pxf/pxfexecv.o \
./osprey/libf/pxf/pxfexecve.o \
./osprey/libf/pxf/pxfexecvp.o \
./osprey/libf/pxf/pxffastexit.o \
./osprey/libf/pxf/pxffcntl.o \
./osprey/libf/pxf/pxffileno.o \
./osprey/libf/pxf/pxffork.o \
./osprey/libf/pxf/pxfget.o \
./osprey/libf/pxf/pxfgetarg.o \
./osprey/libf/pxf/pxfgetcwd.o \
./osprey/libf/pxf/pxfgetegid.o \
./osprey/libf/pxf/pxfgetenv.o \
./osprey/libf/pxf/pxfgeteuid.o \
./osprey/libf/pxf/pxfgetgid.o \
./osprey/libf/pxf/pxfgetgrgid.o \
./osprey/libf/pxf/pxfgetgrnam.o \
./osprey/libf/pxf/pxfgetgroups.o \
./osprey/libf/pxf/pxfgetlogin.o \
./osprey/libf/pxf/pxfgetpgrp.o \
./osprey/libf/pxf/pxfgetpid.o \
./osprey/libf/pxf/pxfgetppid.o \
./osprey/libf/pxf/pxfgetpwnam.o \
./osprey/libf/pxf/pxfgetpwuid.o \
./osprey/libf/pxf/pxfgetuid.o \
./osprey/libf/pxf/pxfisatty.o \
./osprey/libf/pxf/pxfisblk.o \
./osprey/libf/pxf/pxfischr.o \
./osprey/libf/pxf/pxfisdir.o \
./osprey/libf/pxf/pxfisfifo.o \
./osprey/libf/pxf/pxfisreg.o \
./osprey/libf/pxf/pxfkill.o \
./osprey/libf/pxf/pxflink.o \
./osprey/libf/pxf/pxflocaltime.o \
./osprey/libf/pxf/pxflseek.o \
./osprey/libf/pxf/pxfmkfifo.o \
./osprey/libf/pxf/pxfopen.o \
./osprey/libf/pxf/pxfopendir.o \
./osprey/libf/pxf/pxfpause.o \
./osprey/libf/pxf/pxfpipe.o \
./osprey/libf/pxf/pxfread.o \
./osprey/libf/pxf/pxfreaddir.o \
./osprey/libf/pxf/pxfrename.o \
./osprey/libf/pxf/pxfrewinddir.o \
./osprey/libf/pxf/pxfrmdir.o \
./osprey/libf/pxf/pxfsetenv.o \
./osprey/libf/pxf/pxfsetgid.o \
./osprey/libf/pxf/pxfsetpgid.o \
./osprey/libf/pxf/pxfsetsid.o \
./osprey/libf/pxf/pxfsetuid.o \
./osprey/libf/pxf/pxfsigaddset.o \
./osprey/libf/pxf/pxfsigdelset.o \
./osprey/libf/pxf/pxfsigemptyset.o \
./osprey/libf/pxf/pxfsigfillset.o \
./osprey/libf/pxf/pxfsigismember.o \
./osprey/libf/pxf/pxfsigpending.o \
./osprey/libf/pxf/pxfsigprocmask.o \
./osprey/libf/pxf/pxfsigsuspend.o \
./osprey/libf/pxf/pxfsleep.o \
./osprey/libf/pxf/pxfstat.o \
./osprey/libf/pxf/pxfstrget.o \
./osprey/libf/pxf/pxfstructcopy.o \
./osprey/libf/pxf/pxfstructcreate.o \
./osprey/libf/pxf/pxfsysconf.o \
./osprey/libf/pxf/pxfsystem.o \
./osprey/libf/pxf/pxftcgetattr.o \
./osprey/libf/pxf/pxftcgetpgrp.o \
./osprey/libf/pxf/pxftcsendbreak.o \
./osprey/libf/pxf/pxftcsetpgrp.o \
./osprey/libf/pxf/pxftime.o \
./osprey/libf/pxf/pxftimes.o \
./osprey/libf/pxf/pxfucompare.o \
./osprey/libf/pxf/pxfumask.o \
./osprey/libf/pxf/pxfuname.o \
./osprey/libf/pxf/pxfunlink.o \
./osprey/libf/pxf/pxfutime.o \
./osprey/libf/pxf/pxfwait.o \
./osprey/libf/pxf/pxfwaitpid.o \
./osprey/libf/pxf/pxfwifexited.o \
./osprey/libf/pxf/pxfwifsignaled.o \
./osprey/libf/pxf/pxfwifstopped.o \
./osprey/libf/pxf/pxfwrite.o \
./osprey/libf/pxf/table.o 

C_DEPS += \
./osprey/libf/pxf/ipxfargc.d \
./osprey/libf/pxf/ipxfwexitstatus.d \
./osprey/libf/pxf/ipxfwstopsig.d \
./osprey/libf/pxf/ipxfwtermsig.d \
./osprey/libf/pxf/pxfaccess.d \
./osprey/libf/pxf/pxfaintget.d \
./osprey/libf/pxf/pxfalarm.d \
./osprey/libf/pxf/pxfcfgetospeed.d \
./osprey/libf/pxf/pxfchdir.d \
./osprey/libf/pxf/pxfchmod.d \
./osprey/libf/pxf/pxfchown.d \
./osprey/libf/pxf/pxfchroot.d \
./osprey/libf/pxf/pxfclearenv.d \
./osprey/libf/pxf/pxfclose.d \
./osprey/libf/pxf/pxfclosedir.d \
./osprey/libf/pxf/pxfconst.d \
./osprey/libf/pxf/pxfcreat.d \
./osprey/libf/pxf/pxfctermid.d \
./osprey/libf/pxf/pxfdup.d \
./osprey/libf/pxf/pxfestrget.d \
./osprey/libf/pxf/pxfexecv.d \
./osprey/libf/pxf/pxfexecve.d \
./osprey/libf/pxf/pxfexecvp.d \
./osprey/libf/pxf/pxffastexit.d \
./osprey/libf/pxf/pxffcntl.d \
./osprey/libf/pxf/pxffileno.d \
./osprey/libf/pxf/pxffork.d \
./osprey/libf/pxf/pxfget.d \
./osprey/libf/pxf/pxfgetarg.d \
./osprey/libf/pxf/pxfgetcwd.d \
./osprey/libf/pxf/pxfgetegid.d \
./osprey/libf/pxf/pxfgetenv.d \
./osprey/libf/pxf/pxfgeteuid.d \
./osprey/libf/pxf/pxfgetgid.d \
./osprey/libf/pxf/pxfgetgrgid.d \
./osprey/libf/pxf/pxfgetgrnam.d \
./osprey/libf/pxf/pxfgetgroups.d \
./osprey/libf/pxf/pxfgetlogin.d \
./osprey/libf/pxf/pxfgetpgrp.d \
./osprey/libf/pxf/pxfgetpid.d \
./osprey/libf/pxf/pxfgetppid.d \
./osprey/libf/pxf/pxfgetpwnam.d \
./osprey/libf/pxf/pxfgetpwuid.d \
./osprey/libf/pxf/pxfgetuid.d \
./osprey/libf/pxf/pxfisatty.d \
./osprey/libf/pxf/pxfisblk.d \
./osprey/libf/pxf/pxfischr.d \
./osprey/libf/pxf/pxfisdir.d \
./osprey/libf/pxf/pxfisfifo.d \
./osprey/libf/pxf/pxfisreg.d \
./osprey/libf/pxf/pxfkill.d \
./osprey/libf/pxf/pxflink.d \
./osprey/libf/pxf/pxflocaltime.d \
./osprey/libf/pxf/pxflseek.d \
./osprey/libf/pxf/pxfmkfifo.d \
./osprey/libf/pxf/pxfopen.d \
./osprey/libf/pxf/pxfopendir.d \
./osprey/libf/pxf/pxfpause.d \
./osprey/libf/pxf/pxfpipe.d \
./osprey/libf/pxf/pxfread.d \
./osprey/libf/pxf/pxfreaddir.d \
./osprey/libf/pxf/pxfrename.d \
./osprey/libf/pxf/pxfrewinddir.d \
./osprey/libf/pxf/pxfrmdir.d \
./osprey/libf/pxf/pxfsetenv.d \
./osprey/libf/pxf/pxfsetgid.d \
./osprey/libf/pxf/pxfsetpgid.d \
./osprey/libf/pxf/pxfsetsid.d \
./osprey/libf/pxf/pxfsetuid.d \
./osprey/libf/pxf/pxfsigaddset.d \
./osprey/libf/pxf/pxfsigdelset.d \
./osprey/libf/pxf/pxfsigemptyset.d \
./osprey/libf/pxf/pxfsigfillset.d \
./osprey/libf/pxf/pxfsigismember.d \
./osprey/libf/pxf/pxfsigpending.d \
./osprey/libf/pxf/pxfsigprocmask.d \
./osprey/libf/pxf/pxfsigsuspend.d \
./osprey/libf/pxf/pxfsleep.d \
./osprey/libf/pxf/pxfstat.d \
./osprey/libf/pxf/pxfstrget.d \
./osprey/libf/pxf/pxfstructcopy.d \
./osprey/libf/pxf/pxfstructcreate.d \
./osprey/libf/pxf/pxfsysconf.d \
./osprey/libf/pxf/pxfsystem.d \
./osprey/libf/pxf/pxftcgetattr.d \
./osprey/libf/pxf/pxftcgetpgrp.d \
./osprey/libf/pxf/pxftcsendbreak.d \
./osprey/libf/pxf/pxftcsetpgrp.d \
./osprey/libf/pxf/pxftime.d \
./osprey/libf/pxf/pxftimes.d \
./osprey/libf/pxf/pxfucompare.d \
./osprey/libf/pxf/pxfumask.d \
./osprey/libf/pxf/pxfuname.d \
./osprey/libf/pxf/pxfunlink.d \
./osprey/libf/pxf/pxfutime.d \
./osprey/libf/pxf/pxfwait.d \
./osprey/libf/pxf/pxfwaitpid.d \
./osprey/libf/pxf/pxfwifexited.d \
./osprey/libf/pxf/pxfwifsignaled.d \
./osprey/libf/pxf/pxfwifstopped.d \
./osprey/libf/pxf/pxfwrite.d \
./osprey/libf/pxf/table.d 


# Each subdirectory must supply rules for building sources it contributes
osprey/libf/pxf/%.o: ../osprey/libf/pxf/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


