#  Define build parameters
BUILD_BASE     = ../../../../osprey/crayf90/fe90
BUILD_VARIANT  = GNU_4_2_0

#  Include setup file which will then include Makefile.base
include ../../../..//osprey/Makefile.gsetup
