################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../osprey/targdir/be/DaVinci.o \
../osprey/targdir/be/alias_analyzer.o \
../osprey/targdir/be/be_memop_annot.o \
../osprey/targdir/be/be_symtab.o \
../osprey/targdir/be/be_util.o \
../osprey/targdir/be/be_version.o \
../osprey/targdir/be/betarget.o \
../osprey/targdir/be/bitset.o \
../osprey/targdir/be/c_q_add.o \
../osprey/targdir/be/c_q_div.o \
../osprey/targdir/be/c_q_mul.o \
../osprey/targdir/be/c_q_neg.o \
../osprey/targdir/be/c_q_rel.o \
../osprey/targdir/be/c_q_sqrt.o \
../osprey/targdir/be/c_q_sub.o \
../osprey/targdir/be/c_q_to_a.o \
../osprey/targdir/be/c_qtenscale.o \
../osprey/targdir/be/c_qwmultu.o \
../osprey/targdir/be/cleanup.o \
../osprey/targdir/be/clone.o \
../osprey/targdir/be/clone_DST_utils.o \
../osprey/targdir/be/com_whirlview.o \
../osprey/targdir/be/comp_decl.o \
../osprey/targdir/be/comp_driver.o \
../osprey/targdir/be/config.o \
../osprey/targdir/be/config_cache.o \
../osprey/targdir/be/config_cache_targ.o \
../osprey/targdir/be/config_elf_targ.o \
../osprey/targdir/be/config_host.o \
../osprey/targdir/be/config_platform.o \
../osprey/targdir/be/config_targ.o \
../osprey/targdir/be/const.o \
../osprey/targdir/be/constraint_graph.o \
../osprey/targdir/be/constraint_graph_escanal.o \
../osprey/targdir/be/constraint_graph_solve.o \
../osprey/targdir/be/cse_table.o \
../osprey/targdir/be/cxx_base.o \
../osprey/targdir/be/cxx_graph.o \
../osprey/targdir/be/cxx_hash_util.o \
../osprey/targdir/be/cxx_memory.o \
../osprey/targdir/be/data_layout.o \
../osprey/targdir/be/dep_graph.o \
../osprey/targdir/be/dra_clone.o \
../osprey/targdir/be/dra_demangle.o \
../osprey/targdir/be/dra_ec.o \
../osprey/targdir/be/dra_file_util.o \
../osprey/targdir/be/dra_mangle.o \
../osprey/targdir/be/driver.o \
../osprey/targdir/be/driver_targ.o \
../osprey/targdir/be/driver_util.o \
../osprey/targdir/be/dso.o \
../osprey/targdir/be/dvector.o \
../osprey/targdir/be/dwarf_DST.o \
../osprey/targdir/be/dwarf_DST_dump.o \
../osprey/targdir/be/dwarf_DST_mem.o \
../osprey/targdir/be/dwarf_DST_producer.o \
../osprey/targdir/be/emulate.o \
../osprey/targdir/be/err_host.o \
../osprey/targdir/be/errors.o \
../osprey/targdir/be/f90_lower.o \
../osprey/targdir/be/f90_lower_dep.o \
../osprey/targdir/be/f90_utils.o \
../osprey/targdir/be/fb_cfg.o \
../osprey/targdir/be/fb_info.o \
../osprey/targdir/be/fb_whirl.o \
../osprey/targdir/be/file_util.o \
../osprey/targdir/be/fill_align.o \
../osprey/targdir/be/fill_align_targ.o \
../osprey/targdir/be/flags.o \
../osprey/targdir/be/glob.o \
../osprey/targdir/be/goto_conv.o \
../osprey/targdir/be/instr_reader.o \
../osprey/targdir/be/intrn_info.o \
../osprey/targdir/be/ipa_be_read.o \
../osprey/targdir/be/ipa_lno_file.o \
../osprey/targdir/be/ipa_lno_summary.o \
../osprey/targdir/be/ipa_lno_util.o \
../osprey/targdir/be/ipo_tlog_utils.o \
../osprey/targdir/be/ir_bcom.o \
../osprey/targdir/be/ir_bread.o \
../osprey/targdir/be/ir_bwrite.o \
../osprey/targdir/be/ir_reader.o \
../osprey/targdir/be/irbdata.o \
../osprey/targdir/be/iter.o \
../osprey/targdir/be/ll.o \
../osprey/targdir/be/mat.o \
../osprey/targdir/be/mem_ctr.o \
../osprey/targdir/be/memory.o \
../osprey/targdir/be/mfmc_misc.o \
../osprey/targdir/be/mfmc_query.o \
../osprey/targdir/be/mfmc_setup.o \
../osprey/targdir/be/mfmc_solve.o \
../osprey/targdir/be/mtypes.o \
../osprey/targdir/be/nystrom_alias_analyzer.o \
../osprey/targdir/be/omp_lower.o \
../osprey/targdir/be/opcode.o \
../osprey/targdir/be/opcode_core.o \
../osprey/targdir/be/opt_addr_flags.o \
../osprey/targdir/be/opt_alias_mgr.o \
../osprey/targdir/be/opt_alias_rule.o \
../osprey/targdir/be/opt_cvtl_rule.o \
../osprey/targdir/be/opt_goto.o \
../osprey/targdir/be/opt_ipaa_io.o \
../osprey/targdir/be/opt_points_to_non_template.o \
../osprey/targdir/be/opt_points_to_summary.o \
../osprey/targdir/be/options_stack.o \
../osprey/targdir/be/ori.o \
../osprey/targdir/be/output_func_start_profiler.o \
../osprey/targdir/be/phase.o \
../osprey/targdir/be/preg_list.o \
../osprey/targdir/be/printsrc.o \
../osprey/targdir/be/priority_queue.o \
../osprey/targdir/be/privatize_common.o \
../osprey/targdir/be/prompf.o \
../osprey/targdir/be/pu_info.o \
../osprey/targdir/be/quadsim.o \
../osprey/targdir/be/rbi.o \
../osprey/targdir/be/region_bounds.o \
../osprey/targdir/be/region_init.o \
../osprey/targdir/be/region_util.o \
../osprey/targdir/be/resource.o \
../osprey/targdir/be/rewrite_pragmas.o \
../osprey/targdir/be/sections.o \
../osprey/targdir/be/soe.o \
../osprey/targdir/be/standardize.o \
../osprey/targdir/be/stblock.o \
../osprey/targdir/be/strtab.o \
../osprey/targdir/be/symtab.o \
../osprey/targdir/be/symtab_verify.o \
../osprey/targdir/be/targ_const.o \
../osprey/targdir/be/targ_sim.o \
../osprey/targdir/be/ti_init.o \
../osprey/targdir/be/timing.o \
../osprey/targdir/be/tlog.o \
../osprey/targdir/be/tls.o \
../osprey/targdir/be/tracing.o \
../osprey/targdir/be/ttype.o \
../osprey/targdir/be/u64_lower_wn.o \
../osprey/targdir/be/util.o \
../osprey/targdir/be/vcg.o \
../osprey/targdir/be/vho_lower.o \
../osprey/targdir/be/vstring.o \
../osprey/targdir/be/w2op.o \
../osprey/targdir/be/wb.o \
../osprey/targdir/be/wb_anl.o \
../osprey/targdir/be/wb_browser.o \
../osprey/targdir/be/wb_buffer.o \
../osprey/targdir/be/wb_carray.o \
../osprey/targdir/be/wb_f90_lower.o \
../osprey/targdir/be/wb_ipl.o \
../osprey/targdir/be/wb_lwr.o \
../osprey/targdir/be/wb_omp.o \
../osprey/targdir/be/wb_util.o \
../osprey/targdir/be/weak.o \
../osprey/targdir/be/whirl2src.o \
../osprey/targdir/be/wn.o \
../osprey/targdir/be/wn_cfg.o \
../osprey/targdir/be/wn_cyg_instrument.o \
../osprey/targdir/be/wn_fio.o \
../osprey/targdir/be/wn_instrument.o \
../osprey/targdir/be/wn_lower.o \
../osprey/targdir/be/wn_map.o \
../osprey/targdir/be/wn_mp.o \
../osprey/targdir/be/wn_pragmas.o \
../osprey/targdir/be/wn_retype_expr.o \
../osprey/targdir/be/wn_simp.o \
../osprey/targdir/be/wn_unroll.o \
../osprey/targdir/be/wn_util.o \
../osprey/targdir/be/wn_verifier.o \
../osprey/targdir/be/wssa_defs.o \
../osprey/targdir/be/wssa_du.o \
../osprey/targdir/be/wssa_io.o \
../osprey/targdir/be/wssa_mgr.o \
../osprey/targdir/be/wssa_points_to.o \
../osprey/targdir/be/wssa_sym.o \
../osprey/targdir/be/wssa_update.o \
../osprey/targdir/be/wssa_utils.o \
../osprey/targdir/be/wssa_wn.o \
../osprey/targdir/be/wutil.o \
../osprey/targdir/be/xstats.o 


# Each subdirectory must supply rules for building sources it contributes

