################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../osprey-gcc/gcc/alias.c \
../osprey-gcc/gcc/alloc-pool.c \
../osprey-gcc/gcc/attribs.c \
../osprey-gcc/gcc/bb-reorder.c \
../osprey-gcc/gcc/bitmap.c \
../osprey-gcc/gcc/bt-load.c \
../osprey-gcc/gcc/builtins.c \
../osprey-gcc/gcc/c-aux-info.c \
../osprey-gcc/gcc/c-common.c \
../osprey-gcc/gcc/c-convert.c \
../osprey-gcc/gcc/c-cppbuiltin.c \
../osprey-gcc/gcc/c-decl.c \
../osprey-gcc/gcc/c-dump.c \
../osprey-gcc/gcc/c-errors.c \
../osprey-gcc/gcc/c-format.c \
../osprey-gcc/gcc/c-gimplify.c \
../osprey-gcc/gcc/c-incpath.c \
../osprey-gcc/gcc/c-lang.c \
../osprey-gcc/gcc/c-lex.c \
../osprey-gcc/gcc/c-objc-common.c \
../osprey-gcc/gcc/c-opts.c \
../osprey-gcc/gcc/c-pch.c \
../osprey-gcc/gcc/c-ppoutput.c \
../osprey-gcc/gcc/c-pragma.c \
../osprey-gcc/gcc/c-pretty-print.c \
../osprey-gcc/gcc/c-semantics.c \
../osprey-gcc/gcc/c-typeck.c \
../osprey-gcc/gcc/caller-save.c \
../osprey-gcc/gcc/calls.c \
../osprey-gcc/gcc/cfg.c \
../osprey-gcc/gcc/cfganal.c \
../osprey-gcc/gcc/cfgbuild.c \
../osprey-gcc/gcc/cfgcleanup.c \
../osprey-gcc/gcc/cfgexpand.c \
../osprey-gcc/gcc/cfghooks.c \
../osprey-gcc/gcc/cfglayout.c \
../osprey-gcc/gcc/cfgloop.c \
../osprey-gcc/gcc/cfgloopanal.c \
../osprey-gcc/gcc/cfgloopmanip.c \
../osprey-gcc/gcc/cfgrtl.c \
../osprey-gcc/gcc/cgraph.c \
../osprey-gcc/gcc/cgraphunit.c \
../osprey-gcc/gcc/collect2.c \
../osprey-gcc/gcc/combine.c \
../osprey-gcc/gcc/conflict.c \
../osprey-gcc/gcc/convert.c \
../osprey-gcc/gcc/coverage.c \
../osprey-gcc/gcc/cppdefault.c \
../osprey-gcc/gcc/cppspec.c \
../osprey-gcc/gcc/crtstuff.c \
../osprey-gcc/gcc/cse.c \
../osprey-gcc/gcc/cselib.c \
../osprey-gcc/gcc/dbxout.c \
../osprey-gcc/gcc/ddg.c \
../osprey-gcc/gcc/debug.c \
../osprey-gcc/gcc/df.c \
../osprey-gcc/gcc/diagnostic.c \
../osprey-gcc/gcc/dojump.c \
../osprey-gcc/gcc/dominance.c \
../osprey-gcc/gcc/domwalk.c \
../osprey-gcc/gcc/dummy-conditions.c \
../osprey-gcc/gcc/dwarf2asm.c \
../osprey-gcc/gcc/dwarf2out.c \
../osprey-gcc/gcc/emit-rtl.c \
../osprey-gcc/gcc/errors.c \
../osprey-gcc/gcc/et-forest.c \
../osprey-gcc/gcc/except.c \
../osprey-gcc/gcc/explow.c \
../osprey-gcc/gcc/expmed.c \
../osprey-gcc/gcc/expr.c \
../osprey-gcc/gcc/final.c \
../osprey-gcc/gcc/fix-header.c \
../osprey-gcc/gcc/flow.c \
../osprey-gcc/gcc/fold-const.c \
../osprey-gcc/gcc/fp-test.c \
../osprey-gcc/gcc/function.c \
../osprey-gcc/gcc/gcc.c \
../osprey-gcc/gcc/gccspec.c \
../osprey-gcc/gcc/gcov-dump.c \
../osprey-gcc/gcc/gcov-io.c \
../osprey-gcc/gcc/gcov-iov.c \
../osprey-gcc/gcc/gcov.c \
../osprey-gcc/gcc/gcse.c \
../osprey-gcc/gcc/gen-protos.c \
../osprey-gcc/gcc/genattr.c \
../osprey-gcc/gcc/genattrtab.c \
../osprey-gcc/gcc/genautomata.c \
../osprey-gcc/gcc/gencheck.c \
../osprey-gcc/gcc/gencodes.c \
../osprey-gcc/gcc/genconditions.c \
../osprey-gcc/gcc/genconfig.c \
../osprey-gcc/gcc/genconstants.c \
../osprey-gcc/gcc/genemit.c \
../osprey-gcc/gcc/genextract.c \
../osprey-gcc/gcc/genflags.c \
../osprey-gcc/gcc/gengenrtl.c \
../osprey-gcc/gcc/gengtype.c \
../osprey-gcc/gcc/genmddeps.c \
../osprey-gcc/gcc/genmodes.c \
../osprey-gcc/gcc/genopinit.c \
../osprey-gcc/gcc/genoutput.c \
../osprey-gcc/gcc/genpeep.c \
../osprey-gcc/gcc/genpreds.c \
../osprey-gcc/gcc/genrecog.c \
../osprey-gcc/gcc/gensupport.c \
../osprey-gcc/gcc/ggc-common.c \
../osprey-gcc/gcc/ggc-none.c \
../osprey-gcc/gcc/ggc-page.c \
../osprey-gcc/gcc/ggc-zone.c \
../osprey-gcc/gcc/gimple-low.c \
../osprey-gcc/gcc/gimplify.c \
../osprey-gcc/gcc/global.c \
../osprey-gcc/gcc/gmon.c \
../osprey-gcc/gcc/graph.c \
../osprey-gcc/gcc/gthr-gnat.c \
../osprey-gcc/gcc/gthr-posix.c \
../osprey-gcc/gcc/haifa-sched.c \
../osprey-gcc/gcc/hooks.c \
../osprey-gcc/gcc/host-default.c \
../osprey-gcc/gcc/ifcvt.c \
../osprey-gcc/gcc/integrate.c \
../osprey-gcc/gcc/intl.c \
../osprey-gcc/gcc/jump.c \
../osprey-gcc/gcc/lambda-code.c \
../osprey-gcc/gcc/lambda-mat.c \
../osprey-gcc/gcc/lambda-trans.c \
../osprey-gcc/gcc/langhooks.c \
../osprey-gcc/gcc/lcm.c \
../osprey-gcc/gcc/libgcc2.c \
../osprey-gcc/gcc/libgcov.c \
../osprey-gcc/gcc/lists.c \
../osprey-gcc/gcc/local-alloc.c \
../osprey-gcc/gcc/loop-doloop.c \
../osprey-gcc/gcc/loop-init.c \
../osprey-gcc/gcc/loop-invariant.c \
../osprey-gcc/gcc/loop-iv.c \
../osprey-gcc/gcc/loop-unroll.c \
../osprey-gcc/gcc/loop-unswitch.c \
../osprey-gcc/gcc/loop.c \
../osprey-gcc/gcc/main.c \
../osprey-gcc/gcc/mips-tdump.c \
../osprey-gcc/gcc/mips-tfile.c \
../osprey-gcc/gcc/modulo-sched.c \
../osprey-gcc/gcc/optabs.c \
../osprey-gcc/gcc/opts.c \
../osprey-gcc/gcc/params.c \
../osprey-gcc/gcc/passes.c \
../osprey-gcc/gcc/pointer-set.c \
../osprey-gcc/gcc/postreload-gcse.c \
../osprey-gcc/gcc/postreload.c \
../osprey-gcc/gcc/predict.c \
../osprey-gcc/gcc/prefix.c \
../osprey-gcc/gcc/pretty-print.c \
../osprey-gcc/gcc/print-rtl.c \
../osprey-gcc/gcc/print-tree.c \
../osprey-gcc/gcc/profile.c \
../osprey-gcc/gcc/protoize.c \
../osprey-gcc/gcc/read-rtl.c \
../osprey-gcc/gcc/real.c \
../osprey-gcc/gcc/recog.c \
../osprey-gcc/gcc/reg-stack.c \
../osprey-gcc/gcc/regclass.c \
../osprey-gcc/gcc/regmove.c \
../osprey-gcc/gcc/regrename.c \
../osprey-gcc/gcc/reload.c \
../osprey-gcc/gcc/reload1.c \
../osprey-gcc/gcc/reorg.c \
../osprey-gcc/gcc/resource.c \
../osprey-gcc/gcc/rtl-error.c \
../osprey-gcc/gcc/rtl-profile.c \
../osprey-gcc/gcc/rtl.c \
../osprey-gcc/gcc/rtlanal.c \
../osprey-gcc/gcc/rtlhooks.c \
../osprey-gcc/gcc/sbitmap.c \
../osprey-gcc/gcc/scan-decls.c \
../osprey-gcc/gcc/scan.c \
../osprey-gcc/gcc/sched-deps.c \
../osprey-gcc/gcc/sched-ebb.c \
../osprey-gcc/gcc/sched-rgn.c \
../osprey-gcc/gcc/sched-vis.c \
../osprey-gcc/gcc/sdbout.c \
../osprey-gcc/gcc/simplify-rtx.c \
../osprey-gcc/gcc/sreal.c \
../osprey-gcc/gcc/stmt.c \
../osprey-gcc/gcc/stor-layout.c \
../osprey-gcc/gcc/stringpool.c \
../osprey-gcc/gcc/stub-objc.c \
../osprey-gcc/gcc/targhooks.c \
../osprey-gcc/gcc/timevar.c \
../osprey-gcc/gcc/tlink.c \
../osprey-gcc/gcc/toplev.c \
../osprey-gcc/gcc/tracer.c \
../osprey-gcc/gcc/tree-browser.c \
../osprey-gcc/gcc/tree-cfg.c \
../osprey-gcc/gcc/tree-chrec.c \
../osprey-gcc/gcc/tree-complex.c \
../osprey-gcc/gcc/tree-data-ref.c \
../osprey-gcc/gcc/tree-dfa.c \
../osprey-gcc/gcc/tree-dump.c \
../osprey-gcc/gcc/tree-eh.c \
../osprey-gcc/gcc/tree-gimple.c \
../osprey-gcc/gcc/tree-if-conv.c \
../osprey-gcc/gcc/tree-inline.c \
../osprey-gcc/gcc/tree-into-ssa.c \
../osprey-gcc/gcc/tree-iterator.c \
../osprey-gcc/gcc/tree-loop-linear.c \
../osprey-gcc/gcc/tree-mudflap.c \
../osprey-gcc/gcc/tree-nested.c \
../osprey-gcc/gcc/tree-nomudflap.c \
../osprey-gcc/gcc/tree-nrv.c \
../osprey-gcc/gcc/tree-optimize.c \
../osprey-gcc/gcc/tree-outof-ssa.c \
../osprey-gcc/gcc/tree-phinodes.c \
../osprey-gcc/gcc/tree-pretty-print.c \
../osprey-gcc/gcc/tree-profile.c \
../osprey-gcc/gcc/tree-scalar-evolution.c \
../osprey-gcc/gcc/tree-sra.c \
../osprey-gcc/gcc/tree-ssa-alias.c \
../osprey-gcc/gcc/tree-ssa-ccp.c \
../osprey-gcc/gcc/tree-ssa-copy.c \
../osprey-gcc/gcc/tree-ssa-copyrename.c \
../osprey-gcc/gcc/tree-ssa-dce.c \
../osprey-gcc/gcc/tree-ssa-dom.c \
../osprey-gcc/gcc/tree-ssa-dse.c \
../osprey-gcc/gcc/tree-ssa-forwprop.c \
../osprey-gcc/gcc/tree-ssa-live.c \
../osprey-gcc/gcc/tree-ssa-loop-ch.c \
../osprey-gcc/gcc/tree-ssa-loop-im.c \
../osprey-gcc/gcc/tree-ssa-loop-ivcanon.c \
../osprey-gcc/gcc/tree-ssa-loop-ivopts.c \
../osprey-gcc/gcc/tree-ssa-loop-manip.c \
../osprey-gcc/gcc/tree-ssa-loop-niter.c \
../osprey-gcc/gcc/tree-ssa-loop-unswitch.c \
../osprey-gcc/gcc/tree-ssa-loop.c \
../osprey-gcc/gcc/tree-ssa-operands.c \
../osprey-gcc/gcc/tree-ssa-phiopt.c \
../osprey-gcc/gcc/tree-ssa-pre.c \
../osprey-gcc/gcc/tree-ssa-propagate.c \
../osprey-gcc/gcc/tree-ssa-threadupdate.c \
../osprey-gcc/gcc/tree-ssa.c \
../osprey-gcc/gcc/tree-ssanames.c \
../osprey-gcc/gcc/tree-tailcall.c \
../osprey-gcc/gcc/tree-vect-analyze.c \
../osprey-gcc/gcc/tree-vect-transform.c \
../osprey-gcc/gcc/tree-vectorizer.c \
../osprey-gcc/gcc/tree-vn.c \
../osprey-gcc/gcc/tree.c \
../osprey-gcc/gcc/unwind-c.c \
../osprey-gcc/gcc/unwind-compat.c \
../osprey-gcc/gcc/unwind-dw2-fde-compat.c \
../osprey-gcc/gcc/unwind-dw2-fde-darwin.c \
../osprey-gcc/gcc/unwind-dw2-fde-glibc.c \
../osprey-gcc/gcc/unwind-dw2-fde.c \
../osprey-gcc/gcc/unwind-dw2.c \
../osprey-gcc/gcc/unwind-sjlj.c \
../osprey-gcc/gcc/value-prof.c \
../osprey-gcc/gcc/var-tracking.c \
../osprey-gcc/gcc/varasm.c \
../osprey-gcc/gcc/varray.c \
../osprey-gcc/gcc/vec.c \
../osprey-gcc/gcc/version.c \
../osprey-gcc/gcc/vmsdbgout.c \
../osprey-gcc/gcc/web.c \
../osprey-gcc/gcc/xcoffout.c 

OBJS += \
./osprey-gcc/gcc/alias.o \
./osprey-gcc/gcc/alloc-pool.o \
./osprey-gcc/gcc/attribs.o \
./osprey-gcc/gcc/bb-reorder.o \
./osprey-gcc/gcc/bitmap.o \
./osprey-gcc/gcc/bt-load.o \
./osprey-gcc/gcc/builtins.o \
./osprey-gcc/gcc/c-aux-info.o \
./osprey-gcc/gcc/c-common.o \
./osprey-gcc/gcc/c-convert.o \
./osprey-gcc/gcc/c-cppbuiltin.o \
./osprey-gcc/gcc/c-decl.o \
./osprey-gcc/gcc/c-dump.o \
./osprey-gcc/gcc/c-errors.o \
./osprey-gcc/gcc/c-format.o \
./osprey-gcc/gcc/c-gimplify.o \
./osprey-gcc/gcc/c-incpath.o \
./osprey-gcc/gcc/c-lang.o \
./osprey-gcc/gcc/c-lex.o \
./osprey-gcc/gcc/c-objc-common.o \
./osprey-gcc/gcc/c-opts.o \
./osprey-gcc/gcc/c-pch.o \
./osprey-gcc/gcc/c-ppoutput.o \
./osprey-gcc/gcc/c-pragma.o \
./osprey-gcc/gcc/c-pretty-print.o \
./osprey-gcc/gcc/c-semantics.o \
./osprey-gcc/gcc/c-typeck.o \
./osprey-gcc/gcc/caller-save.o \
./osprey-gcc/gcc/calls.o \
./osprey-gcc/gcc/cfg.o \
./osprey-gcc/gcc/cfganal.o \
./osprey-gcc/gcc/cfgbuild.o \
./osprey-gcc/gcc/cfgcleanup.o \
./osprey-gcc/gcc/cfgexpand.o \
./osprey-gcc/gcc/cfghooks.o \
./osprey-gcc/gcc/cfglayout.o \
./osprey-gcc/gcc/cfgloop.o \
./osprey-gcc/gcc/cfgloopanal.o \
./osprey-gcc/gcc/cfgloopmanip.o \
./osprey-gcc/gcc/cfgrtl.o \
./osprey-gcc/gcc/cgraph.o \
./osprey-gcc/gcc/cgraphunit.o \
./osprey-gcc/gcc/collect2.o \
./osprey-gcc/gcc/combine.o \
./osprey-gcc/gcc/conflict.o \
./osprey-gcc/gcc/convert.o \
./osprey-gcc/gcc/coverage.o \
./osprey-gcc/gcc/cppdefault.o \
./osprey-gcc/gcc/cppspec.o \
./osprey-gcc/gcc/crtstuff.o \
./osprey-gcc/gcc/cse.o \
./osprey-gcc/gcc/cselib.o \
./osprey-gcc/gcc/dbxout.o \
./osprey-gcc/gcc/ddg.o \
./osprey-gcc/gcc/debug.o \
./osprey-gcc/gcc/df.o \
./osprey-gcc/gcc/diagnostic.o \
./osprey-gcc/gcc/dojump.o \
./osprey-gcc/gcc/dominance.o \
./osprey-gcc/gcc/domwalk.o \
./osprey-gcc/gcc/dummy-conditions.o \
./osprey-gcc/gcc/dwarf2asm.o \
./osprey-gcc/gcc/dwarf2out.o \
./osprey-gcc/gcc/emit-rtl.o \
./osprey-gcc/gcc/errors.o \
./osprey-gcc/gcc/et-forest.o \
./osprey-gcc/gcc/except.o \
./osprey-gcc/gcc/explow.o \
./osprey-gcc/gcc/expmed.o \
./osprey-gcc/gcc/expr.o \
./osprey-gcc/gcc/final.o \
./osprey-gcc/gcc/fix-header.o \
./osprey-gcc/gcc/flow.o \
./osprey-gcc/gcc/fold-const.o \
./osprey-gcc/gcc/fp-test.o \
./osprey-gcc/gcc/function.o \
./osprey-gcc/gcc/gcc.o \
./osprey-gcc/gcc/gccspec.o \
./osprey-gcc/gcc/gcov-dump.o \
./osprey-gcc/gcc/gcov-io.o \
./osprey-gcc/gcc/gcov-iov.o \
./osprey-gcc/gcc/gcov.o \
./osprey-gcc/gcc/gcse.o \
./osprey-gcc/gcc/gen-protos.o \
./osprey-gcc/gcc/genattr.o \
./osprey-gcc/gcc/genattrtab.o \
./osprey-gcc/gcc/genautomata.o \
./osprey-gcc/gcc/gencheck.o \
./osprey-gcc/gcc/gencodes.o \
./osprey-gcc/gcc/genconditions.o \
./osprey-gcc/gcc/genconfig.o \
./osprey-gcc/gcc/genconstants.o \
./osprey-gcc/gcc/genemit.o \
./osprey-gcc/gcc/genextract.o \
./osprey-gcc/gcc/genflags.o \
./osprey-gcc/gcc/gengenrtl.o \
./osprey-gcc/gcc/gengtype.o \
./osprey-gcc/gcc/genmddeps.o \
./osprey-gcc/gcc/genmodes.o \
./osprey-gcc/gcc/genopinit.o \
./osprey-gcc/gcc/genoutput.o \
./osprey-gcc/gcc/genpeep.o \
./osprey-gcc/gcc/genpreds.o \
./osprey-gcc/gcc/genrecog.o \
./osprey-gcc/gcc/gensupport.o \
./osprey-gcc/gcc/ggc-common.o \
./osprey-gcc/gcc/ggc-none.o \
./osprey-gcc/gcc/ggc-page.o \
./osprey-gcc/gcc/ggc-zone.o \
./osprey-gcc/gcc/gimple-low.o \
./osprey-gcc/gcc/gimplify.o \
./osprey-gcc/gcc/global.o \
./osprey-gcc/gcc/gmon.o \
./osprey-gcc/gcc/graph.o \
./osprey-gcc/gcc/gthr-gnat.o \
./osprey-gcc/gcc/gthr-posix.o \
./osprey-gcc/gcc/haifa-sched.o \
./osprey-gcc/gcc/hooks.o \
./osprey-gcc/gcc/host-default.o \
./osprey-gcc/gcc/ifcvt.o \
./osprey-gcc/gcc/integrate.o \
./osprey-gcc/gcc/intl.o \
./osprey-gcc/gcc/jump.o \
./osprey-gcc/gcc/lambda-code.o \
./osprey-gcc/gcc/lambda-mat.o \
./osprey-gcc/gcc/lambda-trans.o \
./osprey-gcc/gcc/langhooks.o \
./osprey-gcc/gcc/lcm.o \
./osprey-gcc/gcc/libgcc2.o \
./osprey-gcc/gcc/libgcov.o \
./osprey-gcc/gcc/lists.o \
./osprey-gcc/gcc/local-alloc.o \
./osprey-gcc/gcc/loop-doloop.o \
./osprey-gcc/gcc/loop-init.o \
./osprey-gcc/gcc/loop-invariant.o \
./osprey-gcc/gcc/loop-iv.o \
./osprey-gcc/gcc/loop-unroll.o \
./osprey-gcc/gcc/loop-unswitch.o \
./osprey-gcc/gcc/loop.o \
./osprey-gcc/gcc/main.o \
./osprey-gcc/gcc/mips-tdump.o \
./osprey-gcc/gcc/mips-tfile.o \
./osprey-gcc/gcc/modulo-sched.o \
./osprey-gcc/gcc/optabs.o \
./osprey-gcc/gcc/opts.o \
./osprey-gcc/gcc/params.o \
./osprey-gcc/gcc/passes.o \
./osprey-gcc/gcc/pointer-set.o \
./osprey-gcc/gcc/postreload-gcse.o \
./osprey-gcc/gcc/postreload.o \
./osprey-gcc/gcc/predict.o \
./osprey-gcc/gcc/prefix.o \
./osprey-gcc/gcc/pretty-print.o \
./osprey-gcc/gcc/print-rtl.o \
./osprey-gcc/gcc/print-tree.o \
./osprey-gcc/gcc/profile.o \
./osprey-gcc/gcc/protoize.o \
./osprey-gcc/gcc/read-rtl.o \
./osprey-gcc/gcc/real.o \
./osprey-gcc/gcc/recog.o \
./osprey-gcc/gcc/reg-stack.o \
./osprey-gcc/gcc/regclass.o \
./osprey-gcc/gcc/regmove.o \
./osprey-gcc/gcc/regrename.o \
./osprey-gcc/gcc/reload.o \
./osprey-gcc/gcc/reload1.o \
./osprey-gcc/gcc/reorg.o \
./osprey-gcc/gcc/resource.o \
./osprey-gcc/gcc/rtl-error.o \
./osprey-gcc/gcc/rtl-profile.o \
./osprey-gcc/gcc/rtl.o \
./osprey-gcc/gcc/rtlanal.o \
./osprey-gcc/gcc/rtlhooks.o \
./osprey-gcc/gcc/sbitmap.o \
./osprey-gcc/gcc/scan-decls.o \
./osprey-gcc/gcc/scan.o \
./osprey-gcc/gcc/sched-deps.o \
./osprey-gcc/gcc/sched-ebb.o \
./osprey-gcc/gcc/sched-rgn.o \
./osprey-gcc/gcc/sched-vis.o \
./osprey-gcc/gcc/sdbout.o \
./osprey-gcc/gcc/simplify-rtx.o \
./osprey-gcc/gcc/sreal.o \
./osprey-gcc/gcc/stmt.o \
./osprey-gcc/gcc/stor-layout.o \
./osprey-gcc/gcc/stringpool.o \
./osprey-gcc/gcc/stub-objc.o \
./osprey-gcc/gcc/targhooks.o \
./osprey-gcc/gcc/timevar.o \
./osprey-gcc/gcc/tlink.o \
./osprey-gcc/gcc/toplev.o \
./osprey-gcc/gcc/tracer.o \
./osprey-gcc/gcc/tree-browser.o \
./osprey-gcc/gcc/tree-cfg.o \
./osprey-gcc/gcc/tree-chrec.o \
./osprey-gcc/gcc/tree-complex.o \
./osprey-gcc/gcc/tree-data-ref.o \
./osprey-gcc/gcc/tree-dfa.o \
./osprey-gcc/gcc/tree-dump.o \
./osprey-gcc/gcc/tree-eh.o \
./osprey-gcc/gcc/tree-gimple.o \
./osprey-gcc/gcc/tree-if-conv.o \
./osprey-gcc/gcc/tree-inline.o \
./osprey-gcc/gcc/tree-into-ssa.o \
./osprey-gcc/gcc/tree-iterator.o \
./osprey-gcc/gcc/tree-loop-linear.o \
./osprey-gcc/gcc/tree-mudflap.o \
./osprey-gcc/gcc/tree-nested.o \
./osprey-gcc/gcc/tree-nomudflap.o \
./osprey-gcc/gcc/tree-nrv.o \
./osprey-gcc/gcc/tree-optimize.o \
./osprey-gcc/gcc/tree-outof-ssa.o \
./osprey-gcc/gcc/tree-phinodes.o \
./osprey-gcc/gcc/tree-pretty-print.o \
./osprey-gcc/gcc/tree-profile.o \
./osprey-gcc/gcc/tree-scalar-evolution.o \
./osprey-gcc/gcc/tree-sra.o \
./osprey-gcc/gcc/tree-ssa-alias.o \
./osprey-gcc/gcc/tree-ssa-ccp.o \
./osprey-gcc/gcc/tree-ssa-copy.o \
./osprey-gcc/gcc/tree-ssa-copyrename.o \
./osprey-gcc/gcc/tree-ssa-dce.o \
./osprey-gcc/gcc/tree-ssa-dom.o \
./osprey-gcc/gcc/tree-ssa-dse.o \
./osprey-gcc/gcc/tree-ssa-forwprop.o \
./osprey-gcc/gcc/tree-ssa-live.o \
./osprey-gcc/gcc/tree-ssa-loop-ch.o \
./osprey-gcc/gcc/tree-ssa-loop-im.o \
./osprey-gcc/gcc/tree-ssa-loop-ivcanon.o \
./osprey-gcc/gcc/tree-ssa-loop-ivopts.o \
./osprey-gcc/gcc/tree-ssa-loop-manip.o \
./osprey-gcc/gcc/tree-ssa-loop-niter.o \
./osprey-gcc/gcc/tree-ssa-loop-unswitch.o \
./osprey-gcc/gcc/tree-ssa-loop.o \
./osprey-gcc/gcc/tree-ssa-operands.o \
./osprey-gcc/gcc/tree-ssa-phiopt.o \
./osprey-gcc/gcc/tree-ssa-pre.o \
./osprey-gcc/gcc/tree-ssa-propagate.o \
./osprey-gcc/gcc/tree-ssa-threadupdate.o \
./osprey-gcc/gcc/tree-ssa.o \
./osprey-gcc/gcc/tree-ssanames.o \
./osprey-gcc/gcc/tree-tailcall.o \
./osprey-gcc/gcc/tree-vect-analyze.o \
./osprey-gcc/gcc/tree-vect-transform.o \
./osprey-gcc/gcc/tree-vectorizer.o \
./osprey-gcc/gcc/tree-vn.o \
./osprey-gcc/gcc/tree.o \
./osprey-gcc/gcc/unwind-c.o \
./osprey-gcc/gcc/unwind-compat.o \
./osprey-gcc/gcc/unwind-dw2-fde-compat.o \
./osprey-gcc/gcc/unwind-dw2-fde-darwin.o \
./osprey-gcc/gcc/unwind-dw2-fde-glibc.o \
./osprey-gcc/gcc/unwind-dw2-fde.o \
./osprey-gcc/gcc/unwind-dw2.o \
./osprey-gcc/gcc/unwind-sjlj.o \
./osprey-gcc/gcc/value-prof.o \
./osprey-gcc/gcc/var-tracking.o \
./osprey-gcc/gcc/varasm.o \
./osprey-gcc/gcc/varray.o \
./osprey-gcc/gcc/vec.o \
./osprey-gcc/gcc/version.o \
./osprey-gcc/gcc/vmsdbgout.o \
./osprey-gcc/gcc/web.o \
./osprey-gcc/gcc/xcoffout.o 

C_DEPS += \
./osprey-gcc/gcc/alias.d \
./osprey-gcc/gcc/alloc-pool.d \
./osprey-gcc/gcc/attribs.d \
./osprey-gcc/gcc/bb-reorder.d \
./osprey-gcc/gcc/bitmap.d \
./osprey-gcc/gcc/bt-load.d \
./osprey-gcc/gcc/builtins.d \
./osprey-gcc/gcc/c-aux-info.d \
./osprey-gcc/gcc/c-common.d \
./osprey-gcc/gcc/c-convert.d \
./osprey-gcc/gcc/c-cppbuiltin.d \
./osprey-gcc/gcc/c-decl.d \
./osprey-gcc/gcc/c-dump.d \
./osprey-gcc/gcc/c-errors.d \
./osprey-gcc/gcc/c-format.d \
./osprey-gcc/gcc/c-gimplify.d \
./osprey-gcc/gcc/c-incpath.d \
./osprey-gcc/gcc/c-lang.d \
./osprey-gcc/gcc/c-lex.d \
./osprey-gcc/gcc/c-objc-common.d \
./osprey-gcc/gcc/c-opts.d \
./osprey-gcc/gcc/c-pch.d \
./osprey-gcc/gcc/c-ppoutput.d \
./osprey-gcc/gcc/c-pragma.d \
./osprey-gcc/gcc/c-pretty-print.d \
./osprey-gcc/gcc/c-semantics.d \
./osprey-gcc/gcc/c-typeck.d \
./osprey-gcc/gcc/caller-save.d \
./osprey-gcc/gcc/calls.d \
./osprey-gcc/gcc/cfg.d \
./osprey-gcc/gcc/cfganal.d \
./osprey-gcc/gcc/cfgbuild.d \
./osprey-gcc/gcc/cfgcleanup.d \
./osprey-gcc/gcc/cfgexpand.d \
./osprey-gcc/gcc/cfghooks.d \
./osprey-gcc/gcc/cfglayout.d \
./osprey-gcc/gcc/cfgloop.d \
./osprey-gcc/gcc/cfgloopanal.d \
./osprey-gcc/gcc/cfgloopmanip.d \
./osprey-gcc/gcc/cfgrtl.d \
./osprey-gcc/gcc/cgraph.d \
./osprey-gcc/gcc/cgraphunit.d \
./osprey-gcc/gcc/collect2.d \
./osprey-gcc/gcc/combine.d \
./osprey-gcc/gcc/conflict.d \
./osprey-gcc/gcc/convert.d \
./osprey-gcc/gcc/coverage.d \
./osprey-gcc/gcc/cppdefault.d \
./osprey-gcc/gcc/cppspec.d \
./osprey-gcc/gcc/crtstuff.d \
./osprey-gcc/gcc/cse.d \
./osprey-gcc/gcc/cselib.d \
./osprey-gcc/gcc/dbxout.d \
./osprey-gcc/gcc/ddg.d \
./osprey-gcc/gcc/debug.d \
./osprey-gcc/gcc/df.d \
./osprey-gcc/gcc/diagnostic.d \
./osprey-gcc/gcc/dojump.d \
./osprey-gcc/gcc/dominance.d \
./osprey-gcc/gcc/domwalk.d \
./osprey-gcc/gcc/dummy-conditions.d \
./osprey-gcc/gcc/dwarf2asm.d \
./osprey-gcc/gcc/dwarf2out.d \
./osprey-gcc/gcc/emit-rtl.d \
./osprey-gcc/gcc/errors.d \
./osprey-gcc/gcc/et-forest.d \
./osprey-gcc/gcc/except.d \
./osprey-gcc/gcc/explow.d \
./osprey-gcc/gcc/expmed.d \
./osprey-gcc/gcc/expr.d \
./osprey-gcc/gcc/final.d \
./osprey-gcc/gcc/fix-header.d \
./osprey-gcc/gcc/flow.d \
./osprey-gcc/gcc/fold-const.d \
./osprey-gcc/gcc/fp-test.d \
./osprey-gcc/gcc/function.d \
./osprey-gcc/gcc/gcc.d \
./osprey-gcc/gcc/gccspec.d \
./osprey-gcc/gcc/gcov-dump.d \
./osprey-gcc/gcc/gcov-io.d \
./osprey-gcc/gcc/gcov-iov.d \
./osprey-gcc/gcc/gcov.d \
./osprey-gcc/gcc/gcse.d \
./osprey-gcc/gcc/gen-protos.d \
./osprey-gcc/gcc/genattr.d \
./osprey-gcc/gcc/genattrtab.d \
./osprey-gcc/gcc/genautomata.d \
./osprey-gcc/gcc/gencheck.d \
./osprey-gcc/gcc/gencodes.d \
./osprey-gcc/gcc/genconditions.d \
./osprey-gcc/gcc/genconfig.d \
./osprey-gcc/gcc/genconstants.d \
./osprey-gcc/gcc/genemit.d \
./osprey-gcc/gcc/genextract.d \
./osprey-gcc/gcc/genflags.d \
./osprey-gcc/gcc/gengenrtl.d \
./osprey-gcc/gcc/gengtype.d \
./osprey-gcc/gcc/genmddeps.d \
./osprey-gcc/gcc/genmodes.d \
./osprey-gcc/gcc/genopinit.d \
./osprey-gcc/gcc/genoutput.d \
./osprey-gcc/gcc/genpeep.d \
./osprey-gcc/gcc/genpreds.d \
./osprey-gcc/gcc/genrecog.d \
./osprey-gcc/gcc/gensupport.d \
./osprey-gcc/gcc/ggc-common.d \
./osprey-gcc/gcc/ggc-none.d \
./osprey-gcc/gcc/ggc-page.d \
./osprey-gcc/gcc/ggc-zone.d \
./osprey-gcc/gcc/gimple-low.d \
./osprey-gcc/gcc/gimplify.d \
./osprey-gcc/gcc/global.d \
./osprey-gcc/gcc/gmon.d \
./osprey-gcc/gcc/graph.d \
./osprey-gcc/gcc/gthr-gnat.d \
./osprey-gcc/gcc/gthr-posix.d \
./osprey-gcc/gcc/haifa-sched.d \
./osprey-gcc/gcc/hooks.d \
./osprey-gcc/gcc/host-default.d \
./osprey-gcc/gcc/ifcvt.d \
./osprey-gcc/gcc/integrate.d \
./osprey-gcc/gcc/intl.d \
./osprey-gcc/gcc/jump.d \
./osprey-gcc/gcc/lambda-code.d \
./osprey-gcc/gcc/lambda-mat.d \
./osprey-gcc/gcc/lambda-trans.d \
./osprey-gcc/gcc/langhooks.d \
./osprey-gcc/gcc/lcm.d \
./osprey-gcc/gcc/libgcc2.d \
./osprey-gcc/gcc/libgcov.d \
./osprey-gcc/gcc/lists.d \
./osprey-gcc/gcc/local-alloc.d \
./osprey-gcc/gcc/loop-doloop.d \
./osprey-gcc/gcc/loop-init.d \
./osprey-gcc/gcc/loop-invariant.d \
./osprey-gcc/gcc/loop-iv.d \
./osprey-gcc/gcc/loop-unroll.d \
./osprey-gcc/gcc/loop-unswitch.d \
./osprey-gcc/gcc/loop.d \
./osprey-gcc/gcc/main.d \
./osprey-gcc/gcc/mips-tdump.d \
./osprey-gcc/gcc/mips-tfile.d \
./osprey-gcc/gcc/modulo-sched.d \
./osprey-gcc/gcc/optabs.d \
./osprey-gcc/gcc/opts.d \
./osprey-gcc/gcc/params.d \
./osprey-gcc/gcc/passes.d \
./osprey-gcc/gcc/pointer-set.d \
./osprey-gcc/gcc/postreload-gcse.d \
./osprey-gcc/gcc/postreload.d \
./osprey-gcc/gcc/predict.d \
./osprey-gcc/gcc/prefix.d \
./osprey-gcc/gcc/pretty-print.d \
./osprey-gcc/gcc/print-rtl.d \
./osprey-gcc/gcc/print-tree.d \
./osprey-gcc/gcc/profile.d \
./osprey-gcc/gcc/protoize.d \
./osprey-gcc/gcc/read-rtl.d \
./osprey-gcc/gcc/real.d \
./osprey-gcc/gcc/recog.d \
./osprey-gcc/gcc/reg-stack.d \
./osprey-gcc/gcc/regclass.d \
./osprey-gcc/gcc/regmove.d \
./osprey-gcc/gcc/regrename.d \
./osprey-gcc/gcc/reload.d \
./osprey-gcc/gcc/reload1.d \
./osprey-gcc/gcc/reorg.d \
./osprey-gcc/gcc/resource.d \
./osprey-gcc/gcc/rtl-error.d \
./osprey-gcc/gcc/rtl-profile.d \
./osprey-gcc/gcc/rtl.d \
./osprey-gcc/gcc/rtlanal.d \
./osprey-gcc/gcc/rtlhooks.d \
./osprey-gcc/gcc/sbitmap.d \
./osprey-gcc/gcc/scan-decls.d \
./osprey-gcc/gcc/scan.d \
./osprey-gcc/gcc/sched-deps.d \
./osprey-gcc/gcc/sched-ebb.d \
./osprey-gcc/gcc/sched-rgn.d \
./osprey-gcc/gcc/sched-vis.d \
./osprey-gcc/gcc/sdbout.d \
./osprey-gcc/gcc/simplify-rtx.d \
./osprey-gcc/gcc/sreal.d \
./osprey-gcc/gcc/stmt.d \
./osprey-gcc/gcc/stor-layout.d \
./osprey-gcc/gcc/stringpool.d \
./osprey-gcc/gcc/stub-objc.d \
./osprey-gcc/gcc/targhooks.d \
./osprey-gcc/gcc/timevar.d \
./osprey-gcc/gcc/tlink.d \
./osprey-gcc/gcc/toplev.d \
./osprey-gcc/gcc/tracer.d \
./osprey-gcc/gcc/tree-browser.d \
./osprey-gcc/gcc/tree-cfg.d \
./osprey-gcc/gcc/tree-chrec.d \
./osprey-gcc/gcc/tree-complex.d \
./osprey-gcc/gcc/tree-data-ref.d \
./osprey-gcc/gcc/tree-dfa.d \
./osprey-gcc/gcc/tree-dump.d \
./osprey-gcc/gcc/tree-eh.d \
./osprey-gcc/gcc/tree-gimple.d \
./osprey-gcc/gcc/tree-if-conv.d \
./osprey-gcc/gcc/tree-inline.d \
./osprey-gcc/gcc/tree-into-ssa.d \
./osprey-gcc/gcc/tree-iterator.d \
./osprey-gcc/gcc/tree-loop-linear.d \
./osprey-gcc/gcc/tree-mudflap.d \
./osprey-gcc/gcc/tree-nested.d \
./osprey-gcc/gcc/tree-nomudflap.d \
./osprey-gcc/gcc/tree-nrv.d \
./osprey-gcc/gcc/tree-optimize.d \
./osprey-gcc/gcc/tree-outof-ssa.d \
./osprey-gcc/gcc/tree-phinodes.d \
./osprey-gcc/gcc/tree-pretty-print.d \
./osprey-gcc/gcc/tree-profile.d \
./osprey-gcc/gcc/tree-scalar-evolution.d \
./osprey-gcc/gcc/tree-sra.d \
./osprey-gcc/gcc/tree-ssa-alias.d \
./osprey-gcc/gcc/tree-ssa-ccp.d \
./osprey-gcc/gcc/tree-ssa-copy.d \
./osprey-gcc/gcc/tree-ssa-copyrename.d \
./osprey-gcc/gcc/tree-ssa-dce.d \
./osprey-gcc/gcc/tree-ssa-dom.d \
./osprey-gcc/gcc/tree-ssa-dse.d \
./osprey-gcc/gcc/tree-ssa-forwprop.d \
./osprey-gcc/gcc/tree-ssa-live.d \
./osprey-gcc/gcc/tree-ssa-loop-ch.d \
./osprey-gcc/gcc/tree-ssa-loop-im.d \
./osprey-gcc/gcc/tree-ssa-loop-ivcanon.d \
./osprey-gcc/gcc/tree-ssa-loop-ivopts.d \
./osprey-gcc/gcc/tree-ssa-loop-manip.d \
./osprey-gcc/gcc/tree-ssa-loop-niter.d \
./osprey-gcc/gcc/tree-ssa-loop-unswitch.d \
./osprey-gcc/gcc/tree-ssa-loop.d \
./osprey-gcc/gcc/tree-ssa-operands.d \
./osprey-gcc/gcc/tree-ssa-phiopt.d \
./osprey-gcc/gcc/tree-ssa-pre.d \
./osprey-gcc/gcc/tree-ssa-propagate.d \
./osprey-gcc/gcc/tree-ssa-threadupdate.d \
./osprey-gcc/gcc/tree-ssa.d \
./osprey-gcc/gcc/tree-ssanames.d \
./osprey-gcc/gcc/tree-tailcall.d \
./osprey-gcc/gcc/tree-vect-analyze.d \
./osprey-gcc/gcc/tree-vect-transform.d \
./osprey-gcc/gcc/tree-vectorizer.d \
./osprey-gcc/gcc/tree-vn.d \
./osprey-gcc/gcc/tree.d \
./osprey-gcc/gcc/unwind-c.d \
./osprey-gcc/gcc/unwind-compat.d \
./osprey-gcc/gcc/unwind-dw2-fde-compat.d \
./osprey-gcc/gcc/unwind-dw2-fde-darwin.d \
./osprey-gcc/gcc/unwind-dw2-fde-glibc.d \
./osprey-gcc/gcc/unwind-dw2-fde.d \
./osprey-gcc/gcc/unwind-dw2.d \
./osprey-gcc/gcc/unwind-sjlj.d \
./osprey-gcc/gcc/value-prof.d \
./osprey-gcc/gcc/var-tracking.d \
./osprey-gcc/gcc/varasm.d \
./osprey-gcc/gcc/varray.d \
./osprey-gcc/gcc/vec.d \
./osprey-gcc/gcc/version.d \
./osprey-gcc/gcc/vmsdbgout.d \
./osprey-gcc/gcc/web.d \
./osprey-gcc/gcc/xcoffout.d 


# Each subdirectory must supply rules for building sources it contributes
osprey-gcc/gcc/%.o: ../osprey-gcc/gcc/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


