################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../osprey/libfi/mathlb/abs.c \
../osprey/libfi/mathlb/acos.c \
../osprey/libfi/mathlb/aimag.c \
../osprey/libfi/mathlb/aint.c \
../osprey/libfi/mathlb/alog.c \
../osprey/libfi/mathlb/alog10.c \
../osprey/libfi/mathlb/anint.c \
../osprey/libfi/mathlb/asin.c \
../osprey/libfi/mathlb/atan.c \
../osprey/libfi/mathlb/atan2.c \
../osprey/libfi/mathlb/cabs.c \
../osprey/libfi/mathlb/ccos.c \
../osprey/libfi/mathlb/cdabs.c \
../osprey/libfi/mathlb/cdcos.c \
../osprey/libfi/mathlb/cddiv.c \
../osprey/libfi/mathlb/cdexp.c \
../osprey/libfi/mathlb/cdiv.c \
../osprey/libfi/mathlb/cdlog.c \
../osprey/libfi/mathlb/cdsin.c \
../osprey/libfi/mathlb/cdsqrt.c \
../osprey/libfi/mathlb/cdtocd.c \
../osprey/libfi/mathlb/cdtod.c \
../osprey/libfi/mathlb/cdtoi.c \
../osprey/libfi/mathlb/cdton.c \
../osprey/libfi/mathlb/ceiling.c \
../osprey/libfi/mathlb/cexp.c \
../osprey/libfi/mathlb/chabs.c \
../osprey/libfi/mathlb/chcos.c \
../osprey/libfi/mathlb/chdiv.c \
../osprey/libfi/mathlb/chexp.c \
../osprey/libfi/mathlb/chlog.c \
../osprey/libfi/mathlb/chsin.c \
../osprey/libfi/mathlb/chsqrt.c \
../osprey/libfi/mathlb/chtoch.c \
../osprey/libfi/mathlb/chtoh.c \
../osprey/libfi/mathlb/chtoi.c \
../osprey/libfi/mathlb/chton.c \
../osprey/libfi/mathlb/clog.c \
../osprey/libfi/mathlb/conjg.c \
../osprey/libfi/mathlb/cos.c \
../osprey/libfi/mathlb/cosh.c \
../osprey/libfi/mathlb/cot.c \
../osprey/libfi/mathlb/csin.c \
../osprey/libfi/mathlb/csqrt.c \
../osprey/libfi/mathlb/ctoc.c \
../osprey/libfi/mathlb/ctoch.c \
../osprey/libfi/mathlb/ctoh.c \
../osprey/libfi/mathlb/ctoi.c \
../osprey/libfi/mathlb/cton.c \
../osprey/libfi/mathlb/ctor.c \
../osprey/libfi/mathlb/dabs.c \
../osprey/libfi/mathlb/dacos.c \
../osprey/libfi/mathlb/dasin.c \
../osprey/libfi/mathlb/datan.c \
../osprey/libfi/mathlb/datan2.c \
../osprey/libfi/mathlb/dconjg.c \
../osprey/libfi/mathlb/dcos.c \
../osprey/libfi/mathlb/dcosh.c \
../osprey/libfi/mathlb/dcot.c \
../osprey/libfi/mathlb/ddim.c \
../osprey/libfi/mathlb/dexp.c \
../osprey/libfi/mathlb/dim.c \
../osprey/libfi/mathlb/dimag.c \
../osprey/libfi/mathlb/dint.c \
../osprey/libfi/mathlb/dlog.c \
../osprey/libfi/mathlb/dlog10.c \
../osprey/libfi/mathlb/dmod.c \
../osprey/libfi/mathlb/dnint.c \
../osprey/libfi/mathlb/dprod.c \
../osprey/libfi/mathlb/dsign.c \
../osprey/libfi/mathlb/dsin.c \
../osprey/libfi/mathlb/dsinh.c \
../osprey/libfi/mathlb/dsqrt.c \
../osprey/libfi/mathlb/dtan.c \
../osprey/libfi/mathlb/dtanh.c \
../osprey/libfi/mathlb/dtod.c \
../osprey/libfi/mathlb/dtoi.c \
../osprey/libfi/mathlb/dton.c \
../osprey/libfi/mathlb/exp.c \
../osprey/libfi/mathlb/exponent.c \
../osprey/libfi/mathlb/floor.c \
../osprey/libfi/mathlb/fp_class_d.c \
../osprey/libfi/mathlb/fp_class_h.c \
../osprey/libfi/mathlb/fp_class_r.c \
../osprey/libfi/mathlb/fraction.c \
../osprey/libfi/mathlb/gen_ieee_cpp_macros.c \
../osprey/libfi/mathlb/habs.c \
../osprey/libfi/mathlb/hacos.c \
../osprey/libfi/mathlb/hasin.c \
../osprey/libfi/mathlb/hatan.c \
../osprey/libfi/mathlb/hatan2.c \
../osprey/libfi/mathlb/hconjg.c \
../osprey/libfi/mathlb/hcos.c \
../osprey/libfi/mathlb/hcosh.c \
../osprey/libfi/mathlb/hcot.c \
../osprey/libfi/mathlb/hdim.c \
../osprey/libfi/mathlb/hexp.c \
../osprey/libfi/mathlb/himag.c \
../osprey/libfi/mathlb/hint.c \
../osprey/libfi/mathlb/hlog.c \
../osprey/libfi/mathlb/hlog10.c \
../osprey/libfi/mathlb/hmod.c \
../osprey/libfi/mathlb/hnint.c \
../osprey/libfi/mathlb/hsign.c \
../osprey/libfi/mathlb/hsin.c \
../osprey/libfi/mathlb/hsinh.c \
../osprey/libfi/mathlb/hsqrt.c \
../osprey/libfi/mathlb/htan.c \
../osprey/libfi/mathlb/htanh.c \
../osprey/libfi/mathlb/htoh.c \
../osprey/libfi/mathlb/htoi.c \
../osprey/libfi/mathlb/hton.c \
../osprey/libfi/mathlb/htor.c \
../osprey/libfi/mathlb/iabs.c \
../osprey/libfi/mathlb/idim.c \
../osprey/libfi/mathlb/idnint.c \
../osprey/libfi/mathlb/ieee_binary_scale_d_i.c \
../osprey/libfi/mathlb/ieee_binary_scale_d_n.c \
../osprey/libfi/mathlb/ieee_binary_scale_h_i.c \
../osprey/libfi/mathlb/ieee_binary_scale_h_n.c \
../osprey/libfi/mathlb/ieee_binary_scale_r_i.c \
../osprey/libfi/mathlb/ieee_binary_scale_r_n.c \
../osprey/libfi/mathlb/ieee_class_d.c \
../osprey/libfi/mathlb/ieee_class_h.c \
../osprey/libfi/mathlb/ieee_class_r.c \
../osprey/libfi/mathlb/ieee_exponent_d.c \
../osprey/libfi/mathlb/ieee_exponent_h.c \
../osprey/libfi/mathlb/ieee_exponent_i.c \
../osprey/libfi/mathlb/ieee_exponent_i1.c \
../osprey/libfi/mathlb/ieee_exponent_i2.c \
../osprey/libfi/mathlb/ieee_exponent_if.c \
../osprey/libfi/mathlb/ieee_exponent_n.c \
../osprey/libfi/mathlb/ieee_exponent_r.c \
../osprey/libfi/mathlb/ieee_finite_d.c \
../osprey/libfi/mathlb/ieee_finite_h.c \
../osprey/libfi/mathlb/ieee_finite_r.c \
../osprey/libfi/mathlb/ieee_int.c \
../osprey/libfi/mathlb/ieee_is_nan_d.c \
../osprey/libfi/mathlb/ieee_is_nan_h.c \
../osprey/libfi/mathlb/ieee_is_nan_r.c \
../osprey/libfi/mathlb/ieee_mips.c \
../osprey/libfi/mathlb/ieee_module_support.c \
../osprey/libfi/mathlb/ieee_next_after.c \
../osprey/libfi/mathlb/ieee_remainder_d.c \
../osprey/libfi/mathlb/ieee_remainder_h.c \
../osprey/libfi/mathlb/ieee_remainder_r.c \
../osprey/libfi/mathlb/ieee_unordered.c \
../osprey/libfi/mathlb/ilen.c \
../osprey/libfi/mathlb/imod.c \
../osprey/libfi/mathlb/isign.c \
../osprey/libfi/mathlb/iso_c_binding_support.c \
../osprey/libfi/mathlb/itoi.c \
../osprey/libfi/mathlb/iton.c \
../osprey/libfi/mathlb/mod.c \
../osprey/libfi/mathlb/nabs.c \
../osprey/libfi/mathlb/ndim.c \
../osprey/libfi/mathlb/nearest.c \
../osprey/libfi/mathlb/nhnint.c \
../osprey/libfi/mathlb/nint.c \
../osprey/libfi/mathlb/nmod.c \
../osprey/libfi/mathlb/nsign.c \
../osprey/libfi/mathlb/ntoi.c \
../osprey/libfi/mathlb/nton.c \
../osprey/libfi/mathlb/proddbl.c \
../osprey/libfi/mathlb/random.c \
../osprey/libfi/mathlb/ransed.c \
../osprey/libfi/mathlb/rcis.c \
../osprey/libfi/mathlb/rrspacing.c \
../osprey/libfi/mathlb/rtoh.c \
../osprey/libfi/mathlb/rtoi.c \
../osprey/libfi/mathlb/rton.c \
../osprey/libfi/mathlb/rtor.c \
../osprey/libfi/mathlb/scale.c \
../osprey/libfi/mathlb/set_exponent.c \
../osprey/libfi/mathlb/sign.c \
../osprey/libfi/mathlb/sin.c \
../osprey/libfi/mathlb/sinh.c \
../osprey/libfi/mathlb/snglr.c \
../osprey/libfi/mathlb/spacing.c \
../osprey/libfi/mathlb/sqrt.c \
../osprey/libfi/mathlb/tan.c \
../osprey/libfi/mathlb/tanh.c 

OBJS += \
./osprey/libfi/mathlb/abs.o \
./osprey/libfi/mathlb/acos.o \
./osprey/libfi/mathlb/aimag.o \
./osprey/libfi/mathlb/aint.o \
./osprey/libfi/mathlb/alog.o \
./osprey/libfi/mathlb/alog10.o \
./osprey/libfi/mathlb/anint.o \
./osprey/libfi/mathlb/asin.o \
./osprey/libfi/mathlb/atan.o \
./osprey/libfi/mathlb/atan2.o \
./osprey/libfi/mathlb/cabs.o \
./osprey/libfi/mathlb/ccos.o \
./osprey/libfi/mathlb/cdabs.o \
./osprey/libfi/mathlb/cdcos.o \
./osprey/libfi/mathlb/cddiv.o \
./osprey/libfi/mathlb/cdexp.o \
./osprey/libfi/mathlb/cdiv.o \
./osprey/libfi/mathlb/cdlog.o \
./osprey/libfi/mathlb/cdsin.o \
./osprey/libfi/mathlb/cdsqrt.o \
./osprey/libfi/mathlb/cdtocd.o \
./osprey/libfi/mathlb/cdtod.o \
./osprey/libfi/mathlb/cdtoi.o \
./osprey/libfi/mathlb/cdton.o \
./osprey/libfi/mathlb/ceiling.o \
./osprey/libfi/mathlb/cexp.o \
./osprey/libfi/mathlb/chabs.o \
./osprey/libfi/mathlb/chcos.o \
./osprey/libfi/mathlb/chdiv.o \
./osprey/libfi/mathlb/chexp.o \
./osprey/libfi/mathlb/chlog.o \
./osprey/libfi/mathlb/chsin.o \
./osprey/libfi/mathlb/chsqrt.o \
./osprey/libfi/mathlb/chtoch.o \
./osprey/libfi/mathlb/chtoh.o \
./osprey/libfi/mathlb/chtoi.o \
./osprey/libfi/mathlb/chton.o \
./osprey/libfi/mathlb/clog.o \
./osprey/libfi/mathlb/conjg.o \
./osprey/libfi/mathlb/cos.o \
./osprey/libfi/mathlb/cosh.o \
./osprey/libfi/mathlb/cot.o \
./osprey/libfi/mathlb/csin.o \
./osprey/libfi/mathlb/csqrt.o \
./osprey/libfi/mathlb/ctoc.o \
./osprey/libfi/mathlb/ctoch.o \
./osprey/libfi/mathlb/ctoh.o \
./osprey/libfi/mathlb/ctoi.o \
./osprey/libfi/mathlb/cton.o \
./osprey/libfi/mathlb/ctor.o \
./osprey/libfi/mathlb/dabs.o \
./osprey/libfi/mathlb/dacos.o \
./osprey/libfi/mathlb/dasin.o \
./osprey/libfi/mathlb/datan.o \
./osprey/libfi/mathlb/datan2.o \
./osprey/libfi/mathlb/dconjg.o \
./osprey/libfi/mathlb/dcos.o \
./osprey/libfi/mathlb/dcosh.o \
./osprey/libfi/mathlb/dcot.o \
./osprey/libfi/mathlb/ddim.o \
./osprey/libfi/mathlb/dexp.o \
./osprey/libfi/mathlb/dim.o \
./osprey/libfi/mathlb/dimag.o \
./osprey/libfi/mathlb/dint.o \
./osprey/libfi/mathlb/dlog.o \
./osprey/libfi/mathlb/dlog10.o \
./osprey/libfi/mathlb/dmod.o \
./osprey/libfi/mathlb/dnint.o \
./osprey/libfi/mathlb/dprod.o \
./osprey/libfi/mathlb/dsign.o \
./osprey/libfi/mathlb/dsin.o \
./osprey/libfi/mathlb/dsinh.o \
./osprey/libfi/mathlb/dsqrt.o \
./osprey/libfi/mathlb/dtan.o \
./osprey/libfi/mathlb/dtanh.o \
./osprey/libfi/mathlb/dtod.o \
./osprey/libfi/mathlb/dtoi.o \
./osprey/libfi/mathlb/dton.o \
./osprey/libfi/mathlb/exp.o \
./osprey/libfi/mathlb/exponent.o \
./osprey/libfi/mathlb/floor.o \
./osprey/libfi/mathlb/fp_class_d.o \
./osprey/libfi/mathlb/fp_class_h.o \
./osprey/libfi/mathlb/fp_class_r.o \
./osprey/libfi/mathlb/fraction.o \
./osprey/libfi/mathlb/gen_ieee_cpp_macros.o \
./osprey/libfi/mathlb/habs.o \
./osprey/libfi/mathlb/hacos.o \
./osprey/libfi/mathlb/hasin.o \
./osprey/libfi/mathlb/hatan.o \
./osprey/libfi/mathlb/hatan2.o \
./osprey/libfi/mathlb/hconjg.o \
./osprey/libfi/mathlb/hcos.o \
./osprey/libfi/mathlb/hcosh.o \
./osprey/libfi/mathlb/hcot.o \
./osprey/libfi/mathlb/hdim.o \
./osprey/libfi/mathlb/hexp.o \
./osprey/libfi/mathlb/himag.o \
./osprey/libfi/mathlb/hint.o \
./osprey/libfi/mathlb/hlog.o \
./osprey/libfi/mathlb/hlog10.o \
./osprey/libfi/mathlb/hmod.o \
./osprey/libfi/mathlb/hnint.o \
./osprey/libfi/mathlb/hsign.o \
./osprey/libfi/mathlb/hsin.o \
./osprey/libfi/mathlb/hsinh.o \
./osprey/libfi/mathlb/hsqrt.o \
./osprey/libfi/mathlb/htan.o \
./osprey/libfi/mathlb/htanh.o \
./osprey/libfi/mathlb/htoh.o \
./osprey/libfi/mathlb/htoi.o \
./osprey/libfi/mathlb/hton.o \
./osprey/libfi/mathlb/htor.o \
./osprey/libfi/mathlb/iabs.o \
./osprey/libfi/mathlb/idim.o \
./osprey/libfi/mathlb/idnint.o \
./osprey/libfi/mathlb/ieee_binary_scale_d_i.o \
./osprey/libfi/mathlb/ieee_binary_scale_d_n.o \
./osprey/libfi/mathlb/ieee_binary_scale_h_i.o \
./osprey/libfi/mathlb/ieee_binary_scale_h_n.o \
./osprey/libfi/mathlb/ieee_binary_scale_r_i.o \
./osprey/libfi/mathlb/ieee_binary_scale_r_n.o \
./osprey/libfi/mathlb/ieee_class_d.o \
./osprey/libfi/mathlb/ieee_class_h.o \
./osprey/libfi/mathlb/ieee_class_r.o \
./osprey/libfi/mathlb/ieee_exponent_d.o \
./osprey/libfi/mathlb/ieee_exponent_h.o \
./osprey/libfi/mathlb/ieee_exponent_i.o \
./osprey/libfi/mathlb/ieee_exponent_i1.o \
./osprey/libfi/mathlb/ieee_exponent_i2.o \
./osprey/libfi/mathlb/ieee_exponent_if.o \
./osprey/libfi/mathlb/ieee_exponent_n.o \
./osprey/libfi/mathlb/ieee_exponent_r.o \
./osprey/libfi/mathlb/ieee_finite_d.o \
./osprey/libfi/mathlb/ieee_finite_h.o \
./osprey/libfi/mathlb/ieee_finite_r.o \
./osprey/libfi/mathlb/ieee_int.o \
./osprey/libfi/mathlb/ieee_is_nan_d.o \
./osprey/libfi/mathlb/ieee_is_nan_h.o \
./osprey/libfi/mathlb/ieee_is_nan_r.o \
./osprey/libfi/mathlb/ieee_mips.o \
./osprey/libfi/mathlb/ieee_module_support.o \
./osprey/libfi/mathlb/ieee_next_after.o \
./osprey/libfi/mathlb/ieee_remainder_d.o \
./osprey/libfi/mathlb/ieee_remainder_h.o \
./osprey/libfi/mathlb/ieee_remainder_r.o \
./osprey/libfi/mathlb/ieee_unordered.o \
./osprey/libfi/mathlb/ilen.o \
./osprey/libfi/mathlb/imod.o \
./osprey/libfi/mathlb/isign.o \
./osprey/libfi/mathlb/iso_c_binding_support.o \
./osprey/libfi/mathlb/itoi.o \
./osprey/libfi/mathlb/iton.o \
./osprey/libfi/mathlb/mod.o \
./osprey/libfi/mathlb/nabs.o \
./osprey/libfi/mathlb/ndim.o \
./osprey/libfi/mathlb/nearest.o \
./osprey/libfi/mathlb/nhnint.o \
./osprey/libfi/mathlb/nint.o \
./osprey/libfi/mathlb/nmod.o \
./osprey/libfi/mathlb/nsign.o \
./osprey/libfi/mathlb/ntoi.o \
./osprey/libfi/mathlb/nton.o \
./osprey/libfi/mathlb/proddbl.o \
./osprey/libfi/mathlb/random.o \
./osprey/libfi/mathlb/ransed.o \
./osprey/libfi/mathlb/rcis.o \
./osprey/libfi/mathlb/rrspacing.o \
./osprey/libfi/mathlb/rtoh.o \
./osprey/libfi/mathlb/rtoi.o \
./osprey/libfi/mathlb/rton.o \
./osprey/libfi/mathlb/rtor.o \
./osprey/libfi/mathlb/scale.o \
./osprey/libfi/mathlb/set_exponent.o \
./osprey/libfi/mathlb/sign.o \
./osprey/libfi/mathlb/sin.o \
./osprey/libfi/mathlb/sinh.o \
./osprey/libfi/mathlb/snglr.o \
./osprey/libfi/mathlb/spacing.o \
./osprey/libfi/mathlb/sqrt.o \
./osprey/libfi/mathlb/tan.o \
./osprey/libfi/mathlb/tanh.o 

C_DEPS += \
./osprey/libfi/mathlb/abs.d \
./osprey/libfi/mathlb/acos.d \
./osprey/libfi/mathlb/aimag.d \
./osprey/libfi/mathlb/aint.d \
./osprey/libfi/mathlb/alog.d \
./osprey/libfi/mathlb/alog10.d \
./osprey/libfi/mathlb/anint.d \
./osprey/libfi/mathlb/asin.d \
./osprey/libfi/mathlb/atan.d \
./osprey/libfi/mathlb/atan2.d \
./osprey/libfi/mathlb/cabs.d \
./osprey/libfi/mathlb/ccos.d \
./osprey/libfi/mathlb/cdabs.d \
./osprey/libfi/mathlb/cdcos.d \
./osprey/libfi/mathlb/cddiv.d \
./osprey/libfi/mathlb/cdexp.d \
./osprey/libfi/mathlb/cdiv.d \
./osprey/libfi/mathlb/cdlog.d \
./osprey/libfi/mathlb/cdsin.d \
./osprey/libfi/mathlb/cdsqrt.d \
./osprey/libfi/mathlb/cdtocd.d \
./osprey/libfi/mathlb/cdtod.d \
./osprey/libfi/mathlb/cdtoi.d \
./osprey/libfi/mathlb/cdton.d \
./osprey/libfi/mathlb/ceiling.d \
./osprey/libfi/mathlb/cexp.d \
./osprey/libfi/mathlb/chabs.d \
./osprey/libfi/mathlb/chcos.d \
./osprey/libfi/mathlb/chdiv.d \
./osprey/libfi/mathlb/chexp.d \
./osprey/libfi/mathlb/chlog.d \
./osprey/libfi/mathlb/chsin.d \
./osprey/libfi/mathlb/chsqrt.d \
./osprey/libfi/mathlb/chtoch.d \
./osprey/libfi/mathlb/chtoh.d \
./osprey/libfi/mathlb/chtoi.d \
./osprey/libfi/mathlb/chton.d \
./osprey/libfi/mathlb/clog.d \
./osprey/libfi/mathlb/conjg.d \
./osprey/libfi/mathlb/cos.d \
./osprey/libfi/mathlb/cosh.d \
./osprey/libfi/mathlb/cot.d \
./osprey/libfi/mathlb/csin.d \
./osprey/libfi/mathlb/csqrt.d \
./osprey/libfi/mathlb/ctoc.d \
./osprey/libfi/mathlb/ctoch.d \
./osprey/libfi/mathlb/ctoh.d \
./osprey/libfi/mathlb/ctoi.d \
./osprey/libfi/mathlb/cton.d \
./osprey/libfi/mathlb/ctor.d \
./osprey/libfi/mathlb/dabs.d \
./osprey/libfi/mathlb/dacos.d \
./osprey/libfi/mathlb/dasin.d \
./osprey/libfi/mathlb/datan.d \
./osprey/libfi/mathlb/datan2.d \
./osprey/libfi/mathlb/dconjg.d \
./osprey/libfi/mathlb/dcos.d \
./osprey/libfi/mathlb/dcosh.d \
./osprey/libfi/mathlb/dcot.d \
./osprey/libfi/mathlb/ddim.d \
./osprey/libfi/mathlb/dexp.d \
./osprey/libfi/mathlb/dim.d \
./osprey/libfi/mathlb/dimag.d \
./osprey/libfi/mathlb/dint.d \
./osprey/libfi/mathlb/dlog.d \
./osprey/libfi/mathlb/dlog10.d \
./osprey/libfi/mathlb/dmod.d \
./osprey/libfi/mathlb/dnint.d \
./osprey/libfi/mathlb/dprod.d \
./osprey/libfi/mathlb/dsign.d \
./osprey/libfi/mathlb/dsin.d \
./osprey/libfi/mathlb/dsinh.d \
./osprey/libfi/mathlb/dsqrt.d \
./osprey/libfi/mathlb/dtan.d \
./osprey/libfi/mathlb/dtanh.d \
./osprey/libfi/mathlb/dtod.d \
./osprey/libfi/mathlb/dtoi.d \
./osprey/libfi/mathlb/dton.d \
./osprey/libfi/mathlb/exp.d \
./osprey/libfi/mathlb/exponent.d \
./osprey/libfi/mathlb/floor.d \
./osprey/libfi/mathlb/fp_class_d.d \
./osprey/libfi/mathlb/fp_class_h.d \
./osprey/libfi/mathlb/fp_class_r.d \
./osprey/libfi/mathlb/fraction.d \
./osprey/libfi/mathlb/gen_ieee_cpp_macros.d \
./osprey/libfi/mathlb/habs.d \
./osprey/libfi/mathlb/hacos.d \
./osprey/libfi/mathlb/hasin.d \
./osprey/libfi/mathlb/hatan.d \
./osprey/libfi/mathlb/hatan2.d \
./osprey/libfi/mathlb/hconjg.d \
./osprey/libfi/mathlb/hcos.d \
./osprey/libfi/mathlb/hcosh.d \
./osprey/libfi/mathlb/hcot.d \
./osprey/libfi/mathlb/hdim.d \
./osprey/libfi/mathlb/hexp.d \
./osprey/libfi/mathlb/himag.d \
./osprey/libfi/mathlb/hint.d \
./osprey/libfi/mathlb/hlog.d \
./osprey/libfi/mathlb/hlog10.d \
./osprey/libfi/mathlb/hmod.d \
./osprey/libfi/mathlb/hnint.d \
./osprey/libfi/mathlb/hsign.d \
./osprey/libfi/mathlb/hsin.d \
./osprey/libfi/mathlb/hsinh.d \
./osprey/libfi/mathlb/hsqrt.d \
./osprey/libfi/mathlb/htan.d \
./osprey/libfi/mathlb/htanh.d \
./osprey/libfi/mathlb/htoh.d \
./osprey/libfi/mathlb/htoi.d \
./osprey/libfi/mathlb/hton.d \
./osprey/libfi/mathlb/htor.d \
./osprey/libfi/mathlb/iabs.d \
./osprey/libfi/mathlb/idim.d \
./osprey/libfi/mathlb/idnint.d \
./osprey/libfi/mathlb/ieee_binary_scale_d_i.d \
./osprey/libfi/mathlb/ieee_binary_scale_d_n.d \
./osprey/libfi/mathlb/ieee_binary_scale_h_i.d \
./osprey/libfi/mathlb/ieee_binary_scale_h_n.d \
./osprey/libfi/mathlb/ieee_binary_scale_r_i.d \
./osprey/libfi/mathlb/ieee_binary_scale_r_n.d \
./osprey/libfi/mathlb/ieee_class_d.d \
./osprey/libfi/mathlb/ieee_class_h.d \
./osprey/libfi/mathlb/ieee_class_r.d \
./osprey/libfi/mathlb/ieee_exponent_d.d \
./osprey/libfi/mathlb/ieee_exponent_h.d \
./osprey/libfi/mathlb/ieee_exponent_i.d \
./osprey/libfi/mathlb/ieee_exponent_i1.d \
./osprey/libfi/mathlb/ieee_exponent_i2.d \
./osprey/libfi/mathlb/ieee_exponent_if.d \
./osprey/libfi/mathlb/ieee_exponent_n.d \
./osprey/libfi/mathlb/ieee_exponent_r.d \
./osprey/libfi/mathlb/ieee_finite_d.d \
./osprey/libfi/mathlb/ieee_finite_h.d \
./osprey/libfi/mathlb/ieee_finite_r.d \
./osprey/libfi/mathlb/ieee_int.d \
./osprey/libfi/mathlb/ieee_is_nan_d.d \
./osprey/libfi/mathlb/ieee_is_nan_h.d \
./osprey/libfi/mathlb/ieee_is_nan_r.d \
./osprey/libfi/mathlb/ieee_mips.d \
./osprey/libfi/mathlb/ieee_module_support.d \
./osprey/libfi/mathlb/ieee_next_after.d \
./osprey/libfi/mathlb/ieee_remainder_d.d \
./osprey/libfi/mathlb/ieee_remainder_h.d \
./osprey/libfi/mathlb/ieee_remainder_r.d \
./osprey/libfi/mathlb/ieee_unordered.d \
./osprey/libfi/mathlb/ilen.d \
./osprey/libfi/mathlb/imod.d \
./osprey/libfi/mathlb/isign.d \
./osprey/libfi/mathlb/iso_c_binding_support.d \
./osprey/libfi/mathlb/itoi.d \
./osprey/libfi/mathlb/iton.d \
./osprey/libfi/mathlb/mod.d \
./osprey/libfi/mathlb/nabs.d \
./osprey/libfi/mathlb/ndim.d \
./osprey/libfi/mathlb/nearest.d \
./osprey/libfi/mathlb/nhnint.d \
./osprey/libfi/mathlb/nint.d \
./osprey/libfi/mathlb/nmod.d \
./osprey/libfi/mathlb/nsign.d \
./osprey/libfi/mathlb/ntoi.d \
./osprey/libfi/mathlb/nton.d \
./osprey/libfi/mathlb/proddbl.d \
./osprey/libfi/mathlb/random.d \
./osprey/libfi/mathlb/ransed.d \
./osprey/libfi/mathlb/rcis.d \
./osprey/libfi/mathlb/rrspacing.d \
./osprey/libfi/mathlb/rtoh.d \
./osprey/libfi/mathlb/rtoi.d \
./osprey/libfi/mathlb/rton.d \
./osprey/libfi/mathlb/rtor.d \
./osprey/libfi/mathlb/scale.d \
./osprey/libfi/mathlb/set_exponent.d \
./osprey/libfi/mathlb/sign.d \
./osprey/libfi/mathlb/sin.d \
./osprey/libfi/mathlb/sinh.d \
./osprey/libfi/mathlb/snglr.d \
./osprey/libfi/mathlb/spacing.d \
./osprey/libfi/mathlb/sqrt.d \
./osprey/libfi/mathlb/tan.d \
./osprey/libfi/mathlb/tanh.d 


# Each subdirectory must supply rules for building sources it contributes
osprey/libfi/mathlb/%.o: ../osprey/libfi/mathlb/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


