################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../osprey/libfi/mpp_reduce/all_p_2.c \
../osprey/libfi/mpp_reduce/all_p_3.c \
../osprey/libfi/mpp_reduce/all_p_4.c \
../osprey/libfi/mpp_reduce/all_p_5.c \
../osprey/libfi/mpp_reduce/all_p_6.c \
../osprey/libfi/mpp_reduce/all_p_7.c \
../osprey/libfi/mpp_reduce/all_s_2.c \
../osprey/libfi/mpp_reduce/all_s_3.c \
../osprey/libfi/mpp_reduce/all_s_4.c \
../osprey/libfi/mpp_reduce/all_s_5.c \
../osprey/libfi/mpp_reduce/all_s_6.c \
../osprey/libfi/mpp_reduce/all_s_7.c \
../osprey/libfi/mpp_reduce/any_p_2.c \
../osprey/libfi/mpp_reduce/any_p_3.c \
../osprey/libfi/mpp_reduce/any_p_4.c \
../osprey/libfi/mpp_reduce/any_p_5.c \
../osprey/libfi/mpp_reduce/any_p_6.c \
../osprey/libfi/mpp_reduce/any_p_7.c \
../osprey/libfi/mpp_reduce/any_s_2.c \
../osprey/libfi/mpp_reduce/any_s_3.c \
../osprey/libfi/mpp_reduce/any_s_4.c \
../osprey/libfi/mpp_reduce/any_s_5.c \
../osprey/libfi/mpp_reduce/any_s_6.c \
../osprey/libfi/mpp_reduce/any_s_7.c \
../osprey/libfi/mpp_reduce/count_p_2.c \
../osprey/libfi/mpp_reduce/count_p_3.c \
../osprey/libfi/mpp_reduce/count_p_4.c \
../osprey/libfi/mpp_reduce/count_p_5.c \
../osprey/libfi/mpp_reduce/count_p_6.c \
../osprey/libfi/mpp_reduce/count_p_7.c \
../osprey/libfi/mpp_reduce/count_s_2.c \
../osprey/libfi/mpp_reduce/count_s_3.c \
../osprey/libfi/mpp_reduce/count_s_4.c \
../osprey/libfi/mpp_reduce/count_s_5.c \
../osprey/libfi/mpp_reduce/count_s_6.c \
../osprey/libfi/mpp_reduce/count_s_7.c \
../osprey/libfi/mpp_reduce/maxloc_p_1.c \
../osprey/libfi/mpp_reduce/maxloc_p_2.c \
../osprey/libfi/mpp_reduce/maxloc_p_3.c \
../osprey/libfi/mpp_reduce/maxloc_p_4.c \
../osprey/libfi/mpp_reduce/maxloc_p_5.c \
../osprey/libfi/mpp_reduce/maxloc_p_6.c \
../osprey/libfi/mpp_reduce/maxloc_p_7.c \
../osprey/libfi/mpp_reduce/maxloc_s_1.c \
../osprey/libfi/mpp_reduce/maxloc_s_2.c \
../osprey/libfi/mpp_reduce/maxloc_s_3.c \
../osprey/libfi/mpp_reduce/maxloc_s_4.c \
../osprey/libfi/mpp_reduce/maxloc_s_5.c \
../osprey/libfi/mpp_reduce/maxloc_s_6.c \
../osprey/libfi/mpp_reduce/maxloc_s_7.c \
../osprey/libfi/mpp_reduce/maxval_p_2.c \
../osprey/libfi/mpp_reduce/maxval_p_3.c \
../osprey/libfi/mpp_reduce/maxval_p_4.c \
../osprey/libfi/mpp_reduce/maxval_p_5.c \
../osprey/libfi/mpp_reduce/maxval_p_6.c \
../osprey/libfi/mpp_reduce/maxval_p_7.c \
../osprey/libfi/mpp_reduce/maxval_s_2.c \
../osprey/libfi/mpp_reduce/maxval_s_3.c \
../osprey/libfi/mpp_reduce/maxval_s_4.c \
../osprey/libfi/mpp_reduce/maxval_s_5.c \
../osprey/libfi/mpp_reduce/maxval_s_6.c \
../osprey/libfi/mpp_reduce/maxval_s_7.c \
../osprey/libfi/mpp_reduce/minloc_p_1.c \
../osprey/libfi/mpp_reduce/minloc_p_2.c \
../osprey/libfi/mpp_reduce/minloc_p_3.c \
../osprey/libfi/mpp_reduce/minloc_p_4.c \
../osprey/libfi/mpp_reduce/minloc_p_5.c \
../osprey/libfi/mpp_reduce/minloc_p_6.c \
../osprey/libfi/mpp_reduce/minloc_p_7.c \
../osprey/libfi/mpp_reduce/minloc_s_1.c \
../osprey/libfi/mpp_reduce/minloc_s_2.c \
../osprey/libfi/mpp_reduce/minloc_s_3.c \
../osprey/libfi/mpp_reduce/minloc_s_4.c \
../osprey/libfi/mpp_reduce/minloc_s_5.c \
../osprey/libfi/mpp_reduce/minloc_s_6.c \
../osprey/libfi/mpp_reduce/minloc_s_7.c \
../osprey/libfi/mpp_reduce/minval_p_2.c \
../osprey/libfi/mpp_reduce/minval_p_3.c \
../osprey/libfi/mpp_reduce/minval_p_4.c \
../osprey/libfi/mpp_reduce/minval_p_5.c \
../osprey/libfi/mpp_reduce/minval_p_6.c \
../osprey/libfi/mpp_reduce/minval_p_7.c \
../osprey/libfi/mpp_reduce/minval_s_2.c \
../osprey/libfi/mpp_reduce/minval_s_3.c \
../osprey/libfi/mpp_reduce/minval_s_4.c \
../osprey/libfi/mpp_reduce/minval_s_5.c \
../osprey/libfi/mpp_reduce/minval_s_6.c \
../osprey/libfi/mpp_reduce/minval_s_7.c \
../osprey/libfi/mpp_reduce/prod_p_2.c \
../osprey/libfi/mpp_reduce/prod_p_3.c \
../osprey/libfi/mpp_reduce/prod_p_4.c \
../osprey/libfi/mpp_reduce/prod_p_5.c \
../osprey/libfi/mpp_reduce/prod_p_6.c \
../osprey/libfi/mpp_reduce/prod_p_7.c \
../osprey/libfi/mpp_reduce/prod_s_2.c \
../osprey/libfi/mpp_reduce/prod_s_3.c \
../osprey/libfi/mpp_reduce/prod_s_4.c \
../osprey/libfi/mpp_reduce/prod_s_5.c \
../osprey/libfi/mpp_reduce/prod_s_6.c \
../osprey/libfi/mpp_reduce/prod_s_7.c \
../osprey/libfi/mpp_reduce/sum_p_2.c \
../osprey/libfi/mpp_reduce/sum_p_3.c \
../osprey/libfi/mpp_reduce/sum_p_4.c \
../osprey/libfi/mpp_reduce/sum_p_5.c \
../osprey/libfi/mpp_reduce/sum_p_6.c \
../osprey/libfi/mpp_reduce/sum_p_7.c \
../osprey/libfi/mpp_reduce/sum_s_2.c \
../osprey/libfi/mpp_reduce/sum_s_3.c \
../osprey/libfi/mpp_reduce/sum_s_4.c \
../osprey/libfi/mpp_reduce/sum_s_5.c \
../osprey/libfi/mpp_reduce/sum_s_6.c \
../osprey/libfi/mpp_reduce/sum_s_7.c 

OBJS += \
./osprey/libfi/mpp_reduce/all_p_2.o \
./osprey/libfi/mpp_reduce/all_p_3.o \
./osprey/libfi/mpp_reduce/all_p_4.o \
./osprey/libfi/mpp_reduce/all_p_5.o \
./osprey/libfi/mpp_reduce/all_p_6.o \
./osprey/libfi/mpp_reduce/all_p_7.o \
./osprey/libfi/mpp_reduce/all_s_2.o \
./osprey/libfi/mpp_reduce/all_s_3.o \
./osprey/libfi/mpp_reduce/all_s_4.o \
./osprey/libfi/mpp_reduce/all_s_5.o \
./osprey/libfi/mpp_reduce/all_s_6.o \
./osprey/libfi/mpp_reduce/all_s_7.o \
./osprey/libfi/mpp_reduce/any_p_2.o \
./osprey/libfi/mpp_reduce/any_p_3.o \
./osprey/libfi/mpp_reduce/any_p_4.o \
./osprey/libfi/mpp_reduce/any_p_5.o \
./osprey/libfi/mpp_reduce/any_p_6.o \
./osprey/libfi/mpp_reduce/any_p_7.o \
./osprey/libfi/mpp_reduce/any_s_2.o \
./osprey/libfi/mpp_reduce/any_s_3.o \
./osprey/libfi/mpp_reduce/any_s_4.o \
./osprey/libfi/mpp_reduce/any_s_5.o \
./osprey/libfi/mpp_reduce/any_s_6.o \
./osprey/libfi/mpp_reduce/any_s_7.o \
./osprey/libfi/mpp_reduce/count_p_2.o \
./osprey/libfi/mpp_reduce/count_p_3.o \
./osprey/libfi/mpp_reduce/count_p_4.o \
./osprey/libfi/mpp_reduce/count_p_5.o \
./osprey/libfi/mpp_reduce/count_p_6.o \
./osprey/libfi/mpp_reduce/count_p_7.o \
./osprey/libfi/mpp_reduce/count_s_2.o \
./osprey/libfi/mpp_reduce/count_s_3.o \
./osprey/libfi/mpp_reduce/count_s_4.o \
./osprey/libfi/mpp_reduce/count_s_5.o \
./osprey/libfi/mpp_reduce/count_s_6.o \
./osprey/libfi/mpp_reduce/count_s_7.o \
./osprey/libfi/mpp_reduce/maxloc_p_1.o \
./osprey/libfi/mpp_reduce/maxloc_p_2.o \
./osprey/libfi/mpp_reduce/maxloc_p_3.o \
./osprey/libfi/mpp_reduce/maxloc_p_4.o \
./osprey/libfi/mpp_reduce/maxloc_p_5.o \
./osprey/libfi/mpp_reduce/maxloc_p_6.o \
./osprey/libfi/mpp_reduce/maxloc_p_7.o \
./osprey/libfi/mpp_reduce/maxloc_s_1.o \
./osprey/libfi/mpp_reduce/maxloc_s_2.o \
./osprey/libfi/mpp_reduce/maxloc_s_3.o \
./osprey/libfi/mpp_reduce/maxloc_s_4.o \
./osprey/libfi/mpp_reduce/maxloc_s_5.o \
./osprey/libfi/mpp_reduce/maxloc_s_6.o \
./osprey/libfi/mpp_reduce/maxloc_s_7.o \
./osprey/libfi/mpp_reduce/maxval_p_2.o \
./osprey/libfi/mpp_reduce/maxval_p_3.o \
./osprey/libfi/mpp_reduce/maxval_p_4.o \
./osprey/libfi/mpp_reduce/maxval_p_5.o \
./osprey/libfi/mpp_reduce/maxval_p_6.o \
./osprey/libfi/mpp_reduce/maxval_p_7.o \
./osprey/libfi/mpp_reduce/maxval_s_2.o \
./osprey/libfi/mpp_reduce/maxval_s_3.o \
./osprey/libfi/mpp_reduce/maxval_s_4.o \
./osprey/libfi/mpp_reduce/maxval_s_5.o \
./osprey/libfi/mpp_reduce/maxval_s_6.o \
./osprey/libfi/mpp_reduce/maxval_s_7.o \
./osprey/libfi/mpp_reduce/minloc_p_1.o \
./osprey/libfi/mpp_reduce/minloc_p_2.o \
./osprey/libfi/mpp_reduce/minloc_p_3.o \
./osprey/libfi/mpp_reduce/minloc_p_4.o \
./osprey/libfi/mpp_reduce/minloc_p_5.o \
./osprey/libfi/mpp_reduce/minloc_p_6.o \
./osprey/libfi/mpp_reduce/minloc_p_7.o \
./osprey/libfi/mpp_reduce/minloc_s_1.o \
./osprey/libfi/mpp_reduce/minloc_s_2.o \
./osprey/libfi/mpp_reduce/minloc_s_3.o \
./osprey/libfi/mpp_reduce/minloc_s_4.o \
./osprey/libfi/mpp_reduce/minloc_s_5.o \
./osprey/libfi/mpp_reduce/minloc_s_6.o \
./osprey/libfi/mpp_reduce/minloc_s_7.o \
./osprey/libfi/mpp_reduce/minval_p_2.o \
./osprey/libfi/mpp_reduce/minval_p_3.o \
./osprey/libfi/mpp_reduce/minval_p_4.o \
./osprey/libfi/mpp_reduce/minval_p_5.o \
./osprey/libfi/mpp_reduce/minval_p_6.o \
./osprey/libfi/mpp_reduce/minval_p_7.o \
./osprey/libfi/mpp_reduce/minval_s_2.o \
./osprey/libfi/mpp_reduce/minval_s_3.o \
./osprey/libfi/mpp_reduce/minval_s_4.o \
./osprey/libfi/mpp_reduce/minval_s_5.o \
./osprey/libfi/mpp_reduce/minval_s_6.o \
./osprey/libfi/mpp_reduce/minval_s_7.o \
./osprey/libfi/mpp_reduce/prod_p_2.o \
./osprey/libfi/mpp_reduce/prod_p_3.o \
./osprey/libfi/mpp_reduce/prod_p_4.o \
./osprey/libfi/mpp_reduce/prod_p_5.o \
./osprey/libfi/mpp_reduce/prod_p_6.o \
./osprey/libfi/mpp_reduce/prod_p_7.o \
./osprey/libfi/mpp_reduce/prod_s_2.o \
./osprey/libfi/mpp_reduce/prod_s_3.o \
./osprey/libfi/mpp_reduce/prod_s_4.o \
./osprey/libfi/mpp_reduce/prod_s_5.o \
./osprey/libfi/mpp_reduce/prod_s_6.o \
./osprey/libfi/mpp_reduce/prod_s_7.o \
./osprey/libfi/mpp_reduce/sum_p_2.o \
./osprey/libfi/mpp_reduce/sum_p_3.o \
./osprey/libfi/mpp_reduce/sum_p_4.o \
./osprey/libfi/mpp_reduce/sum_p_5.o \
./osprey/libfi/mpp_reduce/sum_p_6.o \
./osprey/libfi/mpp_reduce/sum_p_7.o \
./osprey/libfi/mpp_reduce/sum_s_2.o \
./osprey/libfi/mpp_reduce/sum_s_3.o \
./osprey/libfi/mpp_reduce/sum_s_4.o \
./osprey/libfi/mpp_reduce/sum_s_5.o \
./osprey/libfi/mpp_reduce/sum_s_6.o \
./osprey/libfi/mpp_reduce/sum_s_7.o 

C_DEPS += \
./osprey/libfi/mpp_reduce/all_p_2.d \
./osprey/libfi/mpp_reduce/all_p_3.d \
./osprey/libfi/mpp_reduce/all_p_4.d \
./osprey/libfi/mpp_reduce/all_p_5.d \
./osprey/libfi/mpp_reduce/all_p_6.d \
./osprey/libfi/mpp_reduce/all_p_7.d \
./osprey/libfi/mpp_reduce/all_s_2.d \
./osprey/libfi/mpp_reduce/all_s_3.d \
./osprey/libfi/mpp_reduce/all_s_4.d \
./osprey/libfi/mpp_reduce/all_s_5.d \
./osprey/libfi/mpp_reduce/all_s_6.d \
./osprey/libfi/mpp_reduce/all_s_7.d \
./osprey/libfi/mpp_reduce/any_p_2.d \
./osprey/libfi/mpp_reduce/any_p_3.d \
./osprey/libfi/mpp_reduce/any_p_4.d \
./osprey/libfi/mpp_reduce/any_p_5.d \
./osprey/libfi/mpp_reduce/any_p_6.d \
./osprey/libfi/mpp_reduce/any_p_7.d \
./osprey/libfi/mpp_reduce/any_s_2.d \
./osprey/libfi/mpp_reduce/any_s_3.d \
./osprey/libfi/mpp_reduce/any_s_4.d \
./osprey/libfi/mpp_reduce/any_s_5.d \
./osprey/libfi/mpp_reduce/any_s_6.d \
./osprey/libfi/mpp_reduce/any_s_7.d \
./osprey/libfi/mpp_reduce/count_p_2.d \
./osprey/libfi/mpp_reduce/count_p_3.d \
./osprey/libfi/mpp_reduce/count_p_4.d \
./osprey/libfi/mpp_reduce/count_p_5.d \
./osprey/libfi/mpp_reduce/count_p_6.d \
./osprey/libfi/mpp_reduce/count_p_7.d \
./osprey/libfi/mpp_reduce/count_s_2.d \
./osprey/libfi/mpp_reduce/count_s_3.d \
./osprey/libfi/mpp_reduce/count_s_4.d \
./osprey/libfi/mpp_reduce/count_s_5.d \
./osprey/libfi/mpp_reduce/count_s_6.d \
./osprey/libfi/mpp_reduce/count_s_7.d \
./osprey/libfi/mpp_reduce/maxloc_p_1.d \
./osprey/libfi/mpp_reduce/maxloc_p_2.d \
./osprey/libfi/mpp_reduce/maxloc_p_3.d \
./osprey/libfi/mpp_reduce/maxloc_p_4.d \
./osprey/libfi/mpp_reduce/maxloc_p_5.d \
./osprey/libfi/mpp_reduce/maxloc_p_6.d \
./osprey/libfi/mpp_reduce/maxloc_p_7.d \
./osprey/libfi/mpp_reduce/maxloc_s_1.d \
./osprey/libfi/mpp_reduce/maxloc_s_2.d \
./osprey/libfi/mpp_reduce/maxloc_s_3.d \
./osprey/libfi/mpp_reduce/maxloc_s_4.d \
./osprey/libfi/mpp_reduce/maxloc_s_5.d \
./osprey/libfi/mpp_reduce/maxloc_s_6.d \
./osprey/libfi/mpp_reduce/maxloc_s_7.d \
./osprey/libfi/mpp_reduce/maxval_p_2.d \
./osprey/libfi/mpp_reduce/maxval_p_3.d \
./osprey/libfi/mpp_reduce/maxval_p_4.d \
./osprey/libfi/mpp_reduce/maxval_p_5.d \
./osprey/libfi/mpp_reduce/maxval_p_6.d \
./osprey/libfi/mpp_reduce/maxval_p_7.d \
./osprey/libfi/mpp_reduce/maxval_s_2.d \
./osprey/libfi/mpp_reduce/maxval_s_3.d \
./osprey/libfi/mpp_reduce/maxval_s_4.d \
./osprey/libfi/mpp_reduce/maxval_s_5.d \
./osprey/libfi/mpp_reduce/maxval_s_6.d \
./osprey/libfi/mpp_reduce/maxval_s_7.d \
./osprey/libfi/mpp_reduce/minloc_p_1.d \
./osprey/libfi/mpp_reduce/minloc_p_2.d \
./osprey/libfi/mpp_reduce/minloc_p_3.d \
./osprey/libfi/mpp_reduce/minloc_p_4.d \
./osprey/libfi/mpp_reduce/minloc_p_5.d \
./osprey/libfi/mpp_reduce/minloc_p_6.d \
./osprey/libfi/mpp_reduce/minloc_p_7.d \
./osprey/libfi/mpp_reduce/minloc_s_1.d \
./osprey/libfi/mpp_reduce/minloc_s_2.d \
./osprey/libfi/mpp_reduce/minloc_s_3.d \
./osprey/libfi/mpp_reduce/minloc_s_4.d \
./osprey/libfi/mpp_reduce/minloc_s_5.d \
./osprey/libfi/mpp_reduce/minloc_s_6.d \
./osprey/libfi/mpp_reduce/minloc_s_7.d \
./osprey/libfi/mpp_reduce/minval_p_2.d \
./osprey/libfi/mpp_reduce/minval_p_3.d \
./osprey/libfi/mpp_reduce/minval_p_4.d \
./osprey/libfi/mpp_reduce/minval_p_5.d \
./osprey/libfi/mpp_reduce/minval_p_6.d \
./osprey/libfi/mpp_reduce/minval_p_7.d \
./osprey/libfi/mpp_reduce/minval_s_2.d \
./osprey/libfi/mpp_reduce/minval_s_3.d \
./osprey/libfi/mpp_reduce/minval_s_4.d \
./osprey/libfi/mpp_reduce/minval_s_5.d \
./osprey/libfi/mpp_reduce/minval_s_6.d \
./osprey/libfi/mpp_reduce/minval_s_7.d \
./osprey/libfi/mpp_reduce/prod_p_2.d \
./osprey/libfi/mpp_reduce/prod_p_3.d \
./osprey/libfi/mpp_reduce/prod_p_4.d \
./osprey/libfi/mpp_reduce/prod_p_5.d \
./osprey/libfi/mpp_reduce/prod_p_6.d \
./osprey/libfi/mpp_reduce/prod_p_7.d \
./osprey/libfi/mpp_reduce/prod_s_2.d \
./osprey/libfi/mpp_reduce/prod_s_3.d \
./osprey/libfi/mpp_reduce/prod_s_4.d \
./osprey/libfi/mpp_reduce/prod_s_5.d \
./osprey/libfi/mpp_reduce/prod_s_6.d \
./osprey/libfi/mpp_reduce/prod_s_7.d \
./osprey/libfi/mpp_reduce/sum_p_2.d \
./osprey/libfi/mpp_reduce/sum_p_3.d \
./osprey/libfi/mpp_reduce/sum_p_4.d \
./osprey/libfi/mpp_reduce/sum_p_5.d \
./osprey/libfi/mpp_reduce/sum_p_6.d \
./osprey/libfi/mpp_reduce/sum_p_7.d \
./osprey/libfi/mpp_reduce/sum_s_2.d \
./osprey/libfi/mpp_reduce/sum_s_3.d \
./osprey/libfi/mpp_reduce/sum_s_4.d \
./osprey/libfi/mpp_reduce/sum_s_5.d \
./osprey/libfi/mpp_reduce/sum_s_6.d \
./osprey/libfi/mpp_reduce/sum_s_7.d 


# Each subdirectory must supply rules for building sources it contributes
osprey/libfi/mpp_reduce/%.o: ../osprey/libfi/mpp_reduce/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


