################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../osprey/libF77/mips/quad/cq_abs.c \
../osprey/libF77/mips/quad/cq_add.c \
../osprey/libF77/mips/quad/cq_conjg.c \
../osprey/libF77/mips/quad/cq_cos.c \
../osprey/libF77/mips/quad/cq_div.c \
../osprey/libF77/mips/quad/cq_eq.c \
../osprey/libF77/mips/quad/cq_exp.c \
../osprey/libF77/mips/quad/cq_imag.c \
../osprey/libF77/mips/quad/cq_int.c \
../osprey/libF77/mips/quad/cq_log.c \
../osprey/libF77/mips/quad/cq_mul.c \
../osprey/libF77/mips/quad/cq_ne.c \
../osprey/libF77/mips/quad/cq_neg.c \
../osprey/libF77/mips/quad/cq_pow.c \
../osprey/libF77/mips/quad/cq_real.c \
../osprey/libF77/mips/quad/cq_sin.c \
../osprey/libF77/mips/quad/cq_sqrt.c \
../osprey/libF77/mips/quad/cq_sub.c \
../osprey/libF77/mips/quad/ii_qnnt.c \
../osprey/libF77/mips/quad/iiqnnt.c \
../osprey/libF77/mips/quad/iqint.c \
../osprey/libF77/mips/quad/j_qmax1.c \
../osprey/libF77/mips/quad/j_qmin1.c \
../osprey/libF77/mips/quad/ji_qnnt.c \
../osprey/libF77/mips/quad/jiqnnt.c \
../osprey/libF77/mips/quad/ki_qnnt.c \
../osprey/libF77/mips/quad/kiqnnt.c \
../osprey/libF77/mips/quad/pow_cqi.c \
../osprey/libF77/mips/quad/pow_qi.c \
../osprey/libF77/mips/quad/q_abs.c \
../osprey/libF77/mips/quad/q_acos.c \
../osprey/libF77/mips/quad/q_acosd.c \
../osprey/libF77/mips/quad/q_asin.c \
../osprey/libF77/mips/quad/q_asind.c \
../osprey/libF77/mips/quad/q_atan.c \
../osprey/libF77/mips/quad/q_atand.c \
../osprey/libF77/mips/quad/q_atn2.c \
../osprey/libF77/mips/quad/q_atn2d.c \
../osprey/libF77/mips/quad/q_cis.c \
../osprey/libF77/mips/quad/q_cmplx.c \
../osprey/libF77/mips/quad/q_cos.c \
../osprey/libF77/mips/quad/q_cosd.c \
../osprey/libF77/mips/quad/q_cosh.c \
../osprey/libF77/mips/quad/q_dim.c \
../osprey/libF77/mips/quad/q_erf.c \
../osprey/libF77/mips/quad/q_erfc.c \
../osprey/libF77/mips/quad/q_exp.c \
../osprey/libF77/mips/quad/q_gamma.c \
../osprey/libF77/mips/quad/q_int.c \
../osprey/libF77/mips/quad/q_lg10.c \
../osprey/libF77/mips/quad/q_lgamma.c \
../osprey/libF77/mips/quad/q_log.c \
../osprey/libF77/mips/quad/q_max1.c \
../osprey/libF77/mips/quad/q_min1.c \
../osprey/libF77/mips/quad/q_mod.c \
../osprey/libF77/mips/quad/q_nint.c \
../osprey/libF77/mips/quad/q_prod.c \
../osprey/libF77/mips/quad/q_sign.c \
../osprey/libF77/mips/quad/q_sin.c \
../osprey/libF77/mips/quad/q_sind.c \
../osprey/libF77/mips/quad/q_sinh.c \
../osprey/libF77/mips/quad/q_sqrt.c \
../osprey/libF77/mips/quad/q_tan.c \
../osprey/libF77/mips/quad/q_tand.c \
../osprey/libF77/mips/quad/q_tanh.c \
../osprey/libF77/mips/quad/qcis_stub.c \
../osprey/libF77/mips/quad/qdim.c \
../osprey/libF77/mips/quad/qerf_.c \
../osprey/libF77/mips/quad/qerfc_.c \
../osprey/libF77/mips/quad/qfrts.c \
../osprey/libF77/mips/quad/qint.c \
../osprey/libF77/mips/quad/qnint.c \
../osprey/libF77/mips/quad/qprod.c \
../osprey/libF77/mips/quad/qsign.c 

OBJS += \
./osprey/libF77/mips/quad/cq_abs.o \
./osprey/libF77/mips/quad/cq_add.o \
./osprey/libF77/mips/quad/cq_conjg.o \
./osprey/libF77/mips/quad/cq_cos.o \
./osprey/libF77/mips/quad/cq_div.o \
./osprey/libF77/mips/quad/cq_eq.o \
./osprey/libF77/mips/quad/cq_exp.o \
./osprey/libF77/mips/quad/cq_imag.o \
./osprey/libF77/mips/quad/cq_int.o \
./osprey/libF77/mips/quad/cq_log.o \
./osprey/libF77/mips/quad/cq_mul.o \
./osprey/libF77/mips/quad/cq_ne.o \
./osprey/libF77/mips/quad/cq_neg.o \
./osprey/libF77/mips/quad/cq_pow.o \
./osprey/libF77/mips/quad/cq_real.o \
./osprey/libF77/mips/quad/cq_sin.o \
./osprey/libF77/mips/quad/cq_sqrt.o \
./osprey/libF77/mips/quad/cq_sub.o \
./osprey/libF77/mips/quad/ii_qnnt.o \
./osprey/libF77/mips/quad/iiqnnt.o \
./osprey/libF77/mips/quad/iqint.o \
./osprey/libF77/mips/quad/j_qmax1.o \
./osprey/libF77/mips/quad/j_qmin1.o \
./osprey/libF77/mips/quad/ji_qnnt.o \
./osprey/libF77/mips/quad/jiqnnt.o \
./osprey/libF77/mips/quad/ki_qnnt.o \
./osprey/libF77/mips/quad/kiqnnt.o \
./osprey/libF77/mips/quad/pow_cqi.o \
./osprey/libF77/mips/quad/pow_qi.o \
./osprey/libF77/mips/quad/q_abs.o \
./osprey/libF77/mips/quad/q_acos.o \
./osprey/libF77/mips/quad/q_acosd.o \
./osprey/libF77/mips/quad/q_asin.o \
./osprey/libF77/mips/quad/q_asind.o \
./osprey/libF77/mips/quad/q_atan.o \
./osprey/libF77/mips/quad/q_atand.o \
./osprey/libF77/mips/quad/q_atn2.o \
./osprey/libF77/mips/quad/q_atn2d.o \
./osprey/libF77/mips/quad/q_cis.o \
./osprey/libF77/mips/quad/q_cmplx.o \
./osprey/libF77/mips/quad/q_cos.o \
./osprey/libF77/mips/quad/q_cosd.o \
./osprey/libF77/mips/quad/q_cosh.o \
./osprey/libF77/mips/quad/q_dim.o \
./osprey/libF77/mips/quad/q_erf.o \
./osprey/libF77/mips/quad/q_erfc.o \
./osprey/libF77/mips/quad/q_exp.o \
./osprey/libF77/mips/quad/q_gamma.o \
./osprey/libF77/mips/quad/q_int.o \
./osprey/libF77/mips/quad/q_lg10.o \
./osprey/libF77/mips/quad/q_lgamma.o \
./osprey/libF77/mips/quad/q_log.o \
./osprey/libF77/mips/quad/q_max1.o \
./osprey/libF77/mips/quad/q_min1.o \
./osprey/libF77/mips/quad/q_mod.o \
./osprey/libF77/mips/quad/q_nint.o \
./osprey/libF77/mips/quad/q_prod.o \
./osprey/libF77/mips/quad/q_sign.o \
./osprey/libF77/mips/quad/q_sin.o \
./osprey/libF77/mips/quad/q_sind.o \
./osprey/libF77/mips/quad/q_sinh.o \
./osprey/libF77/mips/quad/q_sqrt.o \
./osprey/libF77/mips/quad/q_tan.o \
./osprey/libF77/mips/quad/q_tand.o \
./osprey/libF77/mips/quad/q_tanh.o \
./osprey/libF77/mips/quad/qcis_stub.o \
./osprey/libF77/mips/quad/qdim.o \
./osprey/libF77/mips/quad/qerf_.o \
./osprey/libF77/mips/quad/qerfc_.o \
./osprey/libF77/mips/quad/qfrts.o \
./osprey/libF77/mips/quad/qint.o \
./osprey/libF77/mips/quad/qnint.o \
./osprey/libF77/mips/quad/qprod.o \
./osprey/libF77/mips/quad/qsign.o 

C_DEPS += \
./osprey/libF77/mips/quad/cq_abs.d \
./osprey/libF77/mips/quad/cq_add.d \
./osprey/libF77/mips/quad/cq_conjg.d \
./osprey/libF77/mips/quad/cq_cos.d \
./osprey/libF77/mips/quad/cq_div.d \
./osprey/libF77/mips/quad/cq_eq.d \
./osprey/libF77/mips/quad/cq_exp.d \
./osprey/libF77/mips/quad/cq_imag.d \
./osprey/libF77/mips/quad/cq_int.d \
./osprey/libF77/mips/quad/cq_log.d \
./osprey/libF77/mips/quad/cq_mul.d \
./osprey/libF77/mips/quad/cq_ne.d \
./osprey/libF77/mips/quad/cq_neg.d \
./osprey/libF77/mips/quad/cq_pow.d \
./osprey/libF77/mips/quad/cq_real.d \
./osprey/libF77/mips/quad/cq_sin.d \
./osprey/libF77/mips/quad/cq_sqrt.d \
./osprey/libF77/mips/quad/cq_sub.d \
./osprey/libF77/mips/quad/ii_qnnt.d \
./osprey/libF77/mips/quad/iiqnnt.d \
./osprey/libF77/mips/quad/iqint.d \
./osprey/libF77/mips/quad/j_qmax1.d \
./osprey/libF77/mips/quad/j_qmin1.d \
./osprey/libF77/mips/quad/ji_qnnt.d \
./osprey/libF77/mips/quad/jiqnnt.d \
./osprey/libF77/mips/quad/ki_qnnt.d \
./osprey/libF77/mips/quad/kiqnnt.d \
./osprey/libF77/mips/quad/pow_cqi.d \
./osprey/libF77/mips/quad/pow_qi.d \
./osprey/libF77/mips/quad/q_abs.d \
./osprey/libF77/mips/quad/q_acos.d \
./osprey/libF77/mips/quad/q_acosd.d \
./osprey/libF77/mips/quad/q_asin.d \
./osprey/libF77/mips/quad/q_asind.d \
./osprey/libF77/mips/quad/q_atan.d \
./osprey/libF77/mips/quad/q_atand.d \
./osprey/libF77/mips/quad/q_atn2.d \
./osprey/libF77/mips/quad/q_atn2d.d \
./osprey/libF77/mips/quad/q_cis.d \
./osprey/libF77/mips/quad/q_cmplx.d \
./osprey/libF77/mips/quad/q_cos.d \
./osprey/libF77/mips/quad/q_cosd.d \
./osprey/libF77/mips/quad/q_cosh.d \
./osprey/libF77/mips/quad/q_dim.d \
./osprey/libF77/mips/quad/q_erf.d \
./osprey/libF77/mips/quad/q_erfc.d \
./osprey/libF77/mips/quad/q_exp.d \
./osprey/libF77/mips/quad/q_gamma.d \
./osprey/libF77/mips/quad/q_int.d \
./osprey/libF77/mips/quad/q_lg10.d \
./osprey/libF77/mips/quad/q_lgamma.d \
./osprey/libF77/mips/quad/q_log.d \
./osprey/libF77/mips/quad/q_max1.d \
./osprey/libF77/mips/quad/q_min1.d \
./osprey/libF77/mips/quad/q_mod.d \
./osprey/libF77/mips/quad/q_nint.d \
./osprey/libF77/mips/quad/q_prod.d \
./osprey/libF77/mips/quad/q_sign.d \
./osprey/libF77/mips/quad/q_sin.d \
./osprey/libF77/mips/quad/q_sind.d \
./osprey/libF77/mips/quad/q_sinh.d \
./osprey/libF77/mips/quad/q_sqrt.d \
./osprey/libF77/mips/quad/q_tan.d \
./osprey/libF77/mips/quad/q_tand.d \
./osprey/libF77/mips/quad/q_tanh.d \
./osprey/libF77/mips/quad/qcis_stub.d \
./osprey/libF77/mips/quad/qdim.d \
./osprey/libF77/mips/quad/qerf_.d \
./osprey/libF77/mips/quad/qerfc_.d \
./osprey/libF77/mips/quad/qfrts.d \
./osprey/libF77/mips/quad/qint.d \
./osprey/libF77/mips/quad/qnint.d \
./osprey/libF77/mips/quad/qprod.d \
./osprey/libF77/mips/quad/qsign.d 


# Each subdirectory must supply rules for building sources it contributes
osprey/libF77/mips/quad/%.o: ../osprey/libF77/mips/quad/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


