################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../osprey/libU77/abort_.c \
../osprey/libU77/access_.c \
../osprey/libU77/alarm_.c \
../osprey/libU77/bes.c \
../osprey/libU77/charutil.c \
../osprey/libU77/chdir_.c \
../osprey/libU77/chmod_.c \
../osprey/libU77/cmd_line.c \
../osprey/libU77/ctime_.c \
../osprey/libU77/date_.c \
../osprey/libU77/dbes.c \
../osprey/libU77/dtime_.c \
../osprey/libU77/etime_.c \
../osprey/libU77/exit_.c \
../osprey/libU77/fdate_.c \
../osprey/libU77/gerror_.c \
../osprey/libU77/getarg_.c \
../osprey/libU77/getcwd_.c \
../osprey/libU77/getenv_.c \
../osprey/libU77/getgid_.c \
../osprey/libU77/gethostname_.c \
../osprey/libU77/getlog_.c \
../osprey/libU77/getpid_.c \
../osprey/libU77/getuid_.c \
../osprey/libU77/gmtime_.c \
../osprey/libU77/hostnm_.c \
../osprey/libU77/iargc_.c \
../osprey/libU77/ierrno_.c \
../osprey/libU77/irand_.c \
../osprey/libU77/itime_.c \
../osprey/libU77/legacy_access_.c \
../osprey/libU77/legacy_alarm_.c \
../osprey/libU77/legacy_chdir_.c \
../osprey/libU77/legacy_chmod_.c \
../osprey/libU77/legacy_dtime_.c \
../osprey/libU77/legacy_etime_.c \
../osprey/libU77/legacy_fdate_.c \
../osprey/libU77/legacy_getarg_.c \
../osprey/libU77/legacy_getcwd_.c \
../osprey/libU77/legacy_getenv_.c \
../osprey/libU77/legacy_getgid_.c \
../osprey/libU77/legacy_getlog_.c \
../osprey/libU77/legacy_getpid_.c \
../osprey/libU77/legacy_getuid_.c \
../osprey/libU77/legacy_gmtime_.c \
../osprey/libU77/legacy_hostnm_.c \
../osprey/libU77/legacy_iargc_.c \
../osprey/libU77/legacy_itime_.c \
../osprey/libU77/legacy_ltime_.c \
../osprey/libU77/legacy_rename_.c \
../osprey/libU77/legacy_sleep_.c \
../osprey/libU77/legacy_stat_.c \
../osprey/libU77/legacy_symlnk_.c \
../osprey/libU77/legacy_system_.c \
../osprey/libU77/legacy_time_.c \
../osprey/libU77/legacy_unlink_.c \
../osprey/libU77/link_.c \
../osprey/libU77/ltime_.c \
../osprey/libU77/malloc_.c \
../osprey/libU77/output.c \
../osprey/libU77/perror_.c \
../osprey/libU77/putenv_.c \
../osprey/libU77/qsort_.c \
../osprey/libU77/rand_.c \
../osprey/libU77/rename_.c \
../osprey/libU77/secnds_.c \
../osprey/libU77/sleep_.c \
../osprey/libU77/srand_.c \
../osprey/libU77/stat_.c \
../osprey/libU77/symlnk_.c \
../osprey/libU77/system_.c \
../osprey/libU77/time_.c \
../osprey/libU77/umask_.c \
../osprey/libU77/unlink_.c \
../osprey/libU77/userror_.c \
../osprey/libU77/ustrace_.c \
../osprey/libU77/wait_.c 

OBJS += \
./osprey/libU77/abort_.o \
./osprey/libU77/access_.o \
./osprey/libU77/alarm_.o \
./osprey/libU77/bes.o \
./osprey/libU77/charutil.o \
./osprey/libU77/chdir_.o \
./osprey/libU77/chmod_.o \
./osprey/libU77/cmd_line.o \
./osprey/libU77/ctime_.o \
./osprey/libU77/date_.o \
./osprey/libU77/dbes.o \
./osprey/libU77/dtime_.o \
./osprey/libU77/etime_.o \
./osprey/libU77/exit_.o \
./osprey/libU77/fdate_.o \
./osprey/libU77/gerror_.o \
./osprey/libU77/getarg_.o \
./osprey/libU77/getcwd_.o \
./osprey/libU77/getenv_.o \
./osprey/libU77/getgid_.o \
./osprey/libU77/gethostname_.o \
./osprey/libU77/getlog_.o \
./osprey/libU77/getpid_.o \
./osprey/libU77/getuid_.o \
./osprey/libU77/gmtime_.o \
./osprey/libU77/hostnm_.o \
./osprey/libU77/iargc_.o \
./osprey/libU77/ierrno_.o \
./osprey/libU77/irand_.o \
./osprey/libU77/itime_.o \
./osprey/libU77/legacy_access_.o \
./osprey/libU77/legacy_alarm_.o \
./osprey/libU77/legacy_chdir_.o \
./osprey/libU77/legacy_chmod_.o \
./osprey/libU77/legacy_dtime_.o \
./osprey/libU77/legacy_etime_.o \
./osprey/libU77/legacy_fdate_.o \
./osprey/libU77/legacy_getarg_.o \
./osprey/libU77/legacy_getcwd_.o \
./osprey/libU77/legacy_getenv_.o \
./osprey/libU77/legacy_getgid_.o \
./osprey/libU77/legacy_getlog_.o \
./osprey/libU77/legacy_getpid_.o \
./osprey/libU77/legacy_getuid_.o \
./osprey/libU77/legacy_gmtime_.o \
./osprey/libU77/legacy_hostnm_.o \
./osprey/libU77/legacy_iargc_.o \
./osprey/libU77/legacy_itime_.o \
./osprey/libU77/legacy_ltime_.o \
./osprey/libU77/legacy_rename_.o \
./osprey/libU77/legacy_sleep_.o \
./osprey/libU77/legacy_stat_.o \
./osprey/libU77/legacy_symlnk_.o \
./osprey/libU77/legacy_system_.o \
./osprey/libU77/legacy_time_.o \
./osprey/libU77/legacy_unlink_.o \
./osprey/libU77/link_.o \
./osprey/libU77/ltime_.o \
./osprey/libU77/malloc_.o \
./osprey/libU77/output.o \
./osprey/libU77/perror_.o \
./osprey/libU77/putenv_.o \
./osprey/libU77/qsort_.o \
./osprey/libU77/rand_.o \
./osprey/libU77/rename_.o \
./osprey/libU77/secnds_.o \
./osprey/libU77/sleep_.o \
./osprey/libU77/srand_.o \
./osprey/libU77/stat_.o \
./osprey/libU77/symlnk_.o \
./osprey/libU77/system_.o \
./osprey/libU77/time_.o \
./osprey/libU77/umask_.o \
./osprey/libU77/unlink_.o \
./osprey/libU77/userror_.o \
./osprey/libU77/ustrace_.o \
./osprey/libU77/wait_.o 

C_DEPS += \
./osprey/libU77/abort_.d \
./osprey/libU77/access_.d \
./osprey/libU77/alarm_.d \
./osprey/libU77/bes.d \
./osprey/libU77/charutil.d \
./osprey/libU77/chdir_.d \
./osprey/libU77/chmod_.d \
./osprey/libU77/cmd_line.d \
./osprey/libU77/ctime_.d \
./osprey/libU77/date_.d \
./osprey/libU77/dbes.d \
./osprey/libU77/dtime_.d \
./osprey/libU77/etime_.d \
./osprey/libU77/exit_.d \
./osprey/libU77/fdate_.d \
./osprey/libU77/gerror_.d \
./osprey/libU77/getarg_.d \
./osprey/libU77/getcwd_.d \
./osprey/libU77/getenv_.d \
./osprey/libU77/getgid_.d \
./osprey/libU77/gethostname_.d \
./osprey/libU77/getlog_.d \
./osprey/libU77/getpid_.d \
./osprey/libU77/getuid_.d \
./osprey/libU77/gmtime_.d \
./osprey/libU77/hostnm_.d \
./osprey/libU77/iargc_.d \
./osprey/libU77/ierrno_.d \
./osprey/libU77/irand_.d \
./osprey/libU77/itime_.d \
./osprey/libU77/legacy_access_.d \
./osprey/libU77/legacy_alarm_.d \
./osprey/libU77/legacy_chdir_.d \
./osprey/libU77/legacy_chmod_.d \
./osprey/libU77/legacy_dtime_.d \
./osprey/libU77/legacy_etime_.d \
./osprey/libU77/legacy_fdate_.d \
./osprey/libU77/legacy_getarg_.d \
./osprey/libU77/legacy_getcwd_.d \
./osprey/libU77/legacy_getenv_.d \
./osprey/libU77/legacy_getgid_.d \
./osprey/libU77/legacy_getlog_.d \
./osprey/libU77/legacy_getpid_.d \
./osprey/libU77/legacy_getuid_.d \
./osprey/libU77/legacy_gmtime_.d \
./osprey/libU77/legacy_hostnm_.d \
./osprey/libU77/legacy_iargc_.d \
./osprey/libU77/legacy_itime_.d \
./osprey/libU77/legacy_ltime_.d \
./osprey/libU77/legacy_rename_.d \
./osprey/libU77/legacy_sleep_.d \
./osprey/libU77/legacy_stat_.d \
./osprey/libU77/legacy_symlnk_.d \
./osprey/libU77/legacy_system_.d \
./osprey/libU77/legacy_time_.d \
./osprey/libU77/legacy_unlink_.d \
./osprey/libU77/link_.d \
./osprey/libU77/ltime_.d \
./osprey/libU77/malloc_.d \
./osprey/libU77/output.d \
./osprey/libU77/perror_.d \
./osprey/libU77/putenv_.d \
./osprey/libU77/qsort_.d \
./osprey/libU77/rand_.d \
./osprey/libU77/rename_.d \
./osprey/libU77/secnds_.d \
./osprey/libU77/sleep_.d \
./osprey/libU77/srand_.d \
./osprey/libU77/stat_.d \
./osprey/libU77/symlnk_.d \
./osprey/libU77/system_.d \
./osprey/libU77/time_.d \
./osprey/libU77/umask_.d \
./osprey/libU77/unlink_.d \
./osprey/libU77/userror_.d \
./osprey/libU77/ustrace_.d \
./osprey/libU77/wait_.d 


# Each subdirectory must supply rules for building sources it contributes
osprey/libU77/%.o: ../osprey/libU77/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


