#  Define build parameters

BUILD_BASE     = ../../../osprey/include
override BUILD_COMPILER = GNU

#  Include setup file which will then include Makefile.base
include ../../..//osprey/Makefile.gsetup
