################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
C_DEPS := 
EXECUTABLES := 

# Every subdirectory with source files must be described here
SUBDIRS := \
osprey-gcc-4.2.0/libstdc++-v3/libmath \
osprey-gcc-4.2.0/libiberty \
osprey-gcc-4.2.0/libdecnumber \
osprey-gcc-4.2.0/libcpp \
osprey-gcc-4.2.0/host-x86_64-redhat-linux/libiberty \
osprey-gcc-4.2.0/host-x86_64-redhat-linux/libdecnumber \
osprey-gcc-4.2.0/host-x86_64-redhat-linux/libcpp \
osprey-gcc-4.2.0/host-x86_64-redhat-linux/gcc \
osprey-gcc-4.2.0/host-x86_64-redhat-linux/gcc/build \
osprey-gcc-4.2.0/host-x86_64-redhat-linux/fixincludes \
osprey-gcc-4.2.0/gcc \
osprey-gcc-4.2.0/gcc/cp \
osprey-gcc-4.2.0/gcc/config/xtensa \
osprey-gcc-4.2.0/gcc/config \
osprey-gcc-4.2.0/gcc/config/vax \
osprey-gcc-4.2.0/gcc/config/v850 \
osprey-gcc-4.2.0/gcc/config/stormy16 \
osprey-gcc-4.2.0/gcc/config/sparc \
osprey-gcc-4.2.0/gcc/config/soft-fp \
osprey-gcc-4.2.0/gcc/config/sh \
osprey-gcc-4.2.0/gcc/config/score \
osprey-gcc-4.2.0/gcc/config/s390 \
osprey-gcc-4.2.0/gcc/config/rs6000 \
osprey-gcc-4.2.0/gcc/config/pdp11 \
osprey-gcc-4.2.0/gcc/config/pa \
osprey-gcc-4.2.0/gcc/config/mt \
osprey-gcc-4.2.0/gcc/config/mn10300 \
osprey-gcc-4.2.0/gcc/config/mmix \
osprey-gcc-4.2.0/gcc/config/mips \
osprey-gcc-4.2.0/gcc/config/mcore \
osprey-gcc-4.2.0/gcc/config/m68k \
osprey-gcc-4.2.0/gcc/config/m68hc11 \
osprey-gcc-4.2.0/gcc/config/m32r \
osprey-gcc-4.2.0/gcc/config/m32c \
osprey-gcc-4.2.0/gcc/config/iq2000 \
osprey-gcc-4.2.0/gcc/config/ia64 \
osprey-gcc-4.2.0/gcc/config/i386 \
osprey-gcc-4.2.0/gcc/config/h8300 \
osprey-gcc-4.2.0/gcc/config/frv \
osprey-gcc-4.2.0/gcc/config/fr30 \
osprey-gcc-4.2.0/gcc/config/crx \
osprey-gcc-4.2.0/gcc/config/cris \
osprey-gcc-4.2.0/gcc/config/c4x \
osprey-gcc-4.2.0/gcc/config/bfin \
osprey-gcc-4.2.0/gcc/config/avr \
osprey-gcc-4.2.0/gcc/config/arm \
osprey-gcc-4.2.0/gcc/config/arc \
osprey-gcc-4.2.0/gcc/config/alpha \
osprey-gcc-4.2.0/fixincludes \
osprey-gcc-4.2.0/build-x86_64-redhat-linux/libiberty \
osprey-gcc-4.2.0/build-x86_64-redhat-linux/fixincludes \
osprey-gcc/libiberty \
osprey-gcc/libcpp \
osprey-gcc/gcc \
osprey-gcc/gcc/cp \
osprey-gcc/gcc/config/xtensa \
osprey-gcc/gcc/config \
osprey-gcc/gcc/config/vax \
osprey-gcc/gcc/config/v850 \
osprey-gcc/gcc/config/stormy16 \
osprey-gcc/gcc/config/sparc \
osprey-gcc/gcc/config/sh \
osprey-gcc/gcc/config/s390 \
osprey-gcc/gcc/config/rs6000 \
osprey-gcc/gcc/config/pdp11 \
osprey-gcc/gcc/config/pa \
osprey-gcc/gcc/config/ns32k \
osprey-gcc/gcc/config/mn10300 \
osprey-gcc/gcc/config/mmix \
osprey-gcc/gcc/config/mips \
osprey-gcc/gcc/config/mcore \
osprey-gcc/gcc/config/m68k \
osprey-gcc/gcc/config/m68hc11 \
osprey-gcc/gcc/config/m32r \
osprey-gcc/gcc/config/iq2000 \
osprey-gcc/gcc/config/ip2k \
osprey-gcc/gcc/config/ia64 \
osprey-gcc/gcc/config/i860 \
osprey-gcc/gcc/config/i386 \
osprey-gcc/gcc/config/h8300 \
osprey-gcc/gcc/config/frv \
osprey-gcc/gcc/config/fr30 \
osprey-gcc/gcc/config/cris \
osprey-gcc/gcc/config/c4x \
osprey-gcc/gcc/config/bfin \
osprey-gcc/gcc/config/avr \
osprey-gcc/gcc/config/arm \
osprey-gcc/gcc/config/arc \
osprey-gcc/gcc/config/alpha \
osprey-gcc/fixincludes \
osprey/wgen \
osprey/tools/tests \
osprey/testsuite/cases/single_src_cases/wopt \
osprey/testsuite/cases/single_src_cases/wgen \
osprey/testsuite/cases/single_src_cases/vho \
osprey/testsuite/cases/single_src_cases/misc \
osprey/testsuite/cases/single_src_cases/kgccfe \
osprey/testsuite/cases/single_src_cases/kg++fe \
osprey/testsuite/cases/single_src_cases/com \
osprey/testsuite/cases/single_src_cases/cg/x8664 \
osprey/testsuite/cases/single_src_cases/cg \
osprey/targdir/wopt \
osprey/targdir/whirl2f \
osprey/targdir/whirl2c \
osprey/targdir/wgen \
osprey/targdir/targ_info \
osprey/targdir/lw_inline \
osprey/targdir/lno \
osprey/targdir/libunwindP \
osprey/targdir/libspin_4_2_0 \
osprey/targdir/libiberty \
osprey/targdir/libelfutil \
osprey/targdir/libelf \
osprey/targdir/libdwarf \
osprey/targdir/libcomutil \
osprey/targdir/libcmplrs \
osprey/targdir/ir_tools \
osprey/targdir/ipl \
osprey/targdir/ipa \
osprey/targdir/driver \
osprey/targdir/cg \
osprey/targdir/be \
osprey/libunwind/utils \
osprey/libunwind/producer \
osprey/libunwind/consumer \
osprey/libu/waio \
osprey/libu/waio/mpp \
osprey/libu/waio/c1 \
osprey/libu/vms \
osprey/libu/util \
osprey/libu/util/posix \
osprey/libu/util/mpp \
osprey/libu/util/i3e \
osprey/libu/util/c1 \
osprey/libu/trbk \
osprey/libu/trbk/mpp \
osprey/libu/trbk/c1 \
osprey/libu/tblmgr \
osprey/libu/numconv/mpp \
osprey/libu/multi/posix \
osprey/libu/multi \
osprey/libu/ieg/mpp \
osprey/libu/ieg \
osprey/libu/ibm/mpp \
osprey/libu/ibm \
osprey/libu/ffio \
osprey/libu/ffio/posix \
osprey/libu/ffio/c1 \
osprey/libu/errmsg \
osprey/libu/clib \
osprey/libu/clib/c1 \
osprey/libu/aqio \
osprey/libopenmp \
osprey/libopen64rt/x8664 \
osprey/libopen64rt \
osprey/libm \
osprey/libm/mips \
osprey/libm/mips/extra \
osprey/libkapi \
osprey/libiberty \
osprey/libhugetlbfs \
osprey/libhugetlbfs/tests \
osprey/libfi/subrtn \
osprey/libfi/prodsum \
osprey/libfi/mpp_util \
osprey/libfi/mpp_shift \
osprey/libfi/mpp_scan \
osprey/libfi/mpp_reduce \
osprey/libfi/mpp_pre \
osprey/libfi/matrix \
osprey/libfi/mathlb \
osprey/libfi/element \
osprey/libfi/dotprod \
osprey/libfi/char \
osprey/libfi/array \
osprey/libf90 \
osprey/libf/tape \
osprey/libf/tape/c1 \
osprey/libf/pxf \
osprey/libf/fort \
osprey/libf/fio \
osprey/libf/fio/c1 \
osprey/libf/auxarr/c1 \
osprey/libelfutil \
osprey/libelf/po \
osprey/libelf/lib \
osprey/libdwarf/libdwarf \
osprey/libdwarf \
osprey/libdwarf/dwarfdump \
osprey/libcsup/msgnew \
osprey/libcsup/math \
osprey/libcsup/gen \
osprey/libcmplrs \
osprey/libcif \
osprey/libacml_mv/src \
osprey/libacml_mv/src/gas \
osprey/libU77 \
osprey/libI77 \
osprey/libF77 \
osprey/libF77/mips/quad \
osprey/kgccfe \
osprey/kgccfe/gnu \
osprey/kgccfe/gnu/rs6000 \
osprey/kgccfe/gnu/ppc32 \
osprey/kgccfe/gnu/objc \
osprey/kgccfe/gnu/loongson \
osprey/kgccfe/gnu/java \
osprey/kgccfe/gnu/intl \
osprey/kgccfe/gnu/ia64 \
osprey/kgccfe/gnu/i386 \
osprey/kgccfe/gnu/fixinc \
osprey/kgccfe/gnu/f \
osprey/kgccfe/gnu/cp \
osprey/kgccfe/gnu/config/xtensa \
osprey/kgccfe/gnu/config/we32k \
osprey/kgccfe/gnu/config/vax \
osprey/kgccfe/gnu/config/v850 \
osprey/kgccfe/gnu/config \
osprey/kgccfe/gnu/config/stormy16 \
osprey/kgccfe/gnu/config/sparc \
osprey/kgccfe/gnu/config/sh \
osprey/kgccfe/gnu/config/s390 \
osprey/kgccfe/gnu/config/rs6000 \
osprey/kgccfe/gnu/config/romp \
osprey/kgccfe/gnu/config/ppc32 \
osprey/kgccfe/gnu/config/pj \
osprey/kgccfe/gnu/config/pdp11 \
osprey/kgccfe/gnu/config/pa \
osprey/kgccfe/gnu/config/ns32k \
osprey/kgccfe/gnu/config/mn10300 \
osprey/kgccfe/gnu/config/mn10200 \
osprey/kgccfe/gnu/config/mmix \
osprey/kgccfe/gnu/config/mcore \
osprey/kgccfe/gnu/config/m88k \
osprey/kgccfe/gnu/config/m68k \
osprey/kgccfe/gnu/config/m68hc11 \
osprey/kgccfe/gnu/config/m32r \
osprey/kgccfe/gnu/config/loongson \
osprey/kgccfe/gnu/config/ia64 \
osprey/kgccfe/gnu/config/i960 \
osprey/kgccfe/gnu/config/i860 \
osprey/kgccfe/gnu/config/i386 \
osprey/kgccfe/gnu/config/i370 \
osprey/kgccfe/gnu/config/h8300 \
osprey/kgccfe/gnu/config/fr30 \
osprey/kgccfe/gnu/config/elxsi \
osprey/kgccfe/gnu/config/dsp16xx \
osprey/kgccfe/gnu/config/d30v \
osprey/kgccfe/gnu/config/cris \
osprey/kgccfe/gnu/config/convex \
osprey/kgccfe/gnu/config/clipper \
osprey/kgccfe/gnu/config/c4x \
osprey/kgccfe/gnu/config/avr \
osprey/kgccfe/gnu/config/arm \
osprey/kgccfe/gnu/config/arc \
osprey/kgccfe/gnu/config/alpha \
osprey/kgccfe/gnu/config/a29k \
osprey/kgccfe/gnu/config/SL \
osprey/kgccfe/gnu/config/1750a \
osprey/kgccfe/gnu/SL \
osprey/kgccfe/gnu/MIPS \
osprey/kg++fe \
osprey/kg++fe/gnu \
osprey/kg++fe/gnu/rs6000 \
osprey/kg++fe/gnu/ppc32 \
osprey/kg++fe/gnu/loongson \
osprey/kg++fe/gnu/intl \
osprey/kg++fe/gnu/ia64 \
osprey/kg++fe/gnu/i386 \
osprey/kg++fe/gnu/cp \
osprey/kg++fe/gnu/config/xtensa \
osprey/kg++fe/gnu/config/we32k \
osprey/kg++fe/gnu/config/vax \
osprey/kg++fe/gnu/config/v850 \
osprey/kg++fe/gnu/config \
osprey/kg++fe/gnu/config/stormy16 \
osprey/kg++fe/gnu/config/sparc \
osprey/kg++fe/gnu/config/sh \
osprey/kg++fe/gnu/config/s390 \
osprey/kg++fe/gnu/config/romp \
osprey/kg++fe/gnu/config/ppc32 \
osprey/kg++fe/gnu/config/pj \
osprey/kg++fe/gnu/config/pdp11 \
osprey/kg++fe/gnu/config/pa \
osprey/kg++fe/gnu/config/ns32k \
osprey/kg++fe/gnu/config/mn10300 \
osprey/kg++fe/gnu/config/mn10200 \
osprey/kg++fe/gnu/config/mmix \
osprey/kg++fe/gnu/config/mcore \
osprey/kg++fe/gnu/config/m88k \
osprey/kg++fe/gnu/config/m68k \
osprey/kg++fe/gnu/config/m68hc11 \
osprey/kg++fe/gnu/config/m32r \
osprey/kg++fe/gnu/config/loongson \
osprey/kg++fe/gnu/config/ia64 \
osprey/kg++fe/gnu/config/i960 \
osprey/kg++fe/gnu/config/i860 \
osprey/kg++fe/gnu/config/i386 \
osprey/kg++fe/gnu/config/i370 \
osprey/kg++fe/gnu/config/h8300 \
osprey/kg++fe/gnu/config/fr30 \
osprey/kg++fe/gnu/config/elxsi \
osprey/kg++fe/gnu/config/dsp16xx \
osprey/kg++fe/gnu/config/d30v \
osprey/kg++fe/gnu/config/cris \
osprey/kg++fe/gnu/config/convex \
osprey/kg++fe/gnu/config/clipper \
osprey/kg++fe/gnu/config/c4x \
osprey/kg++fe/gnu/config/avr \
osprey/kg++fe/gnu/config/arm \
osprey/kg++fe/gnu/config/arc \
osprey/kg++fe/gnu/config/alpha \
osprey/kg++fe/gnu/config/a29k \
osprey/kg++fe/gnu/config/SL \
osprey/kg++fe/gnu/config/1750a \
osprey/kg++fe/gnu/SL \
osprey/kg++fe/gnu/MIPS \
osprey/ir_tools \
osprey/ipa/common \
osprey/init/ia64 \
osprey/gorc/frays \
osprey/fake_ld \
osprey/driver \
osprey/cygnus/opcodes \
osprey/cygnus/libiberty \
osprey/cygnus/libiberty/testsuite \
osprey/cygnus/ld \
osprey/cygnus/bfd \
osprey/cygnus/bfd/doc \
osprey/crayf90/fe90 \
osprey/common/util \
osprey/common/util/x8664 \
osprey/common/util/pr1 \
osprey/common/util/ppc32 \
osprey/common/util/loongson \
osprey/common/util/ia64 \
osprey/common/util/ia32/IA32_host \
osprey/common/util/SL \
osprey/common/util/MIPS \
osprey/common/targ_info/access \
osprey/common/ipfec_targ_info/access \
osprey/common/com/x8664 \
osprey/common/com/ppc32 \
osprey/common/com/loongson \
osprey/common/com/ia64 \
osprey/common/com/SL \
osprey/common/com/NVISA \
osprey/common/com/MIPS \
osprey/be/whirl2c \
osprey/be/opt \
osprey/arith \
libspin \

